### DISCUSSION TITLE
curl error message

### DISCUSSION THREAD

**Discussion by ElToro1966** [Altinity/clickhouse-backup#1087] [Q&A] [answered]
I keep getting this at the end when running clickhouse-backup using sftp, both for _local_ and _remote_, _incremental_ and _full_:
```
...
2025/02/11 10:40:24.862567  info clickhouse connection closed logger=clickhouse
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

My config file looks like this:
```
general:
 remote_storage: sftp
 backups_to_keep_local: 7 # keep 7 last backups locally.
 backups_to_keep_remote: 0 # sftp server is responsible for cleanup.
clickhouse:
 username: default
 password: ************
 host: localhost
 port: 9000
 disk_mapping: {}
 skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  - _temporary_and_external_tables.*
sftp:
 address: 10.0.0.25
 username: backup 
 password: ************
 key: "/home/clickhouse/.ssh/clickhouse_backup"
 port: 22
 path: /mnt/drive02/clickhouse-backups/IB/
```

Everything seems to be working fine though, and I get both local and remote backups, both full and incremental.
