### DISCUSSION TITLE
Is there a way to create remote backup without key or password

### DISCUSSION THREAD

**Discussion by gavishdewangan** [Altinity/clickhouse-backup#1095] [Q&A] [answered]
Is there a way to create remote backup without key or password. If we mount private key of remote server to clickhouse backup container will it be able to create a remote backup with that key, so that explicitly create remote command can be called without key or password.
Is it possible?

**Comment by Slach** [comment, marked as answer]
look https://github.com/Altinity/clickhouse-backup?tab=readme-ov-file#explain-config-parameters

use environment variables CLICKHOUSE_USER and CLICKHOUSE_PASSWORD and mount secrets for these variables

**Reply by gavishdewangan** [reply]
but how will mounting clickhouse username and password work here?

**Reply by Slach** [reply]
How exactly do you run clickhuse-backup? is this docker container? kubernetes? or just command line in standalone linux system?

**Reply by gavishdewangan** [reply]
as a container of kubernetes pod

**Reply by Slach** [reply]
look to 
kubectl explain pod.spec.containers.env
kubectl explain pod.spec.containers.env.valueFrom

do you use clickhouse-operator?
if yes, then change your `kind: ClickHouseInstallation` manifest with something like that

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
stringData:
  CLICKHOUSE_USERNAME: "user"
  CLIKCHOUSE_PASSWORD: "password"  
---
apiVersion: clickhouse.altinity.com/v1
metadata:
  name: example
spec:
  templates:
    podTemplates:
    - name: backup-with-env
      spec:
        containers:
        - name: clickhouse-backup
          image: altinity/clickhouse-backup:stable
          env:
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backup-credentials
                key: CLICKHOUSE_PASSWORD 
          - name: CLICKHOUSE_USERNAME
            valueFrom:
              secretKeyRef:
                name: backup-credentials
                key: CLICKHOUSE_USERNAME
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
   defaults:
     templates:
       podTemplate: backup-with-env                
```

**Reply by gavishdewangan** [reply]
Still how will mounting CLICKHOUSE_USER and CLICKHOUSE_PASSWORD affect remote access from backup container.
If it is server username password, then we don't have access to it at the time of installation so it won't work.
We have only private key.

**Reply by Slach** [reply]
which exactly kubernetes environment do you use for manage clickhouse-server?
altinity clickhouse-operato? bitnami helm chart? something which you own self?

**Reply by gavishdewangan** [reply]
we use altinity clickhouse operator

**Reply by Slach** [reply]
with altinity clickhouse operator i provided proper solution above

you can manage your user in `kind: ClickHouseInstallation` with
```
spec:
  configuration:
    users:
      # use `echo -n "your-password" | sha256sum` to generate password hash
      user/password_sha256_hex: "xxxx" 
```

**Reply by Slach** [reply]
or even simple
```
spec: 
 configuration:
   users:
     backup_user_name/k8s_secret_password: backup-credentials/CLICKHOUSE_PASSWORD
```

in this case password will mount to environment variable and this variable will use as
`<backup_user_name><password from_env=XXX/></backup_users_name>`
