### DISCUSSION TITLE
Release/Upgrade notes for 2.0.0

### DISCUSSION THREAD

**Discussion by samene** [Altinity/clickhouse-backup#600] [Q&A] [answered]
Hi, we are using the version 1.5.2 of clickhouse-backup and recently upgraded to the 2.1.3 image. The very first thing that broke for us was a HTTP 201 instead of a HTTP 200 in the API call to backup.

Where can we find the release notes for 2.0.x and any special considerations when upgrading from 1.x to 2.x?

**Comment by Slach** [comment]
How exactly do you try to call API backup? 
AFAIK clickhouse-backup return 200 status code for every success backup request

```bash
# clickhouse-backup --version
Version:         2.1.3
Git Commit:      f3e6a5667371bfa122e5a907b68e5004b40251f7
Build Date:      2022-12-26

# curl -vvv http://127.0.0.1:7171/backup/status
*   Trying 127.0.0.1:7171...
* Connected to 127.0.0.1 (127.0.0.1) port 7171 (#0)
> GET /backup/status HTTP/1.1
> Host: 127.0.0.1:7171
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 31 Jan 2023 10:57:47 GMT
< Content-Length: 99
< Content-Type: text/plain; charset=utf-8
<
{"command":"list","status":"success","start":"2023-01-31 04:27:49","finish":"2023-01-31 04:27:49"}
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by samene** [comment]
```failed: [localhost] (item=0) => {"ansible_loop_var": "item", "changed": false, "connection": "close", "content_length": "83", "content_type": "text/plain; charset=utf-8", "cookies": {}, "cookies_string": "", "date": "Thu, 26 Jan 2023 08:46:38 GMT", "elapsed": 0, "item": "0", "msg": "Status code was 201 and not [200]: OK (83 bytes)", "redirected": false, "status": 201, "url": "http://***-clickhouse-estorage-0-0-0.***-clickhouse-estorage-0-0.***-cloud.svc.cluster.local:7171/backup/create?name=backup_1674722704-0"}```

This is  our ansible playbook's output that does the backup

**Comment by Slach** [comment]
could you share your ansible playbook part which call API? not just execution log?

**Comment by samene** [comment]
Nothing special

```
- name: Trigger backup on all shards
  uri:
    url: "http://{{ service_prefix }}-{{ item }}-0-0.{{ service_prefix }}-{{ item }}-0.{{ ns.stdout }}.svc.cluster.local:7171/backup/create?{{table_query}}name={{file_name}}-{{ item }}"
    method: POST
  with_sequence: "start=0 count={{ shards |int }}"
```
The variable are all set somewhere else.
