### DISCUSSION TITLE
clickhouse-backup server consumes memory when idle after first backup

### DISCUSSION THREAD

**Discussion by viktordebulat** [Altinity/clickhouse-backup#841] [Q&A]
Why clickhouse-backup server container placed as a sidecar inside clickhouse server pod consumes memory when idle after first backup succeed. Using remote backups on gcs. When just started, container consumes tens of Mi. But after backup made and uploaded, it consumes couple Gi of memory whole day being idle.

Image: `altinity/clickhouse-backup:2.4.30`

Default config overrides:

```
  general:
    remote_storage: gcs
    backups_to_keep_local: -1
    backups_to_keep_remote: 7
    download_concurrency: 1
    upload_concurrency: 1
    restore_schema_on_cluster: "{cluster}"
  clickhouse:
    max_connections: 2
  gcs:
    path: backup/{replica}-{shard}
    client_pool_size: 3
  api:
    create_integration_tables: true
```

Other gcs and clickhouse creds related config set over env variables.

Any ideas how to deal with such issue? Whole pod restart after each backup not an option.

**Comment by Slach** [comment]
which clickhouse-backup version do you use?
please upgrade to 2.4.31
we have some unnecessary memory buffer allocations in some 2.4.x releases

**Reply by viktordebulat** [reply]
![Container memory usage in Grafana](https://github.com/Altinity/clickhouse-backup/assets/43744974/1f34cd77-0866-423d-b9b8-1bb61373c14c)

Bumped to 2.4.31 - the same picture. First it consumes almost nothing. Then, when upload started it consumes more (that's logical, ok) but after finished it consumes the same amount of memory, not increasing. The same picture on each node.

**Reply by viktordebulat** [reply]
@Slach Nope, it proceeded to grow. Meanwhile, on 1 node it grew up to 11 Gi (being idle), and on another node decreased from 2.68 to 1+ Gi

**Reply by Slach** [reply]
what mean WSS here?
how do you calculate this metric?

**Reply by viktordebulat** [reply]
WSS - Working Set Size, container metrics from cAdvisor
container_memory_working_set_bytes

**Comment by Slach** [comment]
most of allocations required during UPLOAD/DOWNLOAD inside remote storage related SDKs
i will appreciate with debuging memory allocations and help how to resolve it

**Comment by Slach** [comment]
what mean `wss` here the same as `rss`?
could you share `curl http://127.0.0.1:7171/metrics | grep -i mem` inside container which have grow memory related metrics?

**Reply by viktordebulat** [reply]
```
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 2.500536e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 9.150332264e+09
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.548252e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 7.299674e+06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.865024e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 2.500536e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 7.2851456e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 5.070848e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 10180
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 7.2327168e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.7922304e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.7084448142689362e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 7.309854e+06
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 9600
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 188800
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 310080
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 5.820376e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.49486e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.769472e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.769472e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 8.6925592e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 3.5500032e+07
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.363279872e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

**Reply by Slach** [reply]
> process_resident_memory_bytes 3.5500032e+07

it means only `33.86 MiB`

could you explain how exactly do you calculate memory on your graph?

**Reply by viktordebulat** [reply]
cAdvisor - container_memory_working_set_bytes
Now memory usage decreased to 4 Gi on 1 node (where 11 Gi was) and became twice bigger on another (from 1.3 to 2.7). No data transfer from clickhouse-backup container was during that time (backup uploaded long ago)

**Comment by Slach** [comment]
could you also run
`curl -o heap.out http://127.0.0.1:7171//debug/pprof/heap?seconds=120`

and share `heap.out` ?

**Reply by viktordebulat** [reply]
```
Failed to open the file heap.out: Permission denied
```

using inside podTemplate
```
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsUser: 101
```

Could it be an issue?

**Reply by Slach** [reply]
`curl -o /tmp/heap.out http://127.0.0.1:7171//debug/pprof/heap?seconds=120`

after it use `kubectl cp` to copy heap.out

**Reply by viktordebulat** [reply]
No file generated.

```
$ curl -o /tmp/heap.out http://127.0.0.1:7171//debug/pprof/heap?seconds=120
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

**Reply by Slach** [reply]
did you wait 120 seconds?

**Reply by viktordebulat** [reply]
It doesn't generate anything, request is ended right after its execution without response

**Comment by nnor1** [comment]
Hello everyone,

we currently have the scenario that our memory utilization often shoots up when creating a backup. However, this only happens when uploading the **last** table (approx. 10 GB), after which the memory utilization remains this high.
Do you have any idea what the reason for this might be?

Setup details:
- Image: altinity/clickhouse-backup:2.6.2
- Node: Memory-optimized | 4 vCPUs | 32 GiB
- DOWNLOAD_CONCURRENCY=2
- UPLOAD_CONCURRENCY=2
- S3_CONCURRENCY=2
- S3_MAX_PARTS_COUNT=5000
- Backup Size 50 GB
- We use Hot and Cold Storage

Thank you
![BackupGraph](https://github.com/user-attachments/assets/1bc915e6-0295-4df1-8e09-44651b2dbb62)

**Reply by Slach** [reply]
@nnor1 could you share
`clickhouse-backup print-config` without sensitive credentials?

**Reply by nnor1** [reply]
@Slach 

```yaml
general:
    remote_storage: s3
    max_file_size: 0
    backups_to_keep_local: -1
    backups_to_keep_remote: 30
    log_level: info
    allow_empty_backups: false
    download_concurrency: 2
    upload_concurrency: 2
    upload_max_bytes_per_second: 0
    download_max_bytes_per_second: 0
    object_disk_server_side_copy_concurrency: 32
    allow_object_disk_streaming: false
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    restore_table_mapping: {}
    retries_on_failure: 3
    retries_pause: 5s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    sharded_operation_mode: ""
    cpu_nice_priority: 15
    io_nice_priority: idle
    rbac_backup_always: true
    rbac_conflict_resolution: recreate
    retriesduration: 5s
    watchduration: 1h0m0s
    fullduration: 24h0m0s

clickhouse:
    username: default
    password: ""
    host: localhost
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    skip_table_engines: []
    timeout: 30m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /etc/clickhouse-server/
    restart_command: exec:systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    max_connections: 2
    debug: false

s3:
    access_key: access_key
    secret_key: secret_key
    bucket: ""
    endpoint: endpoint
    region: us-east-1
    acl: private
    assume_role_arn: ""
    force_path_style: true
    path: backups
    object_disk_path: var/lib/clickhouse/disks/s3
    disable_ssl: false
    compression_level: 1
    compression_format: tar
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: false
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 2
    part_size: 0
    max_parts_count: 5000
    allow_multipart_download: false
    object_labels: {}
    request_payer: ""
    check_sum_algorithm: ""
    debug: false

gcs:
    credentials_file: ""
    credentials_json: ""
    credentials_json_encoded: ""
    embedded_access_key: ""
    embedded_secret_key: ""
    skip_credentials: false
    bucket: ""
    path: ""
    object_disk_path: ""
    compression_level: 1
    compression_format: tar
    debug: false
    force_http: false
    endpoint: ""
    storage_class: STANDARD
    object_labels: {}
    custom_storage_class_map: {}
    client_pool_size: 32
    chunk_size: 0

cos:
    url: ""
    timeout: 2m
    secret_id: ""
    secret_key: ""
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    debug: false

api:
    listen: 0.0.0.0:7171
    enable_metrics: true
    enable_pprof: true
    username: ""
    password: ""
    secure: false
    certificate_file: ""
    private_key_file: ""
    ca_cert_file: ""
    ca_key_file: ""
    create_integration_tables: false
    integration_tables_host: ""
    allow_parallel: false
    complete_resumable_after_restart: true
    watch_is_main_process: false

ftp:
    address: ""
    timeout: 2m
    username: ""
    password: ""
    tls: false
    skip_tls_verify: false
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 6
    debug: false

sftp:
    address: ""
    port: 22
    username: ""
    password: ""
    key: ""
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 6
    debug: false

azblob:
    endpoint_schema: https
    endpoint_suffix: core.windows.net
    account_name: ""
    account_key: ""
    sas: ""
    use_managed_identity: false
    container: ""
    path: ""
    object_disk_path: ""
    compression_level: 1
    compression_format: tar
    sse_key: ""
    buffer_size: 0
    buffer_count: 3
    max_parts_count: 256
    timeout: 4h
    debug: false

custom:
    upload_command: ""
    download_command: ""
    list_command: ""
    delete_command: ""
    command_timeout: 4h
    commandtimeoutduration: 4h0m0s
```
