### DISCUSSION TITLE
How to use vpc endpoint for s3 backup

### DISCUSSION THREAD

**Discussion by shrbb** [Altinity/clickhouse-backup#896] [Q&A] [answered]
I am incurring lot of costs during backups in 
APS3-NatGateway-Bytes and APS3-DataTransfer-Regional-Bytes

i have created a vpc endpoint 's3-clickhouse-backup'
how to use this in config.yaml

is this correct config
```yaml
s3:
  access_key: access_key
  secret_key: it_is_my_super_secret_key
  bucket: my-clickhouse-backup
  endpoint: s3-clickhouse-backup
```
