### DISCUSSION TITLE
create backup err when set use_embedded_backup_restore=true

### DISCUSSION THREAD

**Discussion by honobi** [Altinity/clickhouse-backup#988] [Q&A] [answered]
When I set `use_embedded_backup_restore=true`, executing `clickhouse-backup create` results in the error: `error backup disk `` not exists in system.disks`.

My config file:
```
general:
  backups_to_keep_local: 1
  log_level: info
clickhouse:
  username: root
  password: "testclickhouse"
  host: localhost
  port: 9000
  skip_tables:
    - system.*
    - INFORMATION_SCHEMA.*
    - information_schema.*
  use_embedded_backup_restore: true
  timeout: 240m
```
