### ISSUE TITLE
Backed table with PARTITION BY (a,b) cannot be deleted from remote

### ISSUE THREAD

**Issue by lesandie** [Altinity/clickhouse-backup#1015]
We have a table with a tuple partitioning like this:

`PARTITION BY (toStartOfInterval(timeStamp, toIntervalHour(1)), timePeriod)`

Partition will look like this: `1727434800-4` and file name generated in bucket is `default_1727434800%2D4_0_83_14.tar`

If we issue `clickhouse-backup delete remote <backupname>` all prefixes in the s3 bucket will be deleted but the one with these filenames. 

clickhouse-backup 2.6.1

**Comment by Slach** [comment]
thanks for reporting
looks weird, actually clickhouse-backup just list keys by prefix based on backup name and shall just delete key as is, will try to reproduce in integration tests

**Comment by Slach** [comment]
can't reproduce

```sql
CREATE TABLE t1 (timeStamp DateTime, timePeriod UInt64) ENGINE=MergeTree ORDER BY timeStamp PARTITION BY (toStartOfInterval(timeStamp, toIntervalHour(1)), timePeriod);
INSERT INTO t1 SELECT now()+INTERVAL number MINUTE, number FROM numbers(10);
```
in `clickhouse-backup`
```bash
LOG_LEVEL=debug clickhouse-backup -c /etc/clickhouse-backup/config-s3.yml create test_partition_by
LOG_LEVEL=debug clickhouse-backup -c /etc/clickhouse-backup/config-s3.yml upload test_partition_by
LOG_LEVEL=debug S3_DEBUG=1 clickhouse-backup -c /etc/clickhouse-backup/config-s3.yml delete remote test_partition_by
```

after that
```bash
ls -la /bitnami/minio/data/clickhouse/
```
in minio
and catalog is empty
which `remote_storage` type did you use?

**Comment by lesandie** [comment]
> which remote_storage type did you use?

I'll check

**Comment by lesandie** [comment]
```
general:
  allow_empty_backups: false
  backups_to_keep_local: {N_KEEP} 
  backups_to_keep_remote: {N_KEEP} 
  disable_progress_bar: false
  log_level: info
  max_file_size: 1099511627776
  remote_storage: s3
clickhouse:
  host: localhost
  port: 9000
  username: {USERNAME}
  password: {PASSWORD}
  disk_mapping: {}
  freeze_by_part: false
  log_sql_queries: false
  secure: false
  skip_sync_replica_timeouts: true
  skip_tables:
    - system.*
    - INFORMATION_SCHEMA.*
    - information_schema.*
  skip_verify: false
  sync_replicated_tables: true
  timeout: 5m
s3:
  bucket: dr-backup
  endpoint: "https://{URL}"
  access_key: {ACCESS_KEY}
  secret_key: {SECRET_KEY}
  region: {REGION}
  acl: private
  compression_format: tar
  compression_level: 1
  disable_cert_verification: true
  disable_ssl: false
  force_path_style: false
  part_size: 536870912
  path: {BP_APP}
  sse: ''
  storage_class: STANDARD
```
