### ISSUE TITLE
Is restore of clickhouse backup to a nfs storage mounted on the same pod using custom command possible

### ISSUE THREAD

**Issue by mithunnutanix** [Altinity/clickhouse-backup#1036]

**Comment by Slach** [comment]
Provide more context
Did you successful make backup with regular approach `clickhouse-backup create` command?

What mean `restore` in your case, do you mean copy backuped data to nfs and then try to use it in clickhouse-server?

**Comment by mithunnutanix** [comment]
Hi @Slach . My bad  let me explain it better. I wanted to backup the data to an nfs storage mounted on the pods. How do i use custom commands to achieve this. I am successfully able to create backup. But when i do an upload. I want the backups to be copied to a mounted nfs storage on the pod

**Comment by Slach** [comment]
ok.
you need to use following config
```
general:
  remote_storage: custom
custom:  
  list_command: list.sh
  delete_command: delete.sh
  upload_command: upload.sh
  download_command: download.sh
```

and write *.sh 
scripts

look examples for rsync
https://github.com/Altinity/clickhouse-backup/tree/master/test/integration/rsync/
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-custom-rsync.yml
