### ISSUE TITLE
Supress SQL commands

### ISSUE THREAD

**Issue by ronenb75** [Altinity/clickhouse-backup#1038]
I'm sure it's an easy one, but I couldn't find how.
How can the SQL commands be suppressed from the output?
I find the output too verbose for normal operation and it makes it hard to see what's important.

**Comment by Slach** [comment]
https://github.com/Altinity/clickhouse-backup/#explain-config-parameters

```yaml
clickhouse:
 # env var CLICKHOUSE_LOG_SQL_QUERIES, 
 # logging `clickhouse-backup` SQL queries on `info` level, when true, `debug` level when false
 log_sql_queries : false        
```
