### ISSUE TITLE
invalid cross-device link in recove data 

### ISSUE THREAD

**Issue by amsenhao** [Altinity/clickhouse-backup#1070]
The disk strategy and disk type for log backup are as follows:

`SELECT * FROM system.disks;`

```csv
name, path, free_space, total_space, unreserved_space, keep_free_space, type, is_encrypted, is_read_only, is_write_once, is_remote, is_broken, cache_path
'default', '/opt/data/clickhouse/', 3326083641344, 3960196521984, 3326082232338, 102400, 'local', 0, 0, 0, 0, 0, ''
```

`SELECT * FROM system.storage_policies`

```csv
policy_name, volume_name, volume_priority, disks, volume_type, max_data_part_size, move_factor, prefer_not_to_merge, perform_ttl_move_on_insert, load_balancing

'data_storage', 'sd_volume', 1, ['default'], 'JBOD', 0, 0.2, 0, 1, 'ROUND_ROBIN'
'default', 'default', 1, ['default'], 'JBOD', 0, 0, 0, 1, 'ROUND_ROBIN');
```

and 

I try to restore it to another server to `sdc` disk

system.disks:
```csv
name, path, free_space, total_space, unreserved_space, keep_free_space, type, is_encrypted, is_read_only, is_write_once, is_remote, is_broken, cache_path

'default', '/opt/data/clickhouse/', 492807090176, 497971769344, 492807090176, 102400, 'local', 0, 0, 0, 0, 0, ''

'sdc', '/opt/exCkDatasdc/', 643811074048, 643930419200, 643811074048, 102400, 'local', 0, 0, 0, 0, 0, ''
```

storage_policies 

```csv
policy_name, volume_name, volume_priority, disks, volume_type, max_data_part_size, move_factor, prefer_not_to_merge, perform_ttl_move_on_insert, load_balancing

'data_storage', 'sd_volume', 1, ['default', 'sdc'], 'JBOD', 0, 0.2, 0, 1, 'ROUND_ROBIN'
'default', 'default', 1, ['default'], 'JBOD', 0, 0, 0, 1, 'ROUND_ROBIN'
```

config:
```yaml
clickhouse:
  backup_mutations: true
  check_parts_columns: false
  check_replicas_before_attach: true
  config_dir: /opt/conf/clickhouse/clickhouse-server
  debug: false
  disk_mapping:
    default: /opt/exCkDatasdc
  embedded_backup_disk: ''
  freeze_by_part: false
  freeze_by_part_where: ''
  host: 127.0.0.1
  ignore_not_exists_error_during_freeze: true
  log_sql_queries: true
  max_connections: 0
  port: 9000
  restart_command: exec:systemctl restart clickhouse-server
  restore_as_attach: false
  secure: false
  skip_table_engines: []
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  skip_verify: true
  sync_replicated_tables: true
  timeout: 5m
  tls_ca: ''
  tls_cert: ''
  tls_key: ''
  use_embedded_backup_restore: false
```

but has this error :
```
one of restoreDataRegular go-routine return error: can't copy data to detached 'mhp_percept_login': error during filepath.Walk 
for part '20241128_3_3_0': failed to create hard link
'/opt/exCkDatasdc/backup/20250107155342_10.65.189.128_13.77KB/shadow/espc/mhp_percept_login/default/20241128_3_3_0/checksums.txt' 
-> '/opt/data/clickhouse/store/d15/d15e8a9c-1bc7-45f4-8f0d-6b4b312b43cb/detached/20241128_3_3_0/checksums.txt': 

link /opt/exCkDatasdc/backup/20250107155342_10.65.189.128_13.77KB/shadow/espc/mhp_percept_login/default/20241128_3_3_0/checksums.txt 
/opt/data/clickhouse/store/d15/d15e8a9c-1bc7-45f4-8f0d-6b4b312b43cb/detached/20241128_3_3_0/checksums.txt: invalid cross-device link
```

What should I do to restore to another disk
