### ISSUE TITLE
BackupList bd.Walk return error: operation error S3: ListObjectsV2

### ISSUE THREAD

**Issue by Tor152** [Altinity/clickhouse-backup#1073]
Hi, I need your help, your utility is in my container, I use python to get data from s3, I used s3cmd from the container as a test, and it also works. I took the config I made in the container and uploaded it to the host, everything works from the host, but if I call clickhouse backup from the container, it doesn't cling to s3.
Please tell me what could be the reason.

Mistake:
```
BackupList bd.Walk return error: operation error S3: ListObjectsV2, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "https://<bucket_name><domain_name>/?delimiter=%2F&list-type=2&max-keys=1000&prefix=": dial tcp: lookup <bucket_name><domain_name>on <ip>:53: no such host
```
My config:
```
general:
    remote_storage: s3
    max_file_size: 0
    backups_to_keep_local: 0
    backups_to_keep_remote: 0
    log_level: info
    allow_empty_backups: false
    download_concurrency: 13
    upload_concurrency: 4
    upload_max_bytes_per_second: 0
    download_max_bytes_per_second: 0
    object_disk_server_side_copy_concurrency: 32
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {empty_brackets}
    restore_table_mapping: {empty_brackets}
    retries_on_failure: 3
    retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    sharded_operation_mode: ""
    cpu_nice_priority: 15
    io_nice_priority: idle
    rbac_backup_always: true
    rbac_conflict_resolution: recreate
    retriesduration: 100ms
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: {user}
    password: "{password}"
    host: {host}
    port: {port}
    disk_mapping: {empty_brackets}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    skip_table_engines: []
    timeout: 30m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /etc/clickhouse-server
    restart_command: exec:systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    max_connections: 13
    debug: false
s3:
    access_key: "{access_key}"
    secret_key: "{secret_key}"
    bucket: "{bucket_name}"
    endpoint: "https://{endpoint_url}"
    region: {bucket_location}
    acl: private
    assume_role_arn: ""
    force_path_style: false
    path: ""
    object_disk_path: ""
    disable_ssl: false
    compression_level: 1
    compression_format: gzip
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: false
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {empty_brackets}
    concurrency: 14
    part_size: 0
    max_parts_count: 4000
    allow_multipart_download: false
    object_labels: {empty_brackets}
    request_payer: ""
    check_sum_algorithm: ""
    debug: false
gcs:
    credentials_file: ""
    credentials_json: ""
    credentials_json_encoded: ""
    embedded_access_key: ""
    embedded_secret_key: ""
    skip_credentials: false
    bucket: ""
    path: ""
    object_disk_path: ""
    compression_level: 1
    compression_format: tar
    debug: false
    force_http: false
    endpoint: ""
    storage_class: STANDARD
    object_labels: {empty_brackets}
    custom_storage_class_map: {empty_brackets}
    client_pool_size: 39
    chunk_size: 0
cos:
    url: ""
    timeout: 2m
    secret_id: ""
    secret_key: ""
    path: ""
    compression_format: tar
    compression_level: 1
    debug: false
api:
    listen: localhost:7171
    enable_metrics: true
    enable_pprof: false
    username: ""
    password: ""
    secure: false
    certificate_file: ""
    private_key_file: ""
    ca_cert_file: ""
    ca_key_file: ""
    create_integration_tables: false
    integration_tables_host: ""
    allow_parallel: false
    complete_resumable_after_restart: true
    watch_is_main_process: false
ftp:
    address: ""
    timeout: 2m
    username: ""
    password: ""
    tls: false
    skip_tls_verify: false
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 39
    debug: false
sftp:
    address: ""
    port: 22
    username: ""
    password: ""
    key: ""
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 39
    debug: false
azblob:
    endpoint_schema: https
    endpoint_suffix: core.windows.net
    account_name: ""
    account_key: ""
    sas: ""
    use_managed_identity: false
    container: ""
    path: ""
    object_disk_path: ""
    compression_level: 1
    compression_format: tar
    sse_key: ""
    buffer_size: 0
    buffer_count: 3
    max_parts_count: 256
    timeout: 4h
    debug: false
custom:
    upload_command: ""
    download_command: ""
    list_command: ""
    delete_command: ""
    command_timeout: 4h
    commandtimeoutduration: 4h0m0s

```

**Comment by Tor152** [comment]
My Dockerfile
```
FROM python:3.11.10-alpine3.20
WORKDIR /app

COPY clickhouse-backup /app
COPY requirements.txt /app
RUN pip install -r /app/requirements.txt
RUN apk add wget nano rpm curl s3cmd
RUN wget -O clickhouse-backup-2.6.3-1.x86_64.rpm https://github.com/Altinity/clickhouse-backup/releases/download/v2.6.3/clickhouse-backup-2.6.3-1.x86_64.rpm
RUN rpm -i clickhouse-backup-2.6.3-1.x86_64.rpm && rm -rf clickhouse-backup-2.6.3-1.x86_64.rpm
RUN apk update
RUN chmod 755 /app/main.py
RUN touch /root/crontab.tmp \
    && echo "0 19 * * * python3 /app/main.py" >> /root/crontab.tmp \
    && crontab /root/crontab.tmp
CMD ["/usr/sbin/crond", "-f", "-d", "0"]
```

My docker compose:
```
services:
  clickhouse-backup:
    image: <myrepoip>/<project>/backup-service/clickhouse:2891fc6b
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - clickhouse_0:/var/lib/clickhouse
      - clickhouse_cfg_0:/etc/clickhouse-server
      - dotenv_ch_0:/app/dotenv
  postgres-backup:
    image: <myrepoip>/<project>/backup-service/postgres:2891fc6b
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - pg_backups_0:/root/pg_backups
      - dotenv_pg_0:/app/dotenv
volumes:

  s3bucket_ch:
    driver: local
    driver_opts:
      type: none
      device: /volumes/s3bucket_ch
      o: bind

  s3bucket_pg:
    driver: local
    driver_opts:
      type: none
      device: /volumes/s3bucket_pg
      o: bind

  dotenv_ch_0:
    driver: local
    driver_opts:
      type: none
      device: /volumes/dotenv_ch_0

   dotenv_pg_0:
    driver: local
    driver_opts:
      type: none
      device: /volumes/dotenv_pg_0
      o: bind

  pg_backups_0:
    driver: local
    driver_opts:
      type: none
      device: /volumes/backups_pg_0/
      o: bind

  clickhouse_0:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/clickhouse
      o: bind

  clickhouse_cfg_0:
    driver: local
    driver_opts:
      type: none
      device: /volumes/clickhouse_cfg_0
      o: bind

```

**Comment by Slach** [comment]
you are use 
```yaml
services:
  clickhouse-backup:
    network_mode: "host"
```

what is return in your `host` machine
```
nslookup domain_from_s3_endpoint_url
```
