### ISSUE TITLE
Replication queue grows during clickhouse-backup upload

### ISSUE THREAD

**Issue by telperions** [Altinity/clickhouse-backup#1085]
First of all, thanks for this great program!

#### **Issue Description:**
When running a backup on a single node (`2-0`) for testing, the following behavior occurs:

- **`clickhouse-backup create test`** → Runs successfully with no issues.  
- **`clickhouse-backup upload test`** → The replication queue starts growing immediately and continues until the upload is complete. 
How to avoid replication queue?
Posponed reason for replication_queue table: **Not executing log entry queue-0010707049 for part <part_name> because it is not disjoint with part <other_part_name> that is currently executing.**

![Image](https://github.com/user-attachments/assets/c128517e-ee98-4cd6-9758-514e77443b15)

#### **Configuration Details:**
1. **Cluster Setup:**
   - 3 shards, 2 replicas  
   - Deployed with Altinity Kubernetes Operator on AWS  

2. **Tiered Storage Policy:**
   - Table data exists on both local disk and S3  
   - Example TTL policy:  
     ```sql
     TTL toStartOfWeek(date_time) + toIntervalWeek(2) TO DISK 's3', 
         toStartOfWeek(date_time) + toIntervalWeek(13)
     ```

3. **Data Size:**
   - Largest table: ~1.5 TB per shard  
   - Total data size: ~3 TB per shard  
   - Largest part size: ~120 GB  

#### **ClickHouse Backup Configuration:**
```yaml
general:
    remote_storage: s3
    max_file_size: 0
    backups_to_keep_local: 0
    backups_to_keep_remote: 0
    log_level: info
    allow_empty_backups: false
    download_concurrency: 8
    upload_concurrency: 5
    upload_max_bytes_per_second: 0
    download_max_bytes_per_second: 0
    object_disk_server_side_copy_concurrency: 128
    allow_object_disk_streaming: false
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    restore_table_mapping: {}
    retries_on_failure: 10
    retries_pause: 120s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    sharded_operation_mode: ""
    cpu_nice_priority: 15
    io_nice_priority: idle
    rbac_backup_always: true
    rbac_conflict_resolution: recreate
    retriesduration: 2m0s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: default
    password: ""
    host: localhost
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    skip_table_engines: []
    timeout: 600m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /etc/clickhouse-server/
    restart_command: exec:systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    default_replica_path: /clickhouse/tables/{cluster}/{shard}/{database}/{table}
    default_replica_name: '{replica}'
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    max_connections: 8
    debug: false
s3:
    access_key: ""
    secret_key: ""
    bucket: test-bucket
    endpoint: ""
    region: eu-west-1
    acl: private
    assume_role_arn: ""
    force_path_style: false
    path: backup-path/shard-{shard}
    object_disk_path: backup-path-s3/shard-{shard}
    disable_ssl: false
    compression_level: 1
    compression_format: tar
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: true
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 23
    part_size: 0
    max_parts_count: 4000
    allow_multipart_download: false
    object_labels: {}
    request_payer: ""
    check_sum_algorithm: ""
    debug: false
custom:
    upload_command: ""
    download_command: ""
    list_command: ""
    delete_command: ""
    command_timeout: 24h
    commandtimeoutduration: 24h0m0s
```

**Comment by Slach** [comment]
clickhouse-backup doesn't lock replication queue
look to your disk and network bandwidth

try to decrease upload concurrency, it increase upload time but maybe will allocates less bandwidth

```yaml
general:
 upload_concurrency: 3
 upload_max_bytes_per_second: 20971520 # 20 mbytes/sec ~ 160Mbit/sec
s3:
 concurrency: 3
```
