### ISSUE TITLE
tables with special char `/`  in name skip for upload / download

### ISSUE THREAD

**Issue by andrejs82git** [Altinity/clickhouse-backup#1091]
Hi!

I have:
 - clickhouse (cluster with one server)
 - s3 minio
 - tables on clichouse (distributed, kafka and ReplicatedReplacingMergeTree(target for backup))
 - tables have names like that: **"metrics.dzto.okp"."vq/ChainHistory$_distributed"**, **"metrics.dzto.okp"."vq/ChainHistory$_queue"** **"metrics.dzto.okp"."vq/ChainHistory$"** (metrics.dzto.okp name of database)

I add to docker-compose.yml
```
 clickhouse-backup:
    image: altinity/clickhouse-backup
    container_name: clickhouse-backup
    depends_on:
      - clickhouse-01
    volumes:
      - clickhouse-data-01:/var/lib/clickhouse  # Доступ к данным ClickHouse
      - ./periodic/daily:/etc/periodic/daily
    environment:
      - CLICKHOUSE_HOST=clickhouse-01
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=1234
      - BACKUPS_TO_KEEP_LOCAL=30
      - BACKUPS_TO_KEEP_REMOTE=30
      - REMOTE_STORAGE=s3
      - S3_ACCESS_KEY=1234
      - S3_SECRET_KEY=1234
      - S3_ENDPOINT=http://10.171.1.45:9000
      - S3_BUCKET=backups
      - S3_ACL=private
      - S3_DEBUG=false
      - USE_EMBEDDED_BACKUP_RESTORE=true

    entrypoint: crond -f && sleep Infinity
    restart: unless-stopped

```

Then i enter to docker container 
and run command
```
 clickhouse-backup create
```
and in directory /var/lib/clickhouse/backup/ i see normal backup directory with normal files (metadata.json, shadow/ , metadata/) (size of shadow directory looks normal)

then i run command
```
 clickhouse-backup create_remote
```
log output looks good (no fatal errors). But on s3 i just have one file in directory metadata.json. No any other files. :(

Then i try add -t option(dbname=metrics.dzto.okp and start of my tables=vq/... ):
```
clickhouse-backup create_remote -t metrics.dzto.okp.vq/*
```
and it works!, on s3, at this time, i have all needed files (metadata.json, shadow/ , metadata/).

It a bug? or i do not understand somthing?
