### ISSUE TITLE
upload_concurrency  and  upload_max_bytes_per_second  do not work

### ISSUE THREAD

**Issue by Aurora-CLW** [Altinity/clickhouse-backup#1108]
```yaml
general:
  remote_storage: s3
  backups_to_keep_local: 1 
  backups_to_keep_remote: 3 
  download_concurrency: 1    
  upload_concurrency: 1      
  download_max_bytes_per_second: 5000000 
  upload_max_bytes_per_second: 5000000        
  cpu_nice_priority: 19        
  io_nice_priority: "idle"     
  use_resumable_state: true       
  retries_on_failure: 3                
  retries_pause: 5s 
```
