### ISSUE TITLE
AWS_REGION=minio doesn't work - "The authorization header is malformed; the region 'minio' is wrong; expecting 'minio'

### ISSUE THREAD

**Issue by RogerSik** [Altinity/clickhouse-backup#1110]
Tested with image altinity/clickhouse-backup:2.6.6 and altinity/clickhouse-backup:latest

```
2025-03-14 07:58:09.386 INF pkg/storage/s3.go:49 > [s3:DEBUG] Response
HTTP/2.0 400 Bad Request
Content-Length: 447
Accept-Ranges: bytes
Content-Type: application/xml
Date: Fri, 14 Mar 2025 07:58:09 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: minio
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 182C9C5F625C5973
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 5305
X-Ratelimit-Remaining: 5305
X-Xss-Protection: 1; mode=block


2025-03-14 07:58:09.386 INF pkg/storage/s3.go:49 > [s3:DEBUG] request failed with unretryable error https response error StatusCode: 400, RequestID: 182C9C5F625C5973, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'minio'.
2025-03-14 07:58:09.386 WRN pkg/storage/general.go:252 > BackupList bd.Walk return error: operation error S3: ListObjectsV2, https response error StatusCode: 400, RequestID: 182C9C5F625C5973, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'minio'.
2025-03-14 07:58:09.386 INF pkg/storage/general.go:163 > list_duration=29.533564
2025-03-14 07:58:09.387 INF pkg/clickhouse/clickhouse.go:327 > clickhouse connection closed
2025-03-14 07:58:09.387 INF pkg/server/server.go:1626 > Update backup metrics finish LastBackupCreateLocal=null LastBackupCreateRemote=null LastBackupSizeLocal=0 LastBack
```

Used as Kubernetes deployment with the following region env:
```
  - name: AWS_REGION
    value: 'minio'
```

**Comment by Slach** [comment]
could you try
```
- name: S3_REGION
  value: us-east-1
```

**Comment by Slach** [comment]
any news from your side?

**Comment by RogerSik** [comment]
> any news from your side?

Will try it tomorrow and will the result report here. Sorry I wasn't more at the pc on this day.

**Comment by RogerSik** [comment]
@Slach same error.

Logs:
```
2025-03-17 06:30:50.996 INF pkg/storage/s3.go:49 > [s3:DEBUG] Response
HTTP/2.0 400 Bad Request
Content-Length: 437
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 17 Mar 2025 06:30:50 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: minio
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 182D83596EB3D0C1
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 7670
X-Ratelimit-Remaining: 7670
X-Xss-Protection: 1; mode=block


2025-03-17 06:30:50.997 INF pkg/storage/s3.go:49 > [s3:DEBUG] request failed with unretryable error https response error StatusCode: 400, RequestID: 182D83596EB3D0C1, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'minio'.
2025-03-17 06:30:50.997 WRN pkg/storage/general.go:252 > BackupList bd.Walk return error: operation error S3: ListObjectsV2, https response error StatusCode: 400, RequestID: 182D83596EB3D0C1, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'minio'.
```

The manifest:
```
---
apiVersion: 'clickhouse.altinity.com/v1'
kind: 'ClickHouseInstallation'
metadata:
  name: clickhouse-test
  namespace: clickhouse-operator
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-clickhouse-test
      podTemplate: pod
      serviceTemplate: svc-prometheus
  configuration:
    files:
      config.d/prometheus.xml: |
        <clickhouse>
          <prometheus>
              <endpoint>/metrics</endpoint>
              <port>8001</port>
              <metrics>true</metrics>
              <events>true</events>
              <asynchronous_metrics>true</asynchronous_metrics>
          </prometheus>
        </clickhouse>
    clusters:
      - name: 'clickhouse-test'
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    serviceTemplates:
      - name: svc-prometheus
        metadata:
          labels:
            app: 'clickhouse'
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
            - name: http-metrics
              port: 8001
    podTemplates:
      - name: pod
        spec:
          containers:
            - name: clickhouse
              # https://clickhouse.com/docs/whats-new/changelog
              # https://hub.docker.com/r/clickhouse/clickhouse-server/
              image: clickhouse/clickhouse-server:25.2
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
                - name: metrics
                  containerPort: 8001
              startupProbe:
                httpGet:
                  path: /ping
                  port: http
                  scheme: HTTP
                failureThreshold: 15 # up to 15 minutes wait before restarting
                initialDelaySeconds: 60
                periodSeconds: 60 # check every 60 seconds
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 2Gi

            ### https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes ###
            - name: clickhouse-backup
              # https://hub.docker.com/r/altinity/clickhouse-backup/tags
              # https://github.com/Altinity/clickhouse-backup/blob/master/ChangeLog.md
              image: altinity/clickhouse-backup:2.6.8
              imagePullPolicy: IfNotPresent
              args: ['server']
              env:
                - name: LOG_LEVEL
                  value: 'debug'
                - name: ALLOW_EMPTY_BACKUPS
                  value: 'true'
                - name: API_LISTEN
                  value: '0.0.0.0:7171'
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: 'true'
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: '3'
                # change it for production S3
                - name: REMOTE_STORAGE
                  value: 's3'
                - name: S3_ACL
                  value: 'private'
                - name: S3_REGION
                  value: us-east-1
                - name: S3_ENDPOINT
                  value: 'https://minio.example.com'
                - name: S3_BUCKET
                  value: 'xxx-test'
                # {shard} macro defined by clickhouse-operator
                - name: S3_PATH
                  value: 'backup/shard-{shard}'
                - name: S3_ACCESS_KEY
                  value: 'XXXXX'
                - name: S3_SECRET_KEY
                  value: 'XXXXX'
                - name: S3_FORCE_PATH_STYLE
                  value: 'true'
                - name: S3_DEBUG
                  value: 'true'
                # require to avoid double scraping clickhouse and clickhouse-backup containers
              ports:
                - name: backup-rest
                  containerPort: 7171
    volumeClaimTemplates:
      - name: data-clickhouse-test
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

```

**Comment by Slach** [comment]
>      - name: S3_ENDPOINT
>        value: 'https://minio.example.com'

is this the real URL ? or fake?

Which exactly `minio` version do you use?
How exactly do you install `minio`? is this outside kubernetes or inside the same kubernetes cluster?

**Comment by RogerSik** [comment]
Is a fake URL for GitHub. Exactly like S3_ACCESS_KEY and S3_SECRET_KEY

minio is running on a separate host as docker compose install with valid certificate and reverse proxy (traefik). Is the newest version. Other Application don't have issues with this minio instance.

```
services:
  minio:
    # https://quay.io/repository/minio/minio?tab=tags&tag=latest
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    command: server /data --console-address ":9001"
    container_name: 'minio'
    restart: always
    environment:
      MINIO_SERVER_URL: 'https://minio.example.com'
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'XXXXXX'
      MINIO_BROWSER_REDIRECT_URL: 'https://minio.console.example.com'
      MINIO_DOMAIN: 'minio.example.com'
      MINIO_REGION_NAME: 'minio'
      MINIO_SITE_REGION: 'minio'
    volumes:
      - /backup/minio/data/:/data
    labels:
      # traefik
      - 'traefik.enable=true'
      # minio
      - 'traefik.http.routers.minio.service=minio'
      - 'traefik.http.routers.minio.rule=Host(`minio.example.com`)'
      - 'traefik.http.routers.minio.tls=true'
      - 'traefik.http.routers.minio.tls.certresolver=letsencrypt'
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'
      - 'traefik.http.services.minio.loadbalancer.passhostheader=true'
      # minio-console
      - 'traefik.http.routers.minio-console.service=minio-console'
      - 'traefik.http.routers.minio-console.rule=Host(`minio.console.example.com`)'
      - 'traefik.http.routers.minio-console.tls=true'
      - 'traefik.http.routers.minio-console.tls.certresolver=letsencrypt'
      - 'traefik.http.services.minio-console.loadbalancer.server.port=9001'
```
