### ISSUE TITLE
After update to 2.6.* get 'no such host'

### ISSUE THREAD

**Issue by barebu** [Altinity/clickhouse-backup#1132]
Hi. After upgrading from 2.5.14 to 2.6.14, we started getting a `no such host` resolve error when trying to access s3. 
Full error:
```
2025-04-11 16:54:01.451 WRN pkg/storage/general.go:252 > BackupList bd.Walk return error: operation error S3: ListObjectsV2, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "https://clickhouse-backups-storage.ceph.storage.domain/?delimiter=%2F&list-type=2&max-keys=1000&prefix=hostname.some.domain%2F": dial tcp: lookup clickhouse-backups-storage.ceph.storage.domain on 127.0.0.1:53: no such host
```
config.yaml:
```
---
general:
  disable_progress_bar: true
  remote_storage: s3
  backups_to_keep_remote: 10
  max_file_size: 0
  allow_empty_backups: true
clickhouse:
  username: system
  password: ''
  host: localhost
  port: 9440
  timeout: 2m
  data_path: "/var/lib/clickhouse"
  config_dir: "/etc/clickhouse-server"
  skip_tables:
  - system.*
  sync_replicated_tables: true
  secure: true
  skip_verify: true
s3:
  access_key: access
  secret_key: secret
  endpoint: https://ceph.storage.domain
  bucket: clickhouse-backups-storage
  disable_ssl: false
  allow_multipart_download: true
  concurrency: 3
  path: "/hostname.some.domain"
  compression_format: tar
api:
  listen: ":7171"
  allow_parallel: true
```
If you roll back to 2.5.14, everything works without errors.
