### ISSUE TITLE
two backup destinations with use_embedded_backup_restore

### ISSUE THREAD

**Issue by loomts** [Altinity/clickhouse-backup#1140]
When using embedded backup, without setting embedded_backup_disk, there will be two destinations, e.g. :
1. test-minio/default/ch-cluster-65c0f380-b51b-40ec-adca-26de3e835d54/clickhouse/backup-default-ch-cluster-20250425123322/clickhouse-k45/backup-default-ch-cluster-20250425123322
2. test-minio/backup-default-ch-cluster-20250425123322

The former is composed of S3_PATH in ClickHouse-Backup, which is the path for storing metadata, and the latter is the path where the native S3 backup function of clickhouse stores it. 

https://github.com/Altinity/clickhouse-backup/blob/ab640e9ccfd9ecfa4ca61b65cf467499ad635ca0/pkg/backup/backuper.go#L250-L252

I'm not sure if it's by designed, maybe use S3_PATH as prefix is better.

```
if b.cfg.S3.AccessKey != "" {
	fullBackupName := path.Join(b.cfg.S3.Path, backupName)
	return fmt.Sprintf("S3('%s/%s/','%s','%s')", s3Endpoint, fullBackupName, b.cfg.S3.AccessKey, b.cfg.S3.SecretKey), nil
}
```

**Comment by Slach** [comment]
when you use embedded backup
you have two stage
first - `create` which use `object_disk_path` to execute BACKUP command
second - `upload` which use `path` and upload local metadata files with table definitions

```
clickhouse:
  use_embedded_backup_restore: true
s3:
  path: /path_for_files_during_upload/
  object_disk_path: /path_for_files_during_create/
```
