### ISSUE TITLE
clickhouse-backup with cronJob and k8s operator errors

### ISSUE THREAD

**Issue by stanislav-dombrovskiy-dp** [Altinity/clickhouse-backup#1143]
Hello! Thank you very much for the tool, Can you please help me with backup creating.
I'm using clickhouse in k8s with the operator.
my clickhouse config:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "mtmstat-dwh"
spec:
  configuration:
    users:
      # use cluster Pod CIDR for more security
      backup_service/networks/ip: 0.0.0.0/0
      # PASSWORD=backup_password; echo "$PASSWORD"; echo -n "$PASSWORD" | sha256sum | tr -d '-'
      backup_service/k8s_secret_password: clickhouse-mtmstat-secret/backup_service
      backup_service/grants/query:
        - "GRANT ALL ON *.*"
    settings:
      # to allow scrape metrics via embedded prometheus protocol
      prometheus/endpoint: /metrics
      prometheus/port: 8888
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
    zookeeper:
      nodes:
        - host: keeper-chk-mtmstat
          port: 2181
    clusters:
      - name: "staging"
        layout:
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: svc-template
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
            iam.amazonaws.com/role: "k8s-clickhouse-staging"
            prometheus.io/scrape: 'true'
            prometheus.io/port: '8888'
            prometheus.io/path: '/metrics'
            # need separate prometheus scrape config, look to https://github.com/prometheus/prometheus/issues/3756
            clickhouse.backup/scrape: 'true'
            clickhouse.backup/port: '7171'
            clickhouse.backup/path: '/metrics'
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
          containers:
            - name: clickhouse
              image: "clickhouse/clickhouse-server:24.8.14.39"
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
                - name: db-mtmstat-bootstrap-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "200m"
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9001
                - name: interserver
                  containerPort: 9010
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:2.6.15
              imagePullPolicy: Always
              args: [ "server" ]
              env:
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "3"
                # change it for production S3
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_ACL
                  value: "private"
                - name: S3_ENDPOINT
                  value: https://<endpoint>
                - name: S3_REGION
                  value: us-east-1
                - name: S3_BUCKET
                  value: <bucket_name>
                # {shard} macro defined by clickhouse-operator
                - name: S3_PATH
                  value: backup/mtm
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                # remove it for production S3
                - name: S3_DISABLE_SSL
                  value: "true"
                - name: S3_DEBUG
                  value: "true"
                # require to avoid double scraping clickhouse and clickhouse-backup containers
              ports:
                - name: backup-rest
                  containerPort: 7171
              command:
                - /bin/bash
                - -c
                - "/bin/clickhouse-backup -c /etc/clickhouse-server/config.d/ch-backup.yaml server || /clickhouse-backup -c /etc/clickhouse-server/config.d/ch-backup.yaml server"

          volumes:
            - name: db-mtmstat-bootstrap-configmap-volume
              configMap:
                name: db-mtmstat-bootstrap-configmap
    volumeClaimTemplates:
      - name: data-storage-vc-template
        # Do not delete PVC if installion is dropped
        # reclaimPolicy: Retain
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    serviceTemplates:
      - name: svc-template
        generateName: clickhouse-{chi}
        metadata:
          labels:
            custom.label: "custom.value"
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: DoNotProvision=
            service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
            service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: 'sg-ffffffffff'
        spec:
          type: LoadBalancer
          loadBalancerSourceRanges:
            - 0.0.0.0/32
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
```

Config of the CronJob

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup-cron
spec:
  # At every 10th minute.
  schedule: "*/10 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 1
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: clickhouse-backup-cron
        spec:
          restartPolicy: Never
          containers:
            - name: run-backup-cron
              # https://hub.docker.com/r/clickhouse/clickhouse-client/tags, doesn't support arm64 platform
              # `clickhouse-server` this is the same symlink with `clickhouse-client` to `clickhouse` binary 
              image: clickhouse/clickhouse-server:24.8.14.39
              imagePullPolicy: IfNotPresent
              env:
                # use first replica in each shard, use `kubectl get svc | grep test-backups`
                - name: CLICKHOUSE_SERVICES
                  value: chi-mtmstat-dwh-staging-0-0
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: BACKUP_USER
                  value: backup_service
                - name: BACKUP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-mtmstat-secret
                      key: backup_service
                # change to 1, if you want to make full backup only in $FULL_BACKUP_WEEKDAY (1 - Mon, 7 - Sun)
                - name: MAKE_INCREMENT_BACKUP
                  value: "1"
                - name: FULL_BACKUP_WEEKDAY
                  value: "1"
              command:
                - bash
                - -ec
                - CLICKHOUSE_SERVICES=$(echo $CLICKHOUSE_SERVICES | tr "," " ");
                  BACKUP_DATE=$(date +%Y-%m-%d-%H-%M-%S);
                  declare -A BACKUP_NAMES;
                  declare -A DIFF_FROM;
                  if [[ "" != "$BACKUP_PASSWORD" ]]; then
                  BACKUP_PASSWORD="--password=$BACKUP_PASSWORD";
                  fi;
                  for SERVER in $CLICKHOUSE_SERVICES; do
                  if [[ "1" == "$MAKE_INCREMENT_BACKUP" ]]; then
                  LAST_FULL_BACKUP=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%${SERVER}%' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
                  TODAY_FULL_BACKUP=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%${SERVER}%' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' AND toDate(created) = today() ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD)
                  PREV_BACKUP_NAME=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
                  DIFF_FROM[$SERVER]="";
                  if [[ ("$FULL_BACKUP_WEEKDAY" == "$(date +%u)" && "" == "$TODAY_FULL_BACKUP") || "" == "$PREV_BACKUP_NAME" || "" == "$LAST_FULL_BACKUP" ]]; then
                  BACKUP_NAMES[$SERVER]="full-$BACKUP_DATE";
                  else
                  BACKUP_NAMES[$SERVER]="increment-$BACKUP_DATE";
                  DIFF_FROM[$SERVER]="--diff-from-remote=$PREV_BACKUP_NAME";
                  fi
                  else
                  BACKUP_NAMES[$SERVER]="full-$BACKUP_DATE";
                  fi;
                  echo "set backup name on $SERVER = ${BACKUP_NAMES[$SERVER]}";
                  done;
                  for SERVER in $CLICKHOUSE_SERVICES; do
                  echo "create ${BACKUP_NAMES[$SERVER]} on $SERVER";
                  clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('create ${SERVER}-${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
                  done;
                  for SERVER in $CLICKHOUSE_SERVICES; do
                  while [[ "in progress" == $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='create ${SERVER}-${BACKUP_NAMES[$SERVER]}' FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; do
                  echo "still in progress ${BACKUP_NAMES[$SERVER]} on $SERVER";
                  sleep 1;
                  done;
                  if [[ "success" != $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='create ${SERVER}-${BACKUP_NAMES[$SERVER]}' FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; then
                  echo "error create ${BACKUP_NAMES[$SERVER]} on $SERVER";
                  clickhouse-client -mn --echo -q "SELECT status,error FROM system.backup_actions WHERE command='create ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
                  exit 1;
                  fi;
                  done;
                  for SERVER in $CLICKHOUSE_SERVICES; do
                  echo "upload ${DIFF_FROM[$SERVER]} ${BACKUP_NAMES[$SERVER]} on $SERVER";
                  clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
                  done;
                  for SERVER in $CLICKHOUSE_SERVICES; do
                  while [[ "in progress" == $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; do
                  echo "upload still in progress ${BACKUP_NAMES[$SERVER]} on $SERVER";
                  sleep 5;
                  done;
                  if [[ "success" != $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; then
                  echo "error ${BACKUP_NAMES[$SERVER]} on $SERVER";
                  clickhouse-client -mn --echo -q "SELECT status,error FROM system.backup_actions WHERE command='upload ${DIFF_FROM[$SERVER]} ${SERVER}-${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
                  exit 1;
                  fi;
                  clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('delete local ${SERVER}-${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
                  done;
                  echo "BACKUP CREATED"

```

The error:
```
Code: 60. DB::Exception: Received from chi-mtmstat-dwh-staging-0-0:9000. DB::Exception: Unknown table expression identifier 'system.backup_list' in scope SELECT name FROM system.backup_list WHERE (location = 'remote') AND (name LIKE '%chi-mtmstat-dwh-staging-0-0%') AND (name LIKE '%full%') AND (desc NOT LIKE 'broken%') ORDER BY created DESC LIMIT 1. (UNKNOWN_TABLE)
(query: SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%chi-mtmstat-dwh-staging-0-0%' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw)
```

But it works when I create backup from the console:
```
BACKUP TABLE system.users TO S3('<endpoint>')


   ┌─id───────────────────────────────────┬─status─────────┐
1. │ 8db45ecc-cd05-43d0-b75d-6e13b725072c │ BACKUP_CREATED │
   └──────
────────────────────────────────┴────────────────┘
```

Thank you very much!
