### ISSUE TITLE
can't restore backup on a new instance

### ISSUE THREAD

**Issue by tomiwairembo** [Altinity/clickhouse-backup#1150]
I keep getting this error when I try to restore a remote back up on a new instance in a different kubernetes cluster.

> error="can't drop table `default`.`table_table_3`: open /var/lib/clickhouse/flags/force_drop_table: no such file or directory after 1 times, please check your schema dependencies"

I am running clickhouse on Kubernetes using the altinity clickhouse operator and I am running the create backup and restore as cronjobs on the different clusters.

Create Backup cronjob
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clickhouse-backup
            image: altinity/clickhouse-backup
            env:
            - name: S3_OBJECT_DISK_PATH
              value: object_disks
            - name: REMOTE_STORAGE
              value: s3
            - name: CLICKHOUSE_PASSWORD
              value: password
            - name: S3_ENDPOINT
              value: https://minio-endpoint
            - name: S3_FORCE_PATH_STYLE
              value: "true"
            - name: S3_BUCKET
              value: bucket
            - name: S3_ACCESS_KEY
              value: access_key
            - name: S3_SECRET_KEY
              value: secret_key
            - name: CLICKHOUSE_HOST
              value: hostname
            - name: CLICKHOUSE_USERNAME
              value: backup_user
            - name: CLICKHOUSE_PORT
              value: "9000"
            command:
            - /bin/sh
            - -c
            - clickhouse-backup create_remote backup_$(date +%Y%m%d_%H%M%S)
          restartPolicy: OnFailure
```

Restore Backup CronJob

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-restore-br
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clickhouse-backup
            image: altinity/clickhouse-backup
            env:
            - name: S3_OBJECT_DISK_PATH
              value: object_disks
            - name: REMOTE_STORAGE
              value: s3
            - name: CLICKHOUSE_PASSWORD
              value: "<ADD_PASSWORD>"
            - name: S3_ENDPOINT
              value: https://minio-endpoint
            - name: S3_FORCE_PATH_STYLE
              value: "true"
            - name: S3_BUCKET
              value: bucket
            - name: S3_ACCESS_KEY
              value: access_key
            - name: S3_SECRET_KEY
              value: secret_key
            - name: CLICKHOUSE_HOST
              value: host_name
            - name: CLICKHOUSE_USERNAME
              value: "sink_user"
            - name: CLICKHOUSE_PORT
              value: "9000"
            - name: use_embedded_backup_restore
              value: "true"
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting backup restore"

              # Get the latest backup name
              LATEST_BACKUP=$(clickhouse-backup list remote | grep -E "[0-9]{2}/[0-9]{2}/[0-9]{4}" | sort -k2,3r | head -n 1 | awk '{print $1}')
              
              # Check if we found a backup
              if [ -z "$LATEST_BACKUP" ]; then
                echo "No backups found in remote storage"
                exit 1
              fi
              
              echo "Restoring latest backup: $LATEST_BACKUP"
              clickhouse-backup restore_remote "$LATEST_BACKUP"
          restartPolicy: OnFailure
```
