### ISSUE TITLE
Backup job failure with error another operation is currently running

### ISSUE THREAD

**Issue by NeuZhou** [Altinity/clickhouse-backup#1167]
Debug: create increment-2025-06-19-00-00-16 on chi-adgroup2-advbi-0-2
INSERT INTO system.backup_actions(command) VALUES('create chi-adgroup2-advbi-0-2-increment-2025-06-19-00-00-16')
Received exception from server (version 24.5.1):
Code: 86. DB::Exception: Received from chi-adgroup2-advbi-0-2:9000. DB::HTTPException. DB::HTTPException: Received error from remote server /backup/actions. HTTP status code: 500 Internal Server Error, body: {"status":"error","operation":"create chi-adgroup2-advbi-0-2-increment-2025-06-19-00-00-16","error":"another operation is currently running"}
. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER)
(query: INSERT INTO system.backup_actions(command) VALUES('create chi-adgroup2-advbi-0-2-increment-2025-06-19-00-00-16'))

![Image](https://github.com/user-attachments/assets/5268f882-215c-4309-b097-a2d9353f38b8)

**Comment by Slach** [comment]
looks like your backup job is wrong

`increment-0-2-2025-06-10-00-00-01` was executed before `0-2-increment-2025-06-19-00-00-16`

**Comment by NeuZhou** [comment]
> looks like your backup job is wrong
> 
> `increment-0-2-2025-06-10-00-00-01` was executed before `0-2-increment-2025-06-19-00-00-16`

@Slach  I backup clickhouse with this approach, but the job is stuck with this message, do you know how to fix it? https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

**Comment by Slach** [comment]
@kazhou2024 

did you modify 
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes?

This is a worked approach

Did you read
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster ?

**Comment by Slach** [comment]
could you share
```
kubectl get cronjob --all-namespces
kubectl get chi --all-namespaces
```

**Comment by NeuZhou** [comment]
Thanks @Slach  I modified it to use Azure Block, and it is working for month, but for a bigger cluster is stucked since 5/30 

Here is the clickhouse-backup pod Yaml
```
- name: clickhouse-backup
              image: xxx/clickhouse-backup:latest
              imagePullPolicy: Always
              args: ["server"]
              env:
                 - name: LOG_LEVEL
                   value: "info"
                 - name: ALLOW_EMPTY_BACKUPS
                   value: "true"
                 - name: API_LISTEN
                   value: "0.0.0.0:7171"
                 - name: BACKUPS_TO_KEEP_LOCAL
                   value: "-1"
                 - name: BACKUPS_TO_KEEP_REMOTE
                   value: "35"
                 # INSERT INTO system.backup_actions to execute backup
                 - name: API_CREATE_INTEGRATION_TABLES
                   value: "true"
                 - name: REMOTE_STORAGE
                   value: "azblob"
                 - name: AZBLOB_ACCOUNT_NAME
                   value: "xxx"
                 - name: AZBLOB_CONTAINER
                   value: "backup"
                 - name: AZBLOB_PATH
                   value: clickhouse/backup/{replica}
                 - name: AZBLOB_ACCOUNT_KEY
                   valueFrom:
                      secretKeyRef:
                        name: clickhouse-secret
                        key: account_key
              ports:
                 - name: backup-rest
                   containerPort: 7171
```
![Image](https://github.com/user-attachments/assets/e01bffbf-df45-483f-960d-377e1433851b)

![Image](https://github.com/user-attachments/assets/9d8022c1-bf29-4a8f-bbbb-6eda14d82496)

![Image](https://github.com/user-attachments/assets/260c5bd8-9aed-4a36-a31b-014392fa5e23)

kubectl get pod --all-namespaces | grep backup

![Image](https://github.com/user-attachments/assets/892b215f-ec4c-4aac-9755-76915678c962)


Received exception from server (version 24.5.1):

![Image](https://github.com/user-attachments/assets/732e1fa0-f34b-4a8a-a971-3b590eeb2403)
```
Code: 86. DB::Exception: Received from chi-adgroup1-advbi-3-2:9000. DB::HTTPException. DB::HTTPException: Received error from remote server /backup/actions. HTTP status code: 500 Internal Server Error, body: {"status":"error","operation":"create chi-adgroup1-advbi-3-2-full-2025-06-23-00-00-01","error":"another operation is currently running"}
. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER)
(query: INSERT INTO system.backup_actions(command) VALUES('create chi-adgroup1-advbi-3-2-full-2025-06-23-00-00-01'))
```
