### ISSUE TITLE
GCS Bucket Name Error(`Bucket names must be at least 3 characters in length, got 1: 'b'`)

### ISSUE THREAD

**Issue by Mostafa-wael** [Altinity/clickhouse-backup#1169]
## Issue Summary

When running the ClickHouse backup tool with a fully specified GCS bucket name, the tool attempts to access a bucket named `b`, which is invalid. This results in the following error:

```text
2025-06-23 03:41:41.177 WRN pkg/storage/general.go:252 > BackupList bd.Walk return error: googleapi: got HTTP response code 400 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Details>Bucket names must be at least 3 characters in length, got 1: 'b'</Details></Error>
Latest backup:
ERROR: no backups found in remote storage
```

## Relevant Job Configuration

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-restore
  namespace: clickhouse-2
spec:
  template:
    spec:
      containers:
        - name: clickhouse-restore
          image: altinity/clickhouse-backup:latest
          env:
            - name: REMOTE_STORAGE
              value: gcs
            - name: BACKUPS_TO_KEEP_REMOTE
              value: "7"
            - name: GCS_BUCKET
              value: clickhouse-backups-<projectID>
            - name: GCS_ENDPOINT
              value: https://storage.googleapis.com
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/backup/key.json
            - name: CLICKHOUSE_HOST
              value: clickhouse.clickhouse.svc.cluster.local
            - name: CLICKHOUSE_PORT
              value: "9000"
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              value: "<redacted>"
          volumeMounts:
            - name: backup-sa-key
              mountPath: /etc/backup
              readOnly: true
          command: ["/bin/sh", "-xe", "-c"]
          args:
            - |
              echo "=== ENVIRONMENT ==="
              env
              # ...existing code...
              echo "=== LIST ALL BACKUPS ==="
              LATEST_BACKUP=$(clickhouse-backup list | grep -Eo 'backup-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}' | sort -r | head -n 1)
              echo "Latest backup: $LATEST_BACKUP"
              if [ -z "$LATEST_BACKUP" ]; then
                echo "ERROR: no backups found in remote storage"
                exit 1
              fi
              # ...existing code...
      volumes:
        - name: backup-sa-key
          secret:
            secretName: clickhouse-backup-sa
      restartPolicy: OnFailure
```
