### ISSUE TITLE
Add SFTP remote storage

### ISSUE THREAD

**Issue by devneri** [Altinity/clickhouse-backup#190]
Add the possibility to configure SFTP remote storage

```
sftp:
  address: ""              # SFTP_ADDRESS
  port: ""                 # SFTP_PORT
  username: ""             # SFTP_USERNAME
  password: ""             # SFTP_PASSWORD
  private_key_file: ""     # SFTP_PRIVATE_KEY_FILE
  path: ""                 # SFTP_PATH
  ssh_options: ""          # SFTP_SSH_OPTIONS
  ssh_tunnel: ""           # SFTP_SSH_TUNNEL
```
