### ISSUE TITLE
Can't restore backup with filepath.Walk error

### ISSUE THREAD

**Issue by malcolm061990** [Altinity/clickhouse-backup#191]
Hi. First of all thank you for your backup solution :)
I got the weird situation. My architecture:
4 clickhouse nodes - 2 shards with 2 replicas
3 zookeeper nodes
Replication works good

I am using config.yaml in docker:
```yaml
general:
  remote_storage: s3             # REMOTE_STORAGE
  max_file_size: 1099511627776   # MAX_FILE_SIZE
  disable_progress_bar: false    # DISABLE_PROGRESS_BAR
  backups_to_keep_local: 0       # BACKUPS_TO_KEEP_LOCAL
  backups_to_keep_remote: 0      # BACKUPS_TO_KEEP_REMOTE
  log_level: info                # LOG_LEVEL
clickhouse:
  username: default              # CLICKHOUSE_USERNAME
  password: ""                   # CLICKHOUSE_PASSWORD
  host: ***.elb.us-east-1.amazonaws.com                # CLICKHOUSE_HOST
  port: 9000                     # CLICKHOUSE_PORT
  disk_mapping: {}               # CLICKHOUSE_DISK_MAPPING
  skip_tables:                   # CLICKHOUSE_SKIP_TABLES
    - system.*
  timeout: 5m                    # CLICKHOUSE_TIMEOUT
  freeze_by_part: false          # CLICKHOUSE_FREEZE_BY_PART
  secure: false                  # CLICKHOUSE_SECURE
  skip_verify: false             # CLICKHOUSE_SKIP_VERIFY
  sync_replicated_tables: true   # CLICKHOUSE_SYNC_REPLICATED_TABLES

s3:
  access_key: ***                   # S3_ACCESS_KEY
  secret_key: ***                   # S3_SECRET_KEY
  bucket: ***                       # S3_BUCKET
  endpoint: ""                     # S3_ENDPOINT
  region: us-east-1                # S3_REGION
  acl: private                     # S3_ACL
  force_path_style: false          # S3_FORCE_PATH_STYLE
  path: ""                         # S3_PATH
  disable_ssl: false               # S3_DISABLE_SSL
  part_size: 104857600             # S3_PART_SIZE
  compression_level: 1             # S3_COMPRESSION_LEVEL
  # supports 'tar', 'lz4', 'bzip2', 'gzip', 'sz', 'xz'
  compression_format: gzip         # S3_COMPRESSION_FORMAT
  # empty (default), AES256, or aws:kms
  sse: AES256                      # S3_SSE
  disable_cert_verification: false # S3_DISABLE_CERT_VERIFICATION
  debug: false                     # S3_DEBUG
  storage_class: STANDARD          # S3_STORAGE_CLASS
```

My steps are outside of clickhouse node separated node in docker `docker run --rm -it -v "/home/ec2-user/tmp/config.yaml:/etc/clickhouse-backup/config.yaml" --entrypoint ash -it  alexakulov/clickhouse-backup:1.0.0-beta1`:
```sh
clickhouse-backup -c /etc/clickhouse-backup/config.yaml tables
default.events                    0B         default  
default.events_local              545B       default 

clickhouse-backup -c /etc/clickhouse-backup/config.yaml create -t \
default.events_local default.events_local  # on ReplicatedMergeTree table
2021/04/29 09:16:02  info done                      backup=default.events_local operation=create table=default.events_local
2021/04/29 09:16:02  info done                      backup=default.events_local operation=create

# I got an error
clickhouse-backup -c /etc/clickhouse-backup/config.yaml restore -t default.events_local default.events_local 
2021/04/29 09:18:07 error can't restore 'default.events_local': error during filepath.Walk for partition '202104_0_0_0': lstat /data/clickhouse/backup/default.events_local/shadow/default/events_local/202104_0_0_0: no such file or directory

# directory tree
tree /data/clickhouse/
/data/clickhouse/
├── backup
│   └── default.events_local
│       ├── metadata
│       │   └── default
│       │       └── events_local.json
│       └── metadata.json
└── data
    └── default
        └── events_local
            └── detached
                └── 202104_0_0_0
9 directories, 2 files
```

So, as you see there is no /data/clickhouse/backup/default.events_local/shadow/default/events_local/202104_0_0_0 path.
Where does this path must exist?
