### ISSUE TITLE
Backup distributed table without replication

### ISSUE THREAD

**Issue by svua** [Altinity/clickhouse-backup#204]
How I can backup and restore distributed table without replication?
```
:) show tables

SHOW TABLES

Query id: 7611ee25-49fd-48b2-b28c-3995eece2799

┌─name──────────────┐
│ cell_towers       │
│ cell_towers_local │
└───────────────────┘

2 rows in set. Elapsed: 0.142 sec.

```
```
./clickhouse-backup -c config.yml tables
system.asynchronous_metric_log  (ignored)
system.metric_log       (ignored)
system.query_log        (ignored)
system.trace_log        (ignored)
test.cell_towers_local
```

**Comment by AlexAkulov** [comment]
Try to use [1.0.0-beta2](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/1.0.0-beta2)

**Comment by svua** [comment]
Unfortunately, the backup doesn't work as expected.

```
./clickhouse-backup -v          
Version:         1.0.0.beta2
Git Commit:      c62b18382740a80011c74db23e45247a714b039e
Build Date:      2021-05-28
```

```
./clickhouse-backup -c config.yml tables
test.cell_towers        0B         default  
test.cell_towers_local  568.33MiB  default
```
Expected table size:
Table test.cell_towers has 568.33MiB per shard. I use two pod in k8s with two separate shards - one shard per pod.
2 x 568.33MiB= 1136.66MiB

Backup for distributed table:
```
./clickhouse-backup --config config.yml create --tables=test.cell_towers test.cell_towers
2021/06/08 08:39:38  info done                      backup=test.cell_towers operation=create table=test.cell_towers
2021/06/08 08:39:38  info done                      backup=test.cell_towers operation=create
```

```
cd /var/lib/clickhouse/backup
du -sh *
20K     test.cell_towers

ls test.cell_towers 
metadata  metadata.json
```
Backup for local table:
```
./clickhouse-backup --config config.yml create --tables=test.cell_towers_local test.cell_towers_local
2021/06/08 08:41:57  info done                      backup=test.cell_towers_local operation=create table=test.cell_towers_local
2021/06/08 08:41:57  info done                      backup=test.cell_towers_local operation=create
```
The same situation. The backup takes 20K.
```
du -sh *
20K     test.cell_towers
20K     test.cell_towers_local

ls test.cell_towers_local 
metadata  metadata.json
```

```
general:
  remote_storage: s3
  max_file_size: 1099511627776
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
clickhouse:
  username: USER
  password: "PASSWORD"
  host: clickhouse.cold-data.svc.cluster.local
  port: 9000
  disk_mapping: {}
  skip_tables:
  - system.*
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  log_sql_queries: false
s3:
  access_key: "access_key"
  secret_key: "secret_key"
  bucket: "bucket-name"
  endpoint: ""
  region: us-east-1
  acl: private
  force_path_style: false
  path: ""
  disable_ssl: false
  part_size: 536870912
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  ...
```
