### ISSUE TITLE
Difference in data size for the backups

### ISSUE THREAD

**Issue by vishnudxb** [Altinity/clickhouse-backup#224]
I am running with 6 ClickHouse pods in K8s (3shards*2replicas), with 50GB of data. 

```
NAME                                 READY   STATUS    RESTARTS   AGE
chi-ch-cluster-clickhouse-cp-0-0-0   2/2     Running   0          20d
chi-ch-cluster-clickhouse-cp-0-1-0   2/2     Running   0          20d
chi-ch-cluster-clickhouse-cp-1-0-0   2/2     Running   0          20d
chi-ch-cluster-clickhouse-cp-1-1-0   2/2     Running   0          20d
chi-ch-cluster-clickhouse-cp-2-0-0   2/2     Running   0          20d
chi-ch-cluster-clickhouse-cp-2-1-0   2/2     Running   0          20d
```

I am able to take the backup from `chi-ch-cluster-clickhouse-cp-0-0-0`  and the backup data size for this pod is 50GB which is correct however when taking the backups for `chi-ch-cluster-clickhouse-cp-1-0-0`  and  `chi-ch-cluster-clickhouse-cp-2-0-0`  which is less than 950KB.  

Note: The data size for  `chi-ch-cluster-clickhouse-cp-0-0-0`, `chi-ch-cluster-clickhouse-cp-1-0-0`  and  `chi-ch-cluster-clickhouse-cp-2-0-0` under `/var/lib/clickhouse`   is 50GB.

Not sure why the backup is not working correctly for `chi-ch-cluster-clickhouse-cp-1-0-0`  and  `chi-ch-cluster-clickhouse-cp-2-0-0`  Any idea?

**Comment by Slach** [comment]
could you share results of running
`LOG_LEVEL=debug clichouse-backup create test_backup `
on  `chi-ch-cluster-clickhouse-cp-1-0-0 ` ?

**Comment by vishnudxb** [comment]
```
clickhouse@chi-ch-cluster-clickhouse-cp-1-0-0$ LOG_LEVEL=debug clickhouse-backup create test_backup
2021/07/20 14:53:52 Create backup 'test_backup'
2021/07/20 14:53:52 Copy metadata
2021/07/20 14:53:52   Done.
2021/07/20 14:53:52 Sync 'devdb.mail_stats_local'
2021/07/20 14:53:52 Freeze 'devdb.mail_stats_local'
2021/07/20 14:53:52 Sync 'devdb.mail_campaign_local'
2021/07/20 14:53:52 Freeze 'devdb.mail_campaign_local'
2021/07/20 14:53:52 Sync 'devdb.mail_campaign_treatment_stats_local'
2021/07/20 14:53:52 Freeze 'devdb.mail_campaign_treatment_stats_local'
2021/07/20 14:53:52 Sync 'devdb.events_local'
2021/07/20 14:53:52 Freeze 'devdb.events_local'
2021/07/20 14:53:52 Sync 'devdb.migrations_local'
2021/07/20 14:53:52 Freeze 'devdb.migrations_local'
2021/07/20 14:53:52 Skip 'system.asynchronous_metric_log'
2021/07/20 14:53:52 Skip 'system.metric_log'
2021/07/20 14:53:52 Skip 'system.part_log'
2021/07/20 14:53:52 Skip 'system.query_log'
2021/07/20 14:53:52 Skip 'system.trace_log'
2021/07/20 14:53:52 Move shadow
2021/07/20 14:53:52   Done.
```

Here I was able to create the backup however for some reason the size of the backup is less than 1MB when the data under `/var/lib/clickhouse`  is around 50GB. So not sure what causing this issue.

**Comment by Slach** [comment]
hm, could you share your /etc/clickhouse-backup/config.yaml ?
and results of 
`SELECT * FROM system.disks`
?

**Comment by vishnudxb** [comment]
```
┌─name────┬─path─────────────────┬───free_space─┬──total_space─┬─keep_free_space─┬─type──┐
│ default │ /var/lib/clickhouse/ │ 151030632448 │ 210304475136 │               0 │ local │
└─────────┴──────────────────────┴──────────────┴──────────────┴─────────────────┴───────┘

1 rows in set. Elapsed: 0.002 sec.


```

```
general:
  remote_storage: gcs            # REMOTE_STORAGE
  max_file_size: 1099511627776   # MAX_FILE_SIZE
  disable_progress_bar: false    # DISABLE_PROGRESS_BAR
  backups_to_keep_local: 0       # BACKUPS_TO_KEEP_LOCAL
  backups_to_keep_remote: 14     # BACKUPS_TO_KEEP_REMOTE
  log_level: debug               # LOG_LEVEL
clickhouse:
  username: <username>
  password: <pwd>
  host: localhost
  port: 9000
  disk_mapping: {}               # CLICKHOUSE_DISK_MAPPING
  skip_tables:                   # CLICKHOUSE_SKIP_TABLES
    - system.*
  timeout: 5m                    # CLICKHOUSE_TIMEOUT
  freeze_by_part: false          # CLICKHOUSE_FREEZE_BY_PART
  secure: false                  # CLICKHOUSE_SECURE
  skip_verify: false             # CLICKHOUSE_SKIP_VERIFY
  sync_replicated_tables: true   # CLICKHOUSE_SYNC_REPLICATED_TABLES

gcs:
  credentials_file: /tmp/creds.json
  bucket: bucket-prod
  path: db
  compression_level: 1         # GCS_COMPRESSION_LEVEL
  compression_format: tar      # GCS_COMPRESSION_FORMAT
```
