### ISSUE TITLE
Clickhouse-backup on K8 openshift

### ISSUE THREAD

**Issue by smpa0321** [Altinity/clickhouse-backup#230]
How to containerize the Clickhouse-backup and deploy on kubernetes open-shift environment.

**Comment by Slach** [comment]
if you already use `clickhouse-operator` for Kubernetes in your open-shift environment, just look at manifest examples:
https://github.com/Altinity/clickhouse-operator/blob/master/tests/configs/test-cluster-for-backups.yaml
and
https://github.com/Altinity/clickhouse-operator/blob/master/tests/templates/tpl-clickhouse-backups.yaml#L26-L70

you need re-declare podTemplates[].spec.containers to allow clickhouse-backup have same volume mounts as separate clickhouse-server container

**Comment by olexiyb** [comment]
@AlexAkulov I followed several examples using

https://github.com/Altinity/clickhouse-operator/blob/0.15.0/tests/templates/tpl-clickhouse-backups.yaml
https://github.com/Altinity/clickhouse-operator/blob/0.15.0/tests/configs/test-cluster-for-backups.yaml
as well as

https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

The problem is that in `clickhouse-backup` pod does not have access to actual data

```
# ls -al /var/lib/clickhouse/
total 16
drwxr-sr-x    1 clickhou clickhou      4096 Jan 27 08:48 .
drwxr-xr-x    1 root     root          4096 Dec  1 17:33 ..
drwxr-s---    7 clickhou clickhou      4096 Jan 28 00:00 backup
```

as result I see on S3 only information about metadata but not actual data, basically this is the same issue as https://github.com/AlexAkulov/clickhouse-backup/issues/360#issuecomment-1016244892

**Comment by Slach** [comment]
@olexiyb 
`clickhouse-backup` need access to the same /var/lib/clickhouse/ as main `clickhouse-server` container

could you share your
`kubectl get chi -n <your-chi-namespace> <your-chi-name> -o yaml`

**Comment by olexiyb** [comment]
@Slach I was able to fix this adding `volumeMounts:`
Here is my installation to setup clickhouse on 3 nodes with local ssd drives for maximum performance

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  defaults:
    templates:
      serviceTemplate: svc-template
#      podTemplate: clickhouse-pod-template
#      dataVolumeClaimTemplate: data
  configuration:
    zookeeper:
      nodes:
        - host: prod01-zookeeper.prod01-zookeeper.svc.cluster.local
    settings:
      # https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-logger
      logger/level: information
      compression/case/method: zstd
      disable_internal_dns_cache: 1
      timezone: America/New_York
      prometheus/endpoint: /metrics
      prometheus/port: 8888
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
    # see https://github.com/Altinity/clickhouse-operator/blob/master/docs/quick_start.md#custom-deployment-with-specific-clickhouse-configuration
    profiles:
      default/default_database_engine: Atomic
    users:
      # admin use has 'password_sha256_hex' so actual password value is not published
      writer/password_sha256_hex: <password_sha256_hex>
      writer/networks/ip:
        - "0.0.0.0/0"
        - "::/0"
      # https://clickhouse.com/docs/en/sql-reference/statements/select/group-by/#select-group-by-in-external-memory
      # writer/max_memory_usage: 20000000000
      writer/max_bytes_before_external_group_by: 25000000000
      writer/distributed_aggregation_memory_efficient: 1
      writer/profile: default
      writer/quota: default
      # readonly user has 'password' field specified, not 'password_sha256_hex' as admin user above
      reader/password_sha256_hex: <password_sha256_hex>
      reader/networks/ip:
        - "0.0.0.0/0"
        - "::/0"
      reader/profile: readonly
      reader/quota: default
      profiles:
        readonly/readonly: "1"
      backup/networks/ip:
        - "0.0.0.0/0"
        - "::/0"
      backup/password_sha256_hex: <password_sha256_hex>
    clusters:
      - name: "cluster1"
        templates:
          serviceTemplate: svc-template
        layout:
          shardsCount: 1
          replicas:
            - templates:
                podTemplate: prod1
            - templates:
                podTemplate: prod2
            - templates:
                podTemplate: prod3
  templates:
    volumeClaimTemplates:
      - name: data
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
    podTemplates:
      - name: prod1
        generateName: "prod06-{chi}-{cluster}-{host}"
        metadata:
          annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/port: '8888'
            prometheus.io/path: '/metrics'
            # need separate prometheus scrape config, look to https://github.com/prometheus/prometheus/issues/3756
            clickhouse.backup/scrape: 'true'
            clickhouse.backup/port: '7171'
            clickhouse.backup/path: '/metrics'
          labels:
            app: clickhouse
        spec:
          nodeSelector:
            kubernetes.io/hostname: prod1
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - clickhouse
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:21.3.13.9
              resources:
                requests:
                  cpu: "8"
                  memory: "32G"
              volumeMounts:
                - name: prod06-clickhouse-prod1-volume1
                  mountPath: /var/lib/clickhouse
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:1.2.2
              imagePullPolicy: Always
              volumeMounts:
                - name: prod06-clickhouse-prod1-volume1
                  mountPath: /var/lib/clickhouse
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              envFrom:
                - secretRef:
                    name: aws-credentials
              env:
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "false"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "5"
                - name: BACKUPS_TO_KEEP_LOCAL
                  value: "5"
                # change it for production S3
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_ACL
                  value: "private"
                - name: S3_COMPRESSION_LEVEL
                  value: "5"
                - name: S3_COMPRESSION_FORMAT
                  value: "gzip"
                - name: S3_ENDPOINT
                  value: https://s3.us-east-1.amazonaws.com
                - name: S3_BUCKET
                  value: rke-rancher-backup
                - name: S3_PATH
                  value: prod06-clickhouse
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                # remove it for production S3
                - name: S3_DISTABLE_SSL
                  value: "false"
                - name: S3_DEBUG
                  value: "false"
                # avoiding double scraping clickhouse and clickhouse-backup containers
              ports:
                - name: backup-rest
                  containerPort: 7171
          volumes:
            - name: prod06-clickhouse-prod1-volume1
              persistentVolumeClaim:
                claimName: prod06-clickhouse-prod1-volume1
                readOnly: false
      - name: prod2
        generateName: "prod06-{chi}-{cluster}-{host}"
        metadata:
          labels:
            app: clickhouse
        spec:
          nodeSelector:
            kubernetes.io/hostname: prod2
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - clickhouse
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:21.3.13.9
              resources:
                requests:
                  cpu: "8"
                  memory: "32G"
              volumeMounts:
                - name: prod06-clickhouse-prod2-volume1
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: prod06-clickhouse-prod2-volume1
              persistentVolumeClaim:
                claimName: prod06-clickhouse-prod2-volume1
                readOnly: false
      - name: prod3
        generateName: "prod06-{chi}-{cluster}-{host}"
        metadata:
          labels:
            app: clickhouse
        spec:
          nodeSelector:
            kubernetes.io/hostname: prod3
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - clickhouse
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:21.3.13.9
              resources:
                requests:
                  cpu: "8"
                  memory: "32G"
              volumeMounts:
                - name: prod06-clickhouse-prod3-volume1
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: prod06-clickhouse-prod3-volume1
              persistentVolumeClaim:
                claimName: prod06-clickhouse-prod3-volume1
                readOnly: false
    serviceTemplates:
      - name: svc-template
        generateName: prod06-{chi}
        spec:
          ipFamilyPolicy: PreferDualStack
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP

```
