### ISSUE TITLE
clickhouse-backup list does not list remote backups

### ISSUE THREAD

**Issue by resuni** [Altinity/clickhouse-backup#240]
I am looking at using clickhouse-backup to back up our ClickHouse 18.16.1 cluster to S3-compatible non-Amazon storage. `clickhouse-backup create_backup` runs without error, and I can confirm the backup exists on our S3-compatible storage using s3cmd. However, when I run `clickhouse-backup list`, only the local backup appears in the list. Furthermore, the `delete` and `restore` commands will return an error when attempting to delete or restore a remote backup. 

In order to troubleshoot this, I've set the log level to "debug", but nothing in the debug messages appears to indicate anything is wrong when running the `create_backup` command. How do I go about troubleshooting this? 

My config:
```yaml
general:
  remote_storage: s3
  max_file_size: 1099511627776
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: debug
  allow_empty_backups: false
clickhouse:
  username: default
  password: ""
  host: localhost
  port: 8080
  disk_mapping: {}
  skip_tables:
  - system.*
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  skip_sync_replica_timeouts: true
  log_sql_queries: false
s3:
  access_key: "REDACTED"
  secret_key: "REDACTED"
  bucket: "REDACTED"
  endpoint: "REDACTED"
  region: REDACTED
  acl: private
  force_path_style: false
  path: "REDACTED"
  disable_ssl: false
  part_size: 536870912
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
```
