### ISSUE TITLE
FR: Ability to restore to another database.

### ISSUE THREAD

**Issue by den-crane** [Altinity/clickhouse-backup#269]
We need to restore the same backup 20 times into the same server but into different databases.

```
clickhouse-backup restore bkp01 -c config.yml --remap-schema databaseX:databaseX1,databaseY:databaseY1
clickhouse-backup restore bkp01 -c config.yml --remap-schema databaseX:databaseX2,databaseY:databaseY2
```

original databaseX will restored into databaseX1 and databaseX2

**Comment by mojerro** [comment]
this is a really useful feature

**Comment by mojerro** [comment]
@Slach I can make a PR, and hope to discuss how to deal with the multi databases defined in restore data. Now I just modify the source code for my custom use

**Comment by Slach** [comment]
@mojerro feel free to make PR
I think  `--restore-database-mapping` is more mental name

moreover, you need to add restore_database_mappings to config.go into `ClickHouseConfig` type

**Comment by mojerro** [comment]
There may be different scenarios who want to change the database name, so I think the most flexible way is to let the user determine the source and target databases to restore.

there is an example: restore data have `default.*` and `database.*`, and one hopes to restore `default.*` to `default.*`, `database.*` to `restore.*` .

then he needs to run the restore command with the following 2 args:
```
--source default

--source database  --target restore
```

**Comment by mojerro** [comment]
> 

oh, that's a good idea

**Comment by mojerro** [comment]
the data struct of `--restore-database-mapping` may like this

```json
[{
    source: 'database',
    target: 'restore_database'
},{
    source: 'default',
    target: 'restore_default'
},
...
]
```

for the database not defined in this struct, the program will not deal with it (the database will not be restored).

**Comment by Slach** [comment]
Ok structure looks mental and good

```yaml
clickhouse:
  restore_database_mapping:
    - source: database
       target: restore_database
    - source: default: 
       target: restore_default  
```

moreover, you need use StringClise in main.go and advanced parsing for CLI --restore-database-mapping
and i not sure this will applicable for envconfig and CLICKHOUSE_RESTORE_DATABASE_MAPPING envrionment variable will properly parsed (https://github.com/kelseyhightower/envconfig)

so, I propose more compact structure look to `DisksMapping` inside `config.go`

```
clickhouse:
  restore_database_mapping:
    source_database: restore_database
    default: restore_default  
  
```
