### ISSUE TITLE
Improve performance for download or restore remote backup

### ISSUE THREAD

**Issue by malcolm061990** [Altinity/clickhouse-backup#301]
May be it's related to #142 but anyway the download/restore from remote speed is slowly then upload/create_remote speed.

Here is the configuration:
```yaml
general:
  remote_storage: s3
  max_file_size: 1099511627776
  disable_progress_bar: false
  backups_to_keep_local: 2
  backups_to_keep_remote: 30
  log_level: info
  allow_empty_backups: false
  download_concurrency: 255
  upload_concurrency: 255
clickhouse:
  username: default
  password: ""
  host: ip-10-40-2-21
  port: 9000
  disk_mapping: {}
  skip_tables:
  - system.*
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  skip_sync_replica_timeouts: true
  log_sql_queries: false
s3:
  access_key: access_key
  secret_key: secret_key
  bucket: bucket
  path: path
  endpoint: ""
  region: us-east-1
  acl: private
  force_path_style: false
  disable_ssl: false
  part_size: 0
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 255
api:
  listen: localhost:7171
  enable_metrics: true
  enable_pprof: false
  username: ""
  password: ""
  secure: false
  certificate_file: ""
  private_key_file: ""
  create_integration_tables: false
```

The test dataset is almost 14 Gb.
`create_remote` works in parallel, cool and fast:
```bash
time clickhouse-backup --config /opt/clickhouse/clickhouse-backup/config.yml create_remote full_ch_backup_2021-11-04-TEST
...
2021/11/04 06:10:59  info done                      backup=full_ch_backup_2021-11-04-TEST duration=17.511s operation=upload size=13.91GiB

real	0m18.537s
user	1m54.922s
sys	0m28.236s
```

But `download/restore` from remote takes much more time than uploading to remote. As you see its longer in almost 6 times:
```bash
time clickhouse-backup --config /opt/clickhouse/clickhouse-backup/config.yml download full_ch_backup_2021-11-04-TEST
...
2021/11/04 06:16:00  info done                      backup=full_ch_backup_2021-11-04-TEST duration=1m53.003s operation=download size=13.89GiB

real	1m53.025s
user	0m20.756s
sys	0m38.276s
```

I changed `download_concurrency` and `part_size` to different values - no effect.
How can the download speed be increased?
