### ISSUE TITLE
add Azure test cases for SAS and ManagedIdentities

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#313]
for SAS config example
```
azblob:
  endpoint_suffix: core.windows.net
  account_name: "ACCOUNT_NAME"
  account_key: ""
  sas: "sp=racwdl&st=2021-11-30T12:53:13Z&se=2021-11-30T20:53:13Z&sip=XX.XX.XX.XX&spr=https&sv=2020-08-04&sr=c&sig=XXXXXXXXX%2Ff%2FTTgOTwM4jljh4nq2XXXXXXXXXXXXXXXXXX"
  container: "prod-db-backup-ch"
  path: ""
  compression_level: 1
  compression_format: tar
  sse_key: ""
```

Error message
```
021/11/30 14:01:29 error can't connect to azblob: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20200807102407-24fe552e0870/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:a8a8c3ca-701e-0050-60ea-e5520e000000
Time:2021-11-30T13:01:29.9179074Z, Details: 
   Code: AuthorizationFailure
   PUT https://ACCOUNT_NAME.blob.core.windows.net/prod-db-backup-ch?restype=container&se=2021-11-30t20%3A53%3A13z&sig=REDACTED&sip=162.55.55.148&sp=racwdl&spr=https&sr=c&st=2021-11-30t12XXXXXXXX&sv=2020-08-04&timeout=61
   User-Agent: [Azure-Storage/0.10 (go1.16.5; linux)]
   X-Ms-Client-Request-Id: [061eb82e-8197-44ad-4ff7-33a2e087ff35]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Tue, 30 Nov 2021 13:01:29 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [061eb82e-8197-44ad-4ff7-33a2e087ff35]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [a8a8c3ca-701e-0050-60ea-e5520e000000]
   X-Ms-Version: [2019-12-12]
```
