### ISSUE TITLE
Upload Clickhouse Backup to S3 bucket not happening 

### ISSUE THREAD

**Issue by kishorer00** [Altinity/clickhouse-backup#365]
Hi @Slach, 

Happy that, you are with us for Clickhouse ...

Here is the config file and command, which i am using .... Nothing uploading to S3 bucket.
Manual backups working fine.

command:-
----------
./clickhouse-backup -c new_config.yml create 's3-test'

config.yml :-
```yaml
s3:
  access_key: "ABCD"
  secret_key: "EFGH"
  bucket: "s3-test"
  endpoint: "https://s3-test.s3.us-east-11.amazonaws.com/s3-test"
  region: us-east-11
  acl: private
  assume_role_arn: "arn:aws:s3:::s3-test"
  force_path_style: false
  path: ""
  disable_ssl: false
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 0
  debug: false
```

Is it possible to upload the Backup data to S3 Bucket running the above command?
Or 
do i need to work on any pre-requisites ? or missing something ..? Pls assist me.

-Backup tool version : v.1.2.2
-Clickhouse running on kubernetes environment, Satefulset.

**Comment by Slach** [comment]
You should define
```yaml
general:
  remote_storage: s3
clickhouse:
  skip_tables:
    - INFORMATION_SCHEMA.*
    - information_schema.*
    - system.*   
```

to allow upload to s3 storage and ignore INFORMATION_SCHEMA for latest version of ClickHouse

**Comment by Slach** [comment]
> Clickhouse running on kubernetes environment, Satefulset.

@kishorer00 Did you use clickhouse-operator or use other kubernetes solution?

**Comment by kishorer00** [comment]
Hi Slach,

Updated the config file and run it ...

It's creating the backup locally.  Tried the backup list, its not able to list the backups from S3 Bucket.

Investigated and found that, S3 bucket not responding to the request, due to authentication issues.

Do i need to create a separate Programmatic access user with S3 Full access?

Do i need to create a separate VPC endpoint?

endpoint: "https://s3-test.s3.us-east-11.amazonaws.com/s3-test"  -- Will this work?

Tried:  wget https://s3-test.s3.us-east-11.amazonaws.com/s3-test/test-file.txt  -- Getting 403 FORBIDDEN Error 

If you can update the sample details for the below, that will be helpfull ...
```yaml
s3:
  access_key: "ABCD"
  secret_key: "EFGH"
  bucket: "s3-test"
  endpoint: ""
  region: us-east-11
  acl: private
  assume_role_arn: "arn:aws:s3:::s3-test"
  force_path_style: false
  path: ""
  disable_ssl: false
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 0
  debug: false
```
Thanks in Advance !!!!.

**Comment by Slach** [comment]
`us-east-11` wrong region, try to ` us-east-1`
try to use https://github.com/aws/aws-cli (aws s3 ls) to check your authorization credentials with ARN

Usually, `assume_role_arn` used inside AWS virtual machines (EC2 or EKS worker nodes) and doesn't require access_key and secret_key

**Comment by Slach** [comment]
Moreover, you can setup following settings (or use S3_DEBUG=true environment variable)

```yaml
s3:
 debug: true
```

and try to determine what is going on between clickhouse-backup and S3

**Comment by Slach** [comment]
@kishorer00 is the issue still relevant for you?

**Comment by kishorer00** [comment]
Hi @Slach, 

Yes.. Running into issues. Getting HTTP/1.1 400 Bad Request error now, while listing the backups 

More details on 404 Error,
```
-----------------------------------------------------
2022/01/22 13:41:09  info DEBUG: Response sts/AssumeRole Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: xxx
Content-Type: xxx
Date: xxx
Server: AmazonS3
X-Amz-Id-2:xxx 
X-Amz-Request-Id: xxx
--------------------------------------------------------------------------
```

Here are more details about my test env,

- Running Clickhouse on Statefullsets on AWS EKS  
- Both EKS and S3 on the same Region 
- Able to download the Backups from the local system and upload it to S3 Bucket using aws cli cmds Manually.
- Backup source to S3 Bucket is failing with HTTP/1.1 400 Bad Request error 
- Using the correct region us-east-1
- Below are the config.yml details,

```yaml
s3:
  access_key: "ABCD"
  secret_key: "EFGH"
  bucket: "s3-test"
  endpoint: "https://s3-test.s3.us-east-1.amazonaws.com/s3-test"
  region: us-east-1
  acl: private
  assume_role_arn: "arn:aws:s3:::s3-test"
  force_path_style: false
  path: ""
  disable_ssl: false
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 0
  debug: true
```

Please correct me,if anything missing on the above config.yml file.

Do i need to create any new user in AWS (For access_key and secret_key )? endpoint URL is https ,is that fine?

**Comment by Slach** [comment]
Could you change your s3 settings to:
```yaml
s3:
  endpoint: "" 
  region: us-east-1
  acl: private
  assume_role_arn: "arn:aws:s3:::s3-test"  
  debug: true
```  

run `LOG_LEVEL=debug S3_DEBUG=true clickhouse-backup upload <backup_name>`
and  share full results?

**Comment by kishorer00** [comment]
Hi Slach , 

Updated the config.yml file.  

Output : - 

--------
# ./clickhouse-backup -c config.yml list

```
2022/01/24 11:11:10  info DEBUG: Request sts/AssumeRole Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.amazonaws.com
User-Agent: xxx
Content-Length: xx
Authorization: xxxx
Content-Type: xxx
X-Amz-Date: 20220124
Accept-Encoding: gzip

 -----------------------------------------------------
2022/01/24 16:52:37  info DEBUG: Response sts/AssumeRole Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403
Content-Length: 333
Content-Type: text/xml
Date: Mon, 24 Jan 2022 16:52:36 GMT
X-Amzn-Requestid: xxx

-----------------------------------------------------

**2022/01/24 11:11:11 error InvalidClientTokenId: The security token included in the request is invalid.**
        status code: 403, request id: xxx

----------------------------------------------------------
```

--> Currently, Using my AWS Management Console access_key and secret_key. Able to upload and download files to S3 Bucket.
--> Do i need to create a separate user with Programmatic access?
One more thing, where i need to update this? LOG_LEVEL=debug S3_DEBUG=true in config.yml ?

**Comment by Slach** [comment]
> One more thing, where i need to update this? LOG_LEVEL=debug S3_DEBUG=true in config.yml ?

please look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/ReadMe.md#default-config

LOG_LEVEL=debug
mean
```yaml
general:
  log_level: debug
```

S3_DEBUG=true
mean
```yaml
s3:
  debug: true  
```

**Comment by Slach** [comment]
>  Do i need to create a separate user with Programmatic access?

could you share full your current config.yml wihtout credentials? not only `s3` section?

**Comment by reddivarikishore** [comment]
Please find the below config.yml

`general:
  remote_storage: s3
  max_file_size: 107374182400
  disable_progress_bar: true
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: debug
  allow_empty_backups: false
  download_concurrency: 1
  upload_concurrency: 1
clickhouse:
  username: default
  password: ""
  host: localhost
  port: 9000
  disk_mapping: {}
  skip_tables:
    - INFORMATION_SCHEMA.*
    - information_schema.*
    - system.* 
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: false
  log_sql_queries: false
  config_dir: /etc/clickhouse-server/
  restart_command: systemctl restart clickhouse-server
  debug: false
s3:
  access_key: "ABCD"
  secret_key: "EFGH"
  bucket: "s3-test"
  endpoint: ""
  region: us-east-1
  acl: private
  assume_role_arn: "arn:aws:s3:::s3-test"
  force_path_style: false
  path: ""
  disable_ssl: false
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 0
  debug: true
 
gcs:
  credentials_file: ""
  credentials_json: ""
  bucket: ""
  path: ""
  compression_level: 1
  compression_format: tar
  debug: false
  endpoint: ""
cos:
  url: ""
  timeout: 2m
  secret_id: ""
  secret_key: ""
  path: ""
  compression_format: tar
  compression_level: 1
api:
  listen: localhost:7171
  enable_metrics: true
  enable_pprof: false
  username: ""
  password: ""
  secure: false
  certificate_file: ""
  private_key_file: ""
  create_integration_tables: false
ftp:
  address: ""
  timeout: 2m
  username: ""
  password: ""
  tls: false
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
  debug: false
sftp:
  address: ""
  port: 22
  username: ""
  password: ""
  key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
azblob:
  endpoint_suffix: core.windows.net
  account_name: ""
  account_key: ""
  sas: ""
  use_managed_identity: false
  container: ""
  path: ""
  compression_level: 1
  compression_format: tar
  sse_key: ""
`

**Comment by kishorer00** [comment]
Hi Slach,

Please find the below config.yml file ,
```yaml
general:
  remote_storage: s3
  max_file_size: 107374182400
  disable_progress_bar: true
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: debug
  allow_empty_backups: false
  download_concurrency: 1
  upload_concurrency: 1
clickhouse:
  username: default
  password: ""
  host: localhost
  port: 9000
  disk_mapping: {}
  skip_tables:
    - INFORMATION_SCHEMA.*
    - information_schema.*
    - system.* 
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: false
  log_sql_queries: false
  config_dir: /etc/clickhouse-server/
  restart_command: systemctl restart clickhouse-server
  debug: false
s3:
  access_key: "ABCD"
  secret_key: "EFGH"
  bucket: "s3-test"
  endpoint: ""
  region: us-east-1
  acl: private
  assume_role_arn: "arn:aws:s3:::s3-test"
  force_path_style: false
  path: ""
  disable_ssl: false
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 0
  debug: true
 
gcs:
  credentials_file: ""
  credentials_json: ""
  bucket: ""
  path: ""
  compression_level: 1
  compression_format: tar
  debug: false
  endpoint: ""
cos:
  url: ""
  timeout: 2m
  secret_id: ""
  secret_key: ""
  path: ""
  compression_format: tar
  compression_level: 1
api:
  listen: localhost:7171
  enable_metrics: true
  enable_pprof: false
  username: ""
  password: ""
  secure: false
  certificate_file: ""
  private_key_file: ""
  create_integration_tables: false
ftp:
  address: ""
  timeout: 2m
  username: ""
  password: ""
  tls: false
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
  debug: false
sftp:
  address: ""
  port: 22
  username: ""
  password: ""
  key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
azblob:
  endpoint_suffix: core.windows.net
  account_name: ""
  account_key: ""
  sas: ""
  use_managed_identity: false
  container: ""
  path: ""
  compression_level: 1
  compression_format: tar
  sse_key: ""
```
