### ISSUE TITLE
external tool for upload / download (gsutil for GCP), remote_storage: cli

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#381]
Need tests kopia, restic, rsync

```yaml
general:
  remote_storage: cli
cli:
  upload_command: ...
  donwload_command: ...  
```
