### ISSUE TITLE
Implements storage type independent retry policy

### ISSUE THREAD

**Issue by mmohan2399** [Altinity/clickhouse-backup#397]
we are doing clickhouse backup for 4 sharding which we are  uploading backup to google cloud. One of the shard is struck due to below error . The data we are uploading almost 100 GB per shard.

2022/02/18 14:01:41.010787 error CompressedStreamUpload return error: Post "https://storage.googleapis.com/upload/storage/v1/b/clickhouse_backup/2Fchi-spdb-clickhouse-spdb-clickhouse-1-0-full-2022-02-18-14-00-03%2Fshadow%2Frecipe%2Frecipe_event_pv%2Fdefault_20181202_2903_2954_1.tar&prettyPrint=false&projection=full&uploadType=resumable&upload_id=ADPycdt-GrUeYdMFLV3LopZ2Aj1ls_TTNl2nPOI2oz9D1da11fPcutb8B1A25k8VPZW0aXgZLBjdoMmdDX7psyzsdNxTYE3e1g": http2: client connection force closed via ClientConn.Close
2022/02/18 14:01:41.010990 error can't acquire semaphore during Upload: context canceled

{"name":"","created":"0001-01-01 00:00:00","location":"remote","required":"","desc":"broken (can't stat metadata.json)"}

GCP Config 
```yaml
env:
                 - name: LOG_LEVEL
                   value: "debug"
                 - name: ALLOW_EMPTY_BACKUPS
                   value: "true"
                 - name: API_LISTEN
                   value: "0.0.0.0:7171"
                 - name: API_CREATE_INTEGRATION_TABLES
                   value: "true"
                 - name: REMOTE_STORAGE
                   value: "gcs"
                 - name: GCS_BUCKET
                   value: clickhouse_backup
                 - name: GCS_PATH
                   value: backups
                 - name: GCS_CREDENTIALS_FILE
                   value: /etc/gcscloud.json/
```

/tmp/.clickhouse-backup-metadata.cache.GCS 

```json
"chi-spdb-clickhouse-spdb-clickhouse-1-0-full-2022-02-18-14-00-03": {                       
                "backup_name": "chi-spdb-clickhouse-spdb-clickhouse-1-0-full-2022-02-18-14-00-03",  
                "disks": null,                                                                      
                "version": "",                                                                      
                "creation_date": "0001-01-01T00:00:00Z",                                            
                "metadata_size": 0,                                                                 
                "tables": null,                                                                     
                "data_format": "",                                                                  
                "Legacy": false,                                                                    
                "FileExtension": "",                                                                
                "Broken": "broken (can't stat metadata.json)",                                      
                "UploadDate": "0001-01-01T00:00:00Z"                                                
        },
```
