### ISSUE TITLE
How to use the tool when CH cluster is run in docker

### ISSUE THREAD

**Issue by nrukavkov** [Altinity/clickhouse-backup#421]
Hello. Thank you for your solution. But how to use the tool when CH cluster is run in docker? Do I need to install tool inside every docker instance in cluster? Or I can somehow to use it on the host?

**Comment by Slach** [comment]
if you run clickhouse inside docker
you also should need to run clickhouse-backup in docker
clickhouse-backup provide docker images
clickhouse-backup require access to the same volumes as clickhouse-server container
docker-compose.yaml should look like that:

```yaml
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - /var/lib/clickhouse
  clickhouse-backup:
    image: altinity/clickhouse-backup:latest
    environment:
      API_CREATE_INTEGRATION_TABLES: "true"
    command: 
      - clickhouse-backup
      - server  
    volumes_from: 
      - clickhouse-backup
```
