### ISSUE TITLE
Hash instead password in config clikhouse-backup

### ISSUE THREAD

**Issue by lavasser** [Altinity/clickhouse-backup#433]
Hello!
It would be nice to add hash instead password in config clickhouse-backup.yml
It will be more secure.

For example:

```yml
clickhouse:
  username: default                                                                                      # CLICKHOUSE_USERNAME
  password_sha256_hash: "080fe732956685df3c63a4483004dd7cf512e8502570d4264712b9d3afda1422"                     # CLICKHOUSE_HASH
```
