### ISSUE TITLE
restore_remote not working properly after doing create_remote

### ISSUE THREAD

**Issue by arikodelabs** [Altinity/clickhouse-backup#460]
I get one of the following error when i do clickhouse-backup restore_remote shardreplikimi07
2022/06/24 14:35:19.664141 error can't create table `bms_qa_qaclient`.`connector_time_series_last_values_view`: code: 70, message: Conversion from AggregateFunction(argMax, Nullable(String), DateTime) to AggregateFunction(argMax, String, DateTime) is not supported: while converting source column s to destination column s after 5986 times, please check your schema dependencies

And the tables are not filled with data

We have around 500gb database hence why we have it difficult to replicate the exact time when this issue happens.
Please let me know what logs you need and we will provide.

Here is the config of /etc/clickhouse-backup/config.yml:
```yaml
general:
  remote_storage: gcs
  max_file_size: 1099511627776
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
clickhouse:
  username:
  password:
  host: 172.16.33.41 #localhost
  port: 9000
  disk_mapping: {}
  skip_tables:
    - system.*
  timeout: 30m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
gcs:
  credentials_file: "/etc/google/gcs.json"
  credentials_json: ""
  bucket: "clickhouse-1-backup"
  path: "clickhouse-dev-1-backup"
  compression_level: 1
  compression_format: tar
```
