### ISSUE TITLE
Code: 1000. DB::Exception: Received from chi-datalake-ck-cluster-0-0:9000. DB::Exception: Timeout. (POCO_EXCEPTION)

### ISSUE THREAD

**Issue by kingboung** [Altinity/clickhouse-backup#482]
Error info:
Received exception from server (version 22.2.3):
Code: 1000. DB::Exception: Received from chi-datalake-ck-cluster-0-0:9000. DB::Exception: Timeout. (POCO_EXCEPTION)
(query: SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '20220722-%-shard_0-business-asset_log_local' ORDER BY created DESC LIMIT 1)

Received exception from server (version 22.2.3):
Code: 1000. DB::Exception: Received from chi-datalake-ck-cluster-0-0:9000. DB::Exception: Timeout. (POCO_EXCEPTION)
(query: INSERT INTO system.backup_actions(command) VALUES('delete remote 20220627-20220714-shard_1-business-asset_log_local'))
Error on processing query: Code: 75. DB::ErrnoException: Cannot write to file (fd = 1), errno: 32, strerror: Broken pipe. (CANNOT_WRITE_TO_FILE_DESCRIPTOR) (version 22.1.3.7 (official build))
(query: SELECT name, location FROM system.backup_list)

Question:
Query system.backup_list always takes a long time and sometimes timeout. And I cant delete my history backup at the same time.
There are only 2k rows data in system.backup_list

**Comment by Slach** [comment]
Are you sure  `clickhouse-backup server` still running?

Could you share results for the following query?
```sql
SHOW CREATE TABLE system.backup_list;
SELECT * FROM system.backup_actions;
```

could you also share
```bash
clickhouse-backup version
clickhouse-backup print-config
```

**Comment by kingboung** [comment]
> Are you sure `clickhouse-backup server` still running?

Yes, pretty sure.

> Could you share results for the following query?
> ```sql
> SHOW CREATE TABLE system.backup_list;
> SELECT * FROM system.backup_actions;
> ```
![image](https://user-images.githubusercontent.com/22000541/182055645-d0f72f91-985c-4bc1-98b1-dbacbef7a476.png)
![image](https://user-images.githubusercontent.com/22000541/182055776-05024130-7acf-4bbe-8bec-aad3ddd0dbf4.png)

> could you also share
> ```shell
> clickhouse-backup version
> clickhouse-backup print-config
> ```
bash-5.1$ clickhouse-backup --version
Version:         1.4.3
Git Commit:      5f267bd8a2d409951e30203337270e5b187d0f17
Build Date:      2022-06-20

```YAML
general:
  remote_storage: s3
  max_file_size: 0
  disable_progress_bar: true
  backups_to_keep_local: 1
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
  download_concurrency: 30
  upload_concurrency: 30
  restore_schema_on_cluster: cluster
  upload_by_part: true
  download_by_part: true
clickhouse:
  username: ****
  password: ********
  host: localhost
  port: 9000
  disk_mapping: {}
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  - default.*
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: false
  log_sql_queries: true
  config_dir: /etc/clickhouse-server/
  restart_command: systemctl restart clickhouse-server
  ignore_not_exists_error_during_freeze: true
  tls_key: ""
  tls_cert: ""
  tls_ca: ""
  debug: false
s3:
  access_key: ******
  secret_key: ******
  bucket: ******
  endpoint: ******
  region: ******
  acl: private
  assume_role_arn: ""
  force_path_style: true
  path: ""
  disable_ssl: true
  compression_level: 6
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 10485760
  max_parts_count: 10000
  allow_multipart_download: false
  debug: false
gcs:
  credentials_file: ""
  credentials_json: ""
  bucket: ""
  path: ""
  compression_level: 1
  compression_format: tar
  debug: false
  endpoint: ""
cos:
  url: ""
  timeout: 2m
  secret_id: ""
  secret_key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  debug: false
api:
  listen: 0.0.0.0:7171
  enable_metrics: true
  enable_pprof: false
  username: ""
  password: ""
  secure: false
  certificate_file: ""
  private_key_file: ""
  create_integration_tables: true
  integration_tables_host: ""
  allow_parallel: true
ftp:
  address: ""
  timeout: 2m
  username: ""
  password: ""
  tls: false
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 28
  debug: false
sftp:
  address: ""
  port: 22
  username: ""
  password: ""
  key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
  debug: false
azblob:
  endpoint_suffix: core.windows.net
  account_name: ""
  account_key: ""
  sas: ""
  use_managed_identity: false
  container: ""
  path: ""
  compression_level: 1
  compression_format: tar
  sse_key: ""
  buffer_size: 0
  buffer_count: 3
  max_parts_count: 10000
```


Anything useful? @Slach
