### ISSUE TITLE
Document using Kubernetes (EKS) service accounts for AWS credentials

### ISSUE THREAD

**Issue by r13i** [Altinity/clickhouse-backup#563]
From the source code [1], it seems possible to acquire credentials from a service account on EKS, which sets the environment variables `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE`.

I am basing my setup on the example [How to use clickhouse-backup in Kubernetes
](https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes).

After updating my ClickHouse installation with the reference to the service account name, all the operations work fine.

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  templates:
    podTemplates:
      - name: <NAME>
        spec:
          containers:
            - name: clickhouse-backup
            ...
          serviceAccountName: <SERVICE ACCOUNT NAME>
```

Is it possible to update the documentation to mention this option, which I think would be valuable for everyone using EKS?

[1]: https://github.com/AlexAkulov/clickhouse-backup/blob/master/pkg/storage/s3.go#L81-L90
