### ISSUE TITLE
Backup specific partition(s)

### ISSUE THREAD

**Issue by rkozlo** [Altinity/clickhouse-backup#579]
Hi,
looking if i could use clickhouse-backup to backup n months or by specific partitions to backup. Have a huge table and want to only backup some latest data not whole. Don't see this in "help" nor other issues. So maybe is there any hidden option or maybe have in plan to implement such feature?

**Comment by Slach** [comment]
look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/ReadMe.md#default-config and https://clickhouse.com/docs/en/operations/system-tables/parts/

```yaml
clickhouse:
  # CLICKHOUSE_FREEZE_BY_PART, allows freeze part by part instead of freeze the whole table
  freeze_by_part: true       
  # CLICKHOUSE_FREEZE_BY_PART_WHERE, allows parts filtering during freeze when freeze_by_part: true
  freeze_by_part_where: "name LIKE concat(toString(toYYYYMM(now())),'%') AND active=1" 
```
