### ISSUE TITLE
Having issues with download from S3

### ISSUE THREAD

**Issue by nikolasct** [Altinity/clickhouse-backup#580]
Hello, I am having issues downloading a backup from S3.
Here is the list of backups:
clickhouse_full_backup_2022-12-03T05-00-02           14.90TiB    03/12/2022 13:25:22   remote                                                 tar, regular
clickhouse_differencial_backup_2022-12-07T05-00-01   158.99GiB   07/12/2022 05:12:04   remote   +clickhouse_full_backup_2022-12-03T05-00-02   tar, regular

I am trying to download differencial backup using the
`clickhouse-backup download clickhouse_differencial_backup_2022-12-07T05-00-01`

Running the `clickhouse-backup download --help` gives me this:
USAGE:
   clickhouse-backup download <backup_name>

The download option is straightforward.

The problem is this takes way too long, so I decided to break to command and run `clickhouse-backup list`.
It gives me clickhouse_full local and clickhouse_differencial local. Ok, I understand that the clickhouse_differencial will be downloaded, but I don't understand why does the clickhouse_full backup starts downloading, even though I specified the backup name?
Note that there are no backups with the same name on S3 or anywhere else on our infrastructure.
So I am guessing this takes way too long because our full backup is ~15TB, but again the question above remains.

Can you help?

**Comment by Slach** [comment]
could you share
`clickhouse-backup print-config`
without sensitive credentials?

**Comment by Slach** [comment]
> but I don't understand why does the clickhouse_full backup starts downloading,

Because incremental backup requires data from full backup for restoring process
only required parts will download from full backup, if you have `download_by_part: true` and `upload_by_part: true` in your `print-config` section.

**Comment by Slach** [comment]
If you want to restore only several tables, you can use `clickhouse-backup download --tables=pattern <backup_name>`

**Comment by Slach** [comment]
try to increase  `download_concurrency` if you have enough of RAM

**Comment by nikolasct** [comment]
Note, we are using AWS assume role, since clickhouse is on our EC2 instance. Uploading the backup works.

Here is the config file:
````yaml
general:
  backups_to_keep_remote: 3
  backups_to_keep_local: 3
  disable_progress_bar: true
  remote_storage: s3
  upload_concurrency: 6
  download_concurrency: 6
  skip_tables:
    - "system.*"
    - "INFORMATION_SCHEMA.*"
    - "information_schema.*"
    - "default.*"
  restore_schema_on_cluster: "main_cluster"
  log_level: debug
  upload_by_part: true
  download_by_part: true
clickhouse:
  host: 
  port: 9000
  username:
  password:
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  timeout: 1s
  restart_command: bash -c 'echo "FAKE RESTART"'
  debug: true
s3:
  bucket: st-clickhouse-backup
  endpoint: ""
  region: us-east-1
  acl: private
  force_path_style: true
  path: backup/clickhouse/{shard}
  disable_ssl: true 
  compression_format: tar
  allow_multipart_download: true 
  debug: true
```
  
  I added the `download_by_part: true` option

> only required parts will download from full backup, if you have download_by_part: true and upload_by_part: true in your print-config section.

So does this mean if I have the download_by_part and upload_by_part set to true I can download the differencial backup without the local full backup, and I can restore from just that differencial?

> try to increase download_concurrency if you have enough of RAM

I did increase the download_concurrency. I got 128GB of RAM, how much can I increase the download and upload concurrency to?

Thanks for answering!!

**Comment by Slach** [comment]
Some config comments

```yaml
general:
  backups_to_keep_local: 1 # enought 1 here, cause  many local backups will allocate disk space
  remote_storage: s3
  upload_concurrency: 6 # 36 upload streams  6 tables, 6 parts in each table
  download_concurrency: 6 # 36 download streams  6 tables, 6 parts in each table
  upload_by_part: true # if you set this option before upload backup (true is default) then 
  download_by_part: true
s3:
  bucket: st-clickhouse-backup
  disable_ssl: true # strange value for AWS S3
  compression_format: tar
  allow_multipart_download: true # setup it false, it require additional disk space and could download slowly in some corner case
  concurrency: 3  # S3 SDK concurrency inside upload / download stream for S3 multipart upload / download
```
