### ISSUE TITLE
Error 404: NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by yayaythegreat** [Altinity/clickhouse-backup#590]
Hello All,

I am encountering an Error 404 when trying to execute `curl -s localhost:7171/backup/list/remote` on my s3 bucket.

Here is the log I am getting.

The request
```
2023/01/09 15:22:27.204631  info DEBUG: Request s3/ListObjectsV2 Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /<bucket_name>?delimiter=%2F&list-type=2&max-keys=1000&prefix=backup%2F HTTP/1.1
Host: <bucket_name>.s3.us-east-1.amazonaws.com
```
And here is the response

```
2023/01/09 15:22:27.263258  info DEBUG: Response s3/ListObjectsV2 Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Mon, 09 Jan 2023 15:22:26 GMT
Server: AmazonS3
-----------------------------------------------------
2023/01/09 15:22:27.263313  warn BackupList bd.Walk return error: NoSuchKey: The specified key does not exist.
	status code: 404, request id: <req_id>, host id: <req_id> logger=s3
```

I also made sure that the **backup** directory is not empty
<img width="1197" alt="Screenshot 2023-01-10 at 12 18 47 AM" src="https://user-images.githubusercontent.com/52384198/211355989-3b6f6b23-b349-4f2e-ad0e-a39c4ba9ade9.png">

clickhouse-server and clickhouse-backup shares the same Pod.
Here is my config
```
env:
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "5"
                # change it for production S3
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_ACL
                  value: "private"
                - name: S3_ENDPOINT
                  value: https://bucket_name.s3.us-east-1.amazonaws.com
                - name: S3_BUCKET
                  value: bucket_name
                - name: S3_PATH
                  value: backup
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                - name: S3_DEBUG
                  value: "true"
```

Thanks in advance for the recommendations and suggestions
