### ISSUE TITLE
Large amounts of data are uploaded remotely through ftp

### ISSUE THREAD

**Issue by baobaopao** [Altinity/clickhouse-backup#601]
Now I need to upload 40T of data to the ftp server through 'clickhouse-backup create-remote', but it will take a long time. Is there any good solution? Or is there a way to back up and upload data from all non-partitioned tables and data from a partition of all partitioned tables at once?
thank you

**Comment by Slach** [comment]
upload speed depends on concurrency and bandwidth your remote ftp server
check the following options in your `/etc/clickhouse-backup/config.yml`

```yaml
general:
  # will upload 10 tables in parallel and 10 parts in parallel for each table - requite support 100-200 connections support for your ftp server
  upload_concurrency: 10 
```
