### ISSUE TITLE
content-type has changed to text/plain from application/json

### ISSUE THREAD

**Issue by yogeshghotekar** [Altinity/clickhouse-backup#605]
We are upgrade the version to version 2.1.3 from 1.5.2 which result in start failing our ansible-playbook task because the content type of API response changed to text/plain from application/json.

We are using ansible-playbook which does the backup job and which is dependent on the application/json type response from clickhouse-backup API.

one of the example of an ansible-playbook task:

```
- name: Wait for backup to complete
  uri:
    url: "http://{{ service_prefix }}-{{ item }}-0-0.{{ service_prefix }}-{{ item }}-0.{{ ns.stdout }}.svc.cluster.local:7171/backup/status"
    return_content: yes
  with_sequence: "start=0 count={{ shards |int }}"
  register: status
  until: "status.json.status == 'success' or status.json.status == 'error'"
  retries: 360
  delay: 10
```

See the api response in different version.
**version 1.5.2**
```
bash-5.1$ curl -k -v -X POST http://localhost:7171/backup/create?name=test
*   Trying 127.0.0.1:7171...
* Connected to localhost (127.0.0.1) port 7171 (#0)
> POST /backup/create?name=test HTTP/1.1
> Host: localhost:7171
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache, must-revalidate
< Content-Type: application/json; charset=UTF-8
< Pragma: no-cache
< Date: Wed, 01 Feb 2023 03:52:21 GMT
< Content-Length: 68
< 
{"status":"acknowledged","operation":"create","backup_name":"test"}
* Connection #0 to host localhost left intact
bash-5.1$ clickhouse-backup --version
Version:         1.5.2
Git Commit:      f67d23fd3b775f887683d3d3fdea1b1500419987
Build Date:      2022-08-08
bash-5.1$ 
```

**version 2.1.3**

``` 
bash-5.1$ curl -k -v -X POST http://localhost:7171/backup/create?name=test
*   Trying 127.0.0.1:7171...
* Connected to localhost (127.0.0.1) port 7171 (#0)
> POST /backup/create?name=test HTTP/1.1
> Host: localhost:7171
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Date: Wed, 01 Feb 2023 03:55:49 GMT
< Content-Length: 68
< Content-Type: text/plain; charset=utf-8
< 
{"status":"acknowledged","operation":"create","backup_name":"test"}
* Connection #0 to host localhost left intact
bash-5.1$ clickhouse-backup --version
Version:         2.1.3
Git Commit:      f3e6a5667371bfa122e5a907b68e5004b40251f7
Build Date:      2022-12-26
bash-5.1$ ```
