### ISSUE TITLE
Dockerized Clickhouse, volumes and data_path

### ISSUE THREAD

**Issue by xTRiM** [Altinity/clickhouse-backup#607]
Our CH runs in Docker and we map volumes like this:
`/data/clickhouse:/var/lib/clickhouse`

Now clickhouse-backup gets data path via:
`SELECT * FROM system.disks; logger=clickhouse`
and it says `/var/lib/clickhouse`
But actual path on the docker host is `/data/clickhouse`

In some older versions of clickhouse-backup we were able to define `clickhouse->data_path` setting in clickhouse-backup.config.yml. 
What is the proper way to do that now? If any.

**Comment by Slach** [comment]
Try to use 

```yaml
clickhouse:
  disk_mapping::
    disk_name: /disk/path
    disk_name2: /disk/path
```
