### ISSUE TITLE
Incremental backup creating diff backups from wrong shards

### ISSUE THREAD

**Issue by nikola358** [Altinity/clickhouse-backup#630]
I’m having an issue with incremental backups with clickhouse in kubernetes. The incremental backups calculate diff from a wrong base backup shard. I’m using the backup cronjob `clickhouse-backup-cron` from https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes with the following environment vars:
```
              env:
                # use first replica in each shard, use `kubectl get svc | grep test-backups`
                - name: CLICKHOUSE_SERVICES
                  value: chi-ch01-prod01-0-1,chi-ch01-prod01-1-1,chi-ch01-prod01-2-1
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: BACKUP_USER
                  value: "omitted"
                - name: BACKUP_PASSWORD
                  value: "omitted"
                # change to 1, if you want to make full backup only in $FULL_BACKUP_WEEKDAY (1 - Mon, 7 - Sun)   
                - name: MAKE_INCREMENT_BACKUP
                  value: "1"
                - name: FULL_BACKUP_WEEKDAY
                  value: "1"
```
When I do `clickhouse-backup list` it returns
```
chi-ch01-prod01-2-1-full-2023-04-03-02-00-01             659.49GiB   03/04/2023 03:31:18   remote                                                             tar, regular
chi-ch01-prod01-1-1-full-2023-04-03-02-00-01             660.84GiB   03/04/2023 03:31:56   remote                                                             tar, regular
chi-ch01-prod01-0-1-full-2023-04-03-02-00-01             660.16GiB   03/04/2023 03:32:12   remote                                                             tar, regular
chi-ch01-prod01-1-1-increment-2023-04-04-02-00-14        20.46GiB    04/04/2023 02:03:32   remote   +chi-ch01-prod01-1-1-full-2023-04-03-02-00-01             tar, regular
chi-ch01-prod01-0-1-increment-2023-04-04-02-00-14        551.25GiB   04/04/2023 03:19:30   remote   +chi-ch01-prod01-1-1-full-2023-04-03-02-00-01             tar, regular
chi-ch01-prod01-2-1-increment-2023-04-04-02-00-14        590.72GiB   04/04/2023 03:23:03   remote   +chi-ch01-prod01-1-1-full-2023-04-03-02-00-01             tar, regular
```
The incremental backups from all shards on 4th of April are all from shard 1, rather than their own shard. The incremental backup size for shard 1 is ~20GB which is correct, but for shards 0 and 2 its 500+ GBs because they are doing a diff from shard 1. What might be the cause of this?
