### ISSUE TITLE
clickhouse-backup only stores metadatas for databases and backups

### ISSUE THREAD

**Issue by devi12311** [Altinity/clickhouse-backup#667]
Hi, i was trying to implement clickhouse-backup as a solution to manage my sharded cluster backups into amazon s3. 
My Clickhouse cluster is running in kubernetes and i used the example provided in the [documentation](https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md).
Everything was configured fine as instructed in the example. 

After i triggered the cron job defined in the example for my specific usecase, i checked the bucket and only the metadata were uploaded.

The backup folder contained metadata for the cluster in general, and inside it had the metadata for the databases and tables. That is totally okay, but it didn't backup the data inside the tables in order to restore them later.
1- clickhouse-backup version is the latest master (altinity/clickhouse-backup:master)
2- clickhouse/clickhouse-server:22.8.5
3- Configurations of the clickhouse-backup sidecar 
```yaml
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: CLICKHOUSE_USERNAME
                  value: "backup"
                - name: CLICKHOUSE_PASSWORD
                  value: "Backup_pass"
                - name: CLICKHOUSE_HOST
                  value: "host"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "3"
                # change it for production S3
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_ACL
                  value: "private"
                - name: S3_ENDPOINT
                  value: url
                - name: S3_BUCKET
                  value: backup
                - name: S3_PATH
                  value: backup/shard-{shard}
                - name: S3_ACCESS_KEY
                  value: access_key
                - name: S3_REGION
                  value: region
                - name: S3_SECRET_KEY
                  value: secret
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                - name: S3_DISABLE_SSL
                  value: "true"
                - name: S3_DEBUG
                  value: "true"
```                
Scripts for backup and restore are identical to the example provided in the repo. Thanks in advance

**Comment by Slach** [comment]
Did you use https://github.com/Altinity/clickhouse-operator to deploy your clickhouse server in Kubernetes?

**Comment by Slach** [comment]
could you share 
`kubectl get chi --all-namespaces` ?

**Comment by mglotov** [comment]
@devi12311 The example isn't full. Try to add this into the `clickhouse-backup` container spec:
```
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: server-storage
```
Where `server-storage` is a volume name using to store clickhouse data (the same name as you set in a `volumeClaimTemplates`)

**Comment by Slach** [comment]
@mglotov thanks, i will fix example ASAP

**Comment by devi12311** [comment]
Hello, guys and thanks for the quick response, i managed to fix it and did exactly what @mglotov said beforehand. It looked like the mount folder i declared for the clickhouse-server container wasn't the same as clickhouse-backup(because since i did not declare the "volumeMounts" on both they got confused). The ideal solution was to declare it on both containers but also not specifying it at all and let the pvc template take care of that was reasonable. 

That was very helpful, thank you once again!

**Comment by Slach** [comment]
@mglotov @devi12311 
Examples.md contains
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
spec:
   defaults:
      templates:
         podTemplate: clickhouse-backup
         dataVolumeClaimTemplate: data-volume
...
   templates:
      volumeClaimTemplates:
         - name: data-volume
           spec:
              accessModes:
                 - ReadWriteOnce
              resources:
                 requests:
                    storage: 10Gi

```

so, it means every pod in statefulset with podTemplate: clickhouse-backup
will have 
```yaml
 volumeMounts:
    - mountPath: /var/lib/clickhouse
      name: data-volume
```

someone just not copied dataVolumeClaimTemplate from original manifests
