### ISSUE TITLE
hotfix created empty .tar.gz  in 2.2.7+

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#676]
system.disks
default, disk2

```yaml
disk_mapping:
   "default": "/var/lib/clickhouse/"
   "default-1-1": "/var/lib/clickhouse"
   "disk2": "/var/lib/clickhouse2/"
   "disk2-1-1": "/var/lib/clickhouse2"
```

wrong empty .tar.gz is created, which can't be restored
