### ISSUE TITLE
issue for restore for 3shard 2 replicas

### ISSUE THREAD

**Issue by MeehanCole** [Altinity/clickhouse-backup#681]
Hello sir 

clickhouse is 3shards 2replicas
```
root@k8s-master1 ~]# kubectl get pod -n imp-public 
NAME                                 READY   STATUS    RESTARTS      AGE
imp-clickhouse-shard0-0              2/2     Running   0             2d5h
imp-clickhouse-shard0-1              2/2     Running   0             2d5h
imp-clickhouse-shard1-0              2/2     Running   0             2d5h
imp-clickhouse-shard1-1              2/2     Running   0             2d5h
imp-clickhouse-shard2-0              2/2     Running   0             2d5h
imp-clickhouse-shard2-1              2/2     Running   0             2d5h
```

to restore the data in the imp-clickhouse-shard0-0,  i will delete all the remain  shard's table and recreate it.  the other shard data is lost.

```
imp-clickhouse-shard1-0:/# clickhouse-backup restore_remote --config  /etc/clickhouse-backup/clickhouse-backup.yml imp-clickhouse-shard1-0-2023-06-28T09:00:00
```

the s1-0 restore data success
![image](https://github.com/Altinity/clickhouse-backup/assets/40968187/46dbcefe-af46-4581-ba68-bc1d3ec743f4)

the s0-0 table also recreate , the data is lost 
![image](https://github.com/Altinity/clickhouse-backup/assets/40968187/6a09fc40-7484-4fae-a881-87cc24bb4e3c)

the configuration as below :
```yaml
general:
  disable_progress_bar: true
  remote_storage: sftp
  upload_by_part: true
  download_by_part: true
  use_resumable_state: false
  upload_concurrency: 1
  download_concurrency: 1
  restore_schema_on_cluster: "default"
  backups_to_keep_local: 2
  retries_on_failure: 3
  retries_pause: 30s
  allow_empty_backups: false
clickhouse:
  host: 127.0.0.1
  port: 9000
  username: default
  password: clickhouse
  secure: false
  skip_verify: true
  timeout: 5m 
  skip_tables:                     
    - system.*
    - INFORMATION_SCHEMA.*
    - information_schema.*
  restart_command: bash -c 'echo "systemctl restart clickhouse-server"'
sftp:
  address: "10.64.8.42"
  username: "root"
  password: "XXX"
  key: ""
  path: "/opt/imp-local-path-provisioner/ckBackUp"
  compression_format: gzip
  compression_level: 1
api:
  listen: "0.0.0.0:7171"
```

any problem for it  ?
