### ISSUE TITLE
BACKUPS_TO_KEEP_REMOTE keeping backups longer than configured

### ISSUE THREAD

**Issue by nikola358** [Altinity/clickhouse-backup#682]
I have a 4 shard ch cluster running in kubernetes using the clickhouse operator. I use the provided clickhouse-backup-cron from https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md to create the backup job.

I wanted to setup incremental backups and to keep backups for 14 days. My current setup is keeping backups for a longer period than I set it to BACKUPS_TO_KEEP_REMOTE. Did I misconfigure the settings?

clickhouse-backup list on a shard has 18 backups, dating from June 11th - this should have been deleted
```
chi-ch02-prod01-3-1-full-2023-06-11-22-00-00        107.03GiB   11/06/2023 22:17:12   remote                                                        tar, regular
chi-ch02-prod01-3-1-increment-2023-06-12-22-00-11   5.05GiB     12/06/2023 22:03:15   remote   +chi-ch02-prod01-3-1-full-2023-06-11-22-00-00        tar, regular
chi-ch02-prod01-3-1-increment-2023-06-13-22-00-09   43.93GiB    13/06/2023 22:08:41   remote   +chi-ch02-prod01-3-1-increment-2023-06-12-22-00-11   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-14-22-00-01   25.18GiB    14/06/2023 22:05:51   remote   +chi-ch02-prod01-3-1-increment-2023-06-13-22-00-09   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-15-22-00-01   14.36GiB    15/06/2023 22:04:22   remote   +chi-ch02-prod01-3-1-increment-2023-06-14-22-00-01   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-16-22-00-14   14.00GiB    16/06/2023 22:04:22   remote   +chi-ch02-prod01-3-1-increment-2023-06-15-22-00-01   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-17-22-00-01   17.29GiB    17/06/2023 22:04:23   remote   +chi-ch02-prod01-3-1-increment-2023-06-16-22-00-14   tar, regular
chi-ch02-prod01-3-1-full-2023-06-18-22-00-01        81.83GiB    18/06/2023 22:13:31   remote                                                        tar, regular
chi-ch02-prod01-3-1-increment-2023-06-19-22-00-11   17.78GiB    19/06/2023 22:05:11   remote   +chi-ch02-prod01-3-1-full-2023-06-18-22-00-01        tar, regular
chi-ch02-prod01-3-1-increment-2023-06-20-22-00-00   19.79GiB    20/06/2023 22:04:26   remote   +chi-ch02-prod01-3-1-increment-2023-06-19-22-00-11   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-21-22-00-10   12.89GiB    21/06/2023 22:03:50   remote   +chi-ch02-prod01-3-1-increment-2023-06-20-22-00-00   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-22-22-00-01   15.23GiB    22/06/2023 22:04:14   remote   +chi-ch02-prod01-3-1-increment-2023-06-21-22-00-10   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-23-13-19-56   7.61GiB     23/06/2023 13:23:11   remote   +chi-ch02-prod01-3-1-increment-2023-06-22-22-00-01   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-23-22-00-01   5.90GiB     23/06/2023 22:04:04   remote   +chi-ch02-prod01-3-1-increment-2023-06-23-13-19-56   tar, regular
chi-ch02-prod01-3-1-increment-2023-06-24-22-00-01   13.12GiB    24/06/2023 22:07:41   remote   +chi-ch02-prod01-3-1-increment-2023-06-23-22-00-01   tar, regular
chi-ch02-prod01-3-1-full-2023-06-25-22-00-01        67.14GiB    25/06/2023 22:14:28   remote                                                        tar, regular
chi-ch02-prod01-3-1-increment-2023-06-26-22-00-01   17.52GiB    26/06/2023 22:07:22   remote   +chi-ch02-prod01-3-1-full-2023-06-25-22-00-01        tar, regular
chi-ch02-prod01-3-1-increment-2023-06-27-22-00-19   40.86GiB    27/06/2023 22:07:54   remote   +chi-ch02-prod01-3-1-increment-2023-06-26-22-00-01   tar, regular
```

The clickhouse backup container config is the following:
```
            # Clickhouse backup container
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:2.2.6
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              env:
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: API_ENABLE_METRICS
                  value: "true"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_LOCAL
                  value: "3"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "14"
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_REGION
                  value: eu-central-1
                - name: S3_BUCKET
                  value: omitted
                - name: S3_PATH
                  value: "backup/{shard}"
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                # 100mb part size
                - name: S3_PART_SIZE
                  value: "104857600"
```

Cronjob env vars are the following:
```
                - name: CLICKHOUSE_SERVICES
                  value: chi-ch02-prod01-0-1,chi-ch02-prod01-1-1,chi-ch02-prod01-2-1,chi-ch02-prod01-3-1
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: BACKUP_USER
                  value: "omitted"
                - name: BACKUP_PASSWORD
                  value: "omitted"
                # change to 1, if you want to make full backup only in $FULL_BACKUP_WEEKDAY (1 - Mon, 7 - Sun)   
                - name: MAKE_INCREMENT_BACKUP
                  value: "1"
                - name: FULL_BACKUP_WEEKDAY
                  value: "7"
```
