### ISSUE TITLE
Upload a backup to GCS is stuck, when upload_concurrency: 0

### ISSUE THREAD

**Issue by mglotov** [Altinity/clickhouse-backup#688]
environment: k8s 1.26
clickhouse config:
```
...
    podTemplates:
      - name: clickhouse-22.8-lts
...
        spec:
          serviceAccount: clickhouse-pod
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.8
              volumeMounts:
                - name: server-storage
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "1024Mi"
                  cpu: 100m
                limits:
                  memory: "1280Mi"
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:master
              imagePullPolicy: Always
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              env:
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "14"
                - name: REMOTE_STORAGE
                  value: "gcs"
                - name: GCS_BUCKET
                  value: "BUCKET_NAME"
                - name: GCS_PATH
                  value: backup/shard-{shard}
                - name: CLICKHOUSE_SKIP_TABLES
                  value: "system.*,INFORMATION_SCHEMA.*,default.*" # All tables except these will be backed up 
```
GCP node type: `n1-standard-1`

Upload operation is stuck on:
```
2023/07/10 05:45:46.015224 debug /tmp/.clickhouse-backup-metadata.cache.GCS load 14 elements logger=gcs
2023/07/10 05:45:46.097387 debug /tmp/.clickhouse-backup-metadata.cache.GCS save 14 elements logger=gcs
2023/07/10 05:45:46.100377 debug prepare table concurrent semaphore with concurrency=0 len(tablesForUpload)=7 backup=BACKUP_NAME operation=upload
```

Looks like a bug with a concurrency calculation for an upload operation, because for `download` it's **1**, but for `upload` it's **0**.
clickhouse-backup config:
```
clickhouse-backup print-config|grep concurrency
    download_concurrency: 1
    upload_concurrency: 0
    concurrency: 2
    concurrency: 2
    concurrency: 2
```
