### ISSUE TITLE
run clickhouse-backup restore outside error,clickhouse-server docker container with volume mounts

### ISSUE THREAD

**Issue by stancycowen** [Altinity/clickhouse-backup#690]
clickhouse-backup version :1.6.2
clickhouse version:22.8.13.20
**clicickhouse-backup config.yml**

```yaml
clickhouse:
  username: *
  password: "*"
  host: localhost
  port: 9000
  disk_mapping:
    default: /data/tip-clickhouse-server-1/
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  timeout: 5m
  freeze_by_part: false
  freeze_by_part_where: ""
  secure: false
  skip_verify: false
  sync_replicated_tables: false
  log_sql_queries: true
  config_dir: /etc/tip-clickhouse-server-1/
````

**docker-compose.yml volume** 
```yaml
    volumes:
      - /data/tip-clickhouse-server-1/:/var/lib/clickhouse/
      - /var/log/tip-clickhouse-server-1/:/var/log/clickhouse-server/
      - /etc/tip-clickhouse-server-1/:/etc/clickhouse-server/

```

**restore error**
`error can't restore 'tip_db.t_ti_statistics_upload': error during filepath.Walk for part '202004_4_4_0': failed to create hard link '/data/tip-clickhouse-server-1/backup/tip-clickhouse-node1_2023-07-10T06-36-21/shadow/tip_db/t_ti_statistics_upload/default/202004_4_4_0/checksums.txt' -> '/var/lib/clickhouse/store/615/615c0330-43e5-4b76-b517-9cfc8547b955/detached/202004_4_4_0/checksums.txt': link /data/tip-clickhouse-server-1/backup/tip-clickhouse-node1_2023-07-10T06-36-21/shadow/tip_db/t_ti_statistics_upload/default/202004_4_4_0/checksums.txt /var/lib/clickhouse/store/615/615c0330-43e5-4b76-b517-9cfc8547b955/detached/202004_4_4_0/checksums.txt: invalid cross-device link`

**Comment by Slach** [comment]
`cross-device link` means `/data` folder and `/var/lib/clickhouse` mounted in separate devices

**Comment by Slach** [comment]
try to use clickhouse-backup:2.3.0
and 
for your use case better run `clickhouse-backup` in the same `docker-compose.yaml`

something like that
`docker-compose run --rm clickhouse-backup`
with following docker-compose

and without disk_mappings

```yaml
services:
 clickhouse:
   image: clickhouse/clickhouse-server:22.8
   volumes:
     - /data/tip-clickhouse-server-1/:/var/lib/clickhouse/
     - /var/log/tip-clickhouse-server-1/:/var/log/clickhouse-server/
     - /etc/tip-clickhouse-server-1/:/etc/clickhouse-server/
 clickhouse-backup:
   image: altinity/clickhouse-backup:latest
   command: ['clickhouse-backup','restore','tip-clickhouse-node1_2023-07-10T06-36-21']
   volumes:
     - /etc/tip-clickhouse-backup/:/etc/clickhouse-backup/
   volumes_from:
     - clickhouse 
         
```
