### ISSUE TITLE
Issue while restoring backup

### ISSUE THREAD

**Issue by ekatabavkar** [Altinity/clickhouse-backup#700]
Below sql part of one time restore job Kubernetes example is erroring out :

```
SELECT * FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC  FORMAT TabSeparatedRaw
``` 
[2023-07-20 10:11:50] Code: 86. DB::HTTPException: Received error from remote server /backup/list. HTTP status code: 500 Internal Server Error, body: {"status":"error","operation":"list","error":"googleHTTPTransport.NewClient error: cannot read credentials file: open /var/lib/clickhouse/clickhouse_gcs_creds.json: no such file or directory"}

However, when the same sql is modified without the order by clause, it runs fine.

```
SELECT * FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%'
``` 
What could be the issue here?

**Comment by Slach** [comment]
> cannot read credentials file: open /var/lib/clickhouse/clickhouse_gcs_creds.json: no such file or directory


do you have this file?
if not, provide properly GCS credentials

could you share your
`clickhouse-backup print-config` without sensitive credentials?

**Comment by ekatabavkar** [comment]
yes this file is present. Backup cron job successfully created backups and hence, this table also has some data.

![image](https://github.com/Altinity/clickhouse-backup/assets/94821574/cdfee123-3a8c-4346-9e8c-2ba9c80592d7)




Below is the clickhouse print config output:

```yaml
general:
    remote_storage: gcs
    max_file_size: 0
    disable_progress_bar: true
    backups_to_keep_local: 0
    backups_to_keep_remote: 3
    log_level: debug
    allow_empty_backups: true
    download_concurrency: 15
    upload_concurrency: 15
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    retries_on_failure: 3
    retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    retriesduration: 30s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: default
    password: ""
    host: localhost
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    timeout: 5m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /etc/clickhouse-server/
    restart_command: systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    debug: false
s3:
    access_key: ""
    secret_key: ""
    bucket: ""
    endpoint: ""
    region: us-east-1
    acl: private
    assume_role_arn: ""
    force_path_style: false
    path: ""
    disable_ssl: false
    compression_level: 1
    compression_format: tar
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: false
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 16
    part_size: 0
    max_parts_count: 5000
    allow_multipart_download: false
    object_labels: {}
    debug: false
gcs:
    credentials_file: /var/lib/clickhouse/clickhouse_gcs_creds.json
    credentials_json: ""
    credentials_json_encoded: ""
    bucket: dummy_bucket
    path: backup/shard-{shard}
    compression_level: 1
    compression_format: tar
    debug: true
    endpoint: ""
    storage_class: STANDARD
    object_labels: {}
    custom_storage_class_map: {}
cos:
    url: ""
    timeout: 2m
    secret_id: ""
    secret_key: ""
    path: ""
    compression_format: tar
    compression_level: 1
    debug: false
api:
    listen: 0.0.0.0:7171
    enable_metrics: true
    enable_pprof: false
    username: ""
    password: ""
    secure: false
    certificate_file: ""
    private_key_file: ""
    ca_cert_file: ""
    ca_key_file: ""
    create_integration_tables: true
    integration_tables_host: ""
    allow_parallel: false
    complete_resumable_after_restart: true
ftp:
    address: ""
    timeout: 2m
    username: ""
    password: ""
    tls: false
    path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 16
    debug: false
sftp:
    address: ""
    port: 22
    username: ""
    password: ""
    key: ""
    path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 16
    debug: false
azblob:
    endpoint_schema: https
    endpoint_suffix: core.windows.net
    account_name: ""
    account_key: ""
    sas: ""
    use_managed_identity: false
    container: ""
    path: ""
    compression_level: 1
    compression_format: tar
    sse_key: ""
    buffer_size: 0
    buffer_count: 3
    max_parts_count: 5000
    timeout: 15m
custom:
    upload_command: ""
    download_command: ""
    list_command: ""
    delete_command: ""
    command_timeout: 4h
    commandtimeoutduration: 4h0m0s

```

**Comment by Slach** [comment]
looks weird

```sql
SELECT * FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC  FORMAT TabSeparatedRaw
```
and
```sql
SELECT * FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%'
```

use the same credentials and do the same network requests
ORDER BY applied on `clickhouse-server` side only


how do you run your `clickhouse-backup` and `clickhouse-server`?
The same standalone server?
Docker containers on the same host with shared /var/lib/clickhouse volume?

**Comment by ekatabavkar** [comment]
yes, that's correct.. clickhouse-backup and clickhouse-server run on the same standalone server. Yes these containers share the same volume. The one time restore Kubernetes job pod had the below logs:

```
kubectl logs job.batch/clickhouse-backup-restore -n dev
INSERT INTO system.backup_actions(command) VALUES('restore_remote --schema --rm chi-medium-medium-cluster-0-0-full-2023-07-20-00-00-01')
Received exception from server (version 23.4.6):
Code: 86. DB::Exception: Received from chi-medium-medium-cluster-0-1:9000. DB::HTTPException. DB::HTTPException: Received error from remote server /backup/list. HTTP status code: 500 Internal Server Error, body: {"status":"error","operation":"list","error":"googleHTTPTransport.NewClient error: cannot read credentials file: open /var/lib/clickhouse/clickhouse_gcs_creds.json: no such file or directory"}
: While executing URL. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER)
(query: SELECT name FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw)
```

Hence, I ran the same SQL query directly using jdbc driver and got the same error. However, if I modify the query and remove the order by clause , it gets completed. Hence, I was wondering what could be wrong here?

**Comment by Slach** [comment]
could you share
`kubectl get chi medium -n <your-chi-namespace> -o yaml`?
without sensitive credentials?

**Comment by Slach** [comment]
@ekatabavkar any news?

**Comment by ekatabavkar** [comment]
Here is the output : 
[kubectl get chi medium output.txt](https://github.com/Altinity/clickhouse-backup/files/12208561/kubectl.get.chi.medium.output.txt)

**Comment by Slach** [comment]
In shared YAML
I see

```yaml
          env:
          - name: GCS_CREDENTIALS_FILE
            value: /var/lib/clickhouse/clickhouse_gcs_creds.json
```

but doesn't see any `volumeMounts` inside `clickhouse-backup` container
it means even if you manually put json file to /var/lib/clickhouse
it will not available after any pod restart

you can check it via
`kubectl exec -n dev chi-medium-medium-cluster-0-0-0 -c clickhouse-backup -- bash -xec "ls -la /var/lib/clickhouse/clickhouse_gcs_creds.json`

you need to store your credentials in separate `secret` and mount this value inside clickhouse-backup pod env 

usually it should look like

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: medium
  namespace: dev
spec:
...
  templates:
    podTemplates:
    - name: clickhouse
      spec:
        volumes:
        - name: clickhouse-backup-secret
          secret:
            secretName:
        containers:
        - command:
          - bash
          - -xc
          - /bin/clickhouse-backup server
          name: clickhouse-backup
...
          env:
          - name: GCS_CREDENTIALS_JSON
            valueFrom:
              secretKeyRef:  
                name: backup-gcs-creds
                key: GCS_CREDENTIALS_JSON
...
---
# replace 
apiVersion: v1
kind: Secret
metadata:
  name: backup-gcs-creds
  namespace: dev 
stringData:
  GCS_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "XXX",
      "private_key_id": "XXXX",
      "private_key": "-----BEGIN PRIVATE KEY-----\nXXXXX\n-----END PRIVATE KEY-----\n",
      "client_email": "XXX@XXX.iam.gserviceaccount.com",
      "client_id": "XXX",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/XXX%40XXX.iam.gserviceaccount.com"
    }

```
