### ISSUE TITLE
How does one create a backup that includes data of a clickhouse installation running on another pod

### ISSUE THREAD

**Issue by vfiset** [Altinity/clickhouse-backup#703]
I am running clickhouse on kubernetes. I wanted to test clickhouse-backup. I created a config file:
```
general:
  remote_storage: gcs
gcs:
  credentials_file: /tmp/gcs.json
  path: /clickhousebackup/
  bucket: blablabla-tmp
```

Then I launch my backup with: `CLICKHOUSE_USERNAME=my-user CLICKHOUSE_PASSWORD=my-password CLICKHOUSE_HOST=my-host clickhouse-backup --config /tmp/config.yml create_remote`

A backup is created and uploaded on GCS but in only contains "metadata" which appear to be only table structure. No data is included.

**What am I missing ?**

Needless to say I am a clickhouse n00b.
