### ISSUE TITLE
Full Backup fails in watch mode

### ISSUE THREAD

**Issue by AlexanderBabel** [Altinity/clickhouse-backup#710]
Hello,
I am using the Clickhouse Helm Chart from Bitnami and attached the clickhouse-backup as a sidecar to it. It runs in watch mode and does not finish the backup as expected. It breaks with the following error:
```
2023/07/26 11:44:03.789267 error can't acquire semaphore during Upload data parts: context canceled logger=uploadTableData
```

### Software
- Clickhouse 23.5.2 (Bitnami)
- clickhouse-backup 2.3.2
- Kubernetes 1.26

### Environment Variables
```
    CLICKHOUSE_HOST: "localhost"
    CLICKHOUSE_PORT: "9000"
    CLICKHOUSE_USER: "default"
    CLICKHOUSE_PASSWORD: "[REDACTED]"

    REMOTE_STORAGE: s3
    WATCH_INTERVAL: 1h
    FULL_INTERVAL: 24h
    WATCH_BACKUP_NAME_TEMPLATE: "shard{shard}-{type}-{time:20060102150405}"

    S3_ACCESS_KEY: "[REDACTED]"
    S3_SECRET_KEY: "[REDACTED]"
    S3_BUCKET: clickhouse-backup
    S3_ENDPOINT: "[REDACTED]"
    S3_REGION: eu01
    S3_FORCE_PATH_STYLE: "true"
```

Logs
```
2023/07/26 11:43:59.009446  info clickhouse connection prepared: tcp://localhost:9000 run ping logger=clickhouse
2023/07/26 11:43:59.010523  info clickhouse connection open: tcp://localhost:9000 logger=clickhouse
2023/07/26 11:43:59.010578  info SELECT count() is_disk_type_present FROM system.columns WHERE database='system' AND table='disks' AND name='type' logger=clickhouse
2023/07/26 11:43:59.015573  info SELECT path, any(name) AS name, any(type) AS type FROM system.disks GROUP BY path logger=clickhouse
2023/07/26 11:43:59.021510  info SELECT max(toInt64(bytes_on_disk * 1.02)) AS max_file_size FROM system.parts logger=clickhouse
2023/07/26 11:43:59.031224  info SELECT count() AS is_macros_exists FROM system.tables WHERE database='system' AND name='macros'  SETTINGS empty_result_for_aggregation_by_empty_set=0 logger=clickhouse
2023/07/26 11:43:59.035839  info SELECT macro, substitution FROM system.macros logger=clickhouse
2023/07/26 11:43:59.728517  info done                      backup=shardshard0-full-20230726114340 duration=428ms operation=upload size=47.08KiB table=_stats.companies
2023/07/26 11:44:00.548216  info done                      backup=shardshard0-full-20230726114340 duration=1.248s operation=upload size=100.63KiB table=_stats.companies_top
2023/07/26 11:44:02.768922  info done                      backup=shardshard0-full-20230726114340 duration=3.469s operation=upload size=729.78KiB table=_stats.adverts
2023/07/26 11:44:03.789267 error can't acquire semaphore during Upload data parts: context canceled logger=uploadTableData
2023/07/26 11:44:03.789628 error UploadCompressedStream return error: context canceled logger=uploadTableData
2023/07/26 11:44:07.762436 error can't acquire semaphore during Upload data parts: context canceled logger=uploadTableData
2023/07/26 11:44:07.762492 error can't acquire semaphore during Upload table: context canceled backup=shardshard0-full-20230726114340 operation=upload
2023/07/26 11:44:07.763699 error can't acquire semaphore during Upload data parts: context canceled logger=uploadTableData
2023/07/26 11:44:07.763731 error can't acquire semaphore during Upload data parts: context canceled logger=uploadTableData
2023/07/26 11:44:07.959314 error UploadCompressedStream return error: context canceled logger=uploadTableData
2023/07/26 11:44:07.959354 error UploadCompressedStream return error: context canceled logger=uploadTableData
2023/07/26 11:44:07.959314 error UploadCompressedStream return error: context canceled logger=uploadTableData
2023/07/26 11:44:07.959323 error UploadCompressedStream return error: context canceled logger=uploadTableData
2023/07/26 11:57:42.223069  info clickhouse connection closed logger=clickhouse
2023/07/26 11:57:42.223126 error create_remote shardshard0-full-20230726114340 return error: one of upload table go-routine return error: one of uploadTableData go-routine return error: can't check uploaded file: key not found backup=shardshard0-full-20230726114340 logger=backuper operation=watch
```

**Comment by Slach** [comment]
Have your `clickhouse-backup` container the same disk volumes as `clickhouse-server` container?

Could you run inside your clickhouse-backup container following command?
`clickhouse-backup print-config`
and share `upload_concurrency` value?

Did you share full logs?

How exactly do you run clickhouse-backup inside pod?
```yaml
command:
 - clickhouse-backup
 - watch 
```

Could you share please?
`kubectl -n <your_namespace> clickhouse_pod_name -o yaml`

without sensitive credentials?

**Comment by AlexanderBabel** [comment]
Hey Slach,

yes, the disk is shared between the sidecar and clickhouse. Actually, the data is uploaded to S3. Sometimes it gets to around 400GB sometimes it uploads only 30GB because of the mentioned error. The `metadata` directory and a `shadow` dir are created.

Yes, I just run the `watch` as an argument for the sidecar (see pod manifest).

The logs are not full. The rest of the logs do not look relevant for the issue. If you need more insights, I can also provide additional logs.

Full configuration:
```yaml
general:
    remote_storage: s3
    max_file_size: 0
    disable_progress_bar: true
    backups_to_keep_local: 0
    backups_to_keep_remote: 0
    log_level: info
    allow_empty_backups: false
    download_concurrency: 16
    upload_concurrency: 4
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    retries_on_failure: 3
    retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    retriesduration: 30s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: default
    password: "[REDACTED]"
    host: localhost
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    timeout: 5m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /etc/clickhouse-server/
    restart_command: systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    debug: false
s3:
    access_key: "[REDACTED]"
    secret_key: "[REDACTED]"
    bucket: clickhouse-backup
    endpoint: "[REDACTED]"
    region: eu01
    acl: private
    assume_role_arn: ""
    force_path_style: true
    path: ""
    disable_ssl: false
    compression_level: 1
    compression_format: tar
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: false
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 17
    part_size: 0
    max_parts_count: 5000
    allow_multipart_download: false
    object_labels: {}
    debug: false
gcs:
    credentials_file: ""
    credentials_json: ""
    credentials_json_encoded: ""
    bucket: ""
    path: ""
    compression_level: 1
    compression_format: tar
    debug: false
    endpoint: ""
    storage_class: STANDARD
    object_labels: {}
    custom_storage_class_map: {}
cos:
    url: ""
    timeout: 2m
    secret_id: ""
    secret_key: ""
    path: ""
    compression_format: tar
    compression_level: 1
    debug: false
api:
    listen: localhost:7171
    enable_metrics: true
    enable_pprof: false
    username: ""
    password: ""
    secure: false
    certificate_file: ""
    private_key_file: ""
    ca_cert_file: ""
    ca_key_file: ""
    create_integration_tables: false
    integration_tables_host: ""
    allow_parallel: false
    complete_resumable_after_restart: true
ftp:
    address: ""
    timeout: 2m
    username: ""
    password: ""
    tls: false
    path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 17
    debug: false
sftp:
    address: ""
    port: 22
    username: ""
    password: ""
    key: ""
    path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 17
    debug: false
azblob:
    endpoint_schema: https
    endpoint_suffix: core.windows.net
    account_name: ""
    account_key: ""
    sas: ""
    use_managed_identity: false
    container: ""
    path: ""
    compression_level: 1
    compression_format: tar
    sse_key: ""
    buffer_size: 0
    buffer_count: 3
    max_parts_count: 5000
    timeout: 15m
custom:
    upload_command: ""
    download_command: ""
    list_command: ""
    delete_command: ""
    command_timeout: 4h
    commandtimeoutduration: 4h0m0s
```

Pod manifest:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-shard0-0
  generateName: clickhouse-shard0-
  namespace: warehouse
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-clickhouse-shard0-0
    - name: scripts
      configMap:
        name: clickhouse-scripts
        defaultMode: 493
    - name: config
      configMap:
        name: clickhouse
        defaultMode: 420
    - name: extra-config
      configMap:
        name: clickhouse-extra
        defaultMode: 420
    - name: clickhouse-backup-config
      secret:
        secretName: clickhouse-backup-config
        defaultMode: 420
    - name: kube-api-access-bzltv
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: clickhouse
      image: docker.io/bitnami/clickhouse:23.5.2-debian-11-r0
      command:
        - /scripts/setup.sh
      ports:
        - name: http
          containerPort: 8123
          protocol: TCP
        - name: tcp
          containerPort: 9000
          protocol: TCP
        - name: tcp-keeper
          containerPort: 2181
          protocol: TCP
        - name: tcp-keeperinter
          containerPort: 9444
          protocol: TCP
        - name: tcp-postgresql
          containerPort: 9005
          protocol: TCP
        - name: tcp-mysql
          containerPort: 9004
          protocol: TCP
        - name: http-intersrv
          containerPort: 9009
          protocol: TCP
      env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: CLICKHOUSE_HTTP_PORT
          value: '8123'
        - name: CLICKHOUSE_TCP_PORT
          value: '9000'
        - name: CLICKHOUSE_MYSQL_PORT
          value: '9004'
        - name: CLICKHOUSE_POSTGRESQL_PORT
          value: '9005'
        - name: CLICKHOUSE_INTERSERVER_HTTP_PORT
          value: '9009'
        - name: CLICKHOUSE_KEEPER_PORT
          value: '2181'
        - name: CLICKHOUSE_KEEPER_INTER_PORT
          value: '9444'
        - name: CLICKHOUSE_ADMIN_USER
          value: default
        - name: CLICKHOUSE_SHARD_ID
          value: shard0
        - name: CLICKHOUSE_REPLICA_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CLICKHOUSE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse
              key: admin-password
        - name: KEEPER_NODE_0
          value: clickhouse-shard0-0.clickhouse-headless.warehouse.svc.cluster.local
      resources:
        limits:
          cpu: '24'
          memory: 64Gi
        requests:
          cpu: '4'
          memory: 16Gi
      volumeMounts:
        - name: scripts
          mountPath: /scripts/setup.sh
          subPath: setup.sh
        - name: data
          mountPath: /bitnami/clickhouse
        - name: config
          mountPath: /bitnami/clickhouse/etc/conf.d/default
        - name: extra-config
          mountPath: /bitnami/clickhouse/etc/conf.d/extra-configmap
        - name: kube-api-access-bzltv
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        httpGet:
          path: /ping
          port: http
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ping
          port: http
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
    - name: clickhouse-backup
      image: altinity/clickhouse-backup:2.3.2
      args:
        - watch
      ports:
        - name: backup-api
          containerPort: 7171
          protocol: TCP
      envFrom:
        - secretRef:
            name: clickhouse-backup-config
      env:
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse
              key: admin-password
      resources: {}
      volumeMounts:
        - name: data
          mountPath: /bitnami/clickhouse
        - name: kube-api-access-bzltv
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: clickhouse
  serviceAccount: clickhouse
  nodeName: sbg5-b2-120-001-node-6ec3da
  securityContext:
    fsGroup: 1001
    seccompProfile:
      type: RuntimeDefault
  hostname: clickhouse-shard0-0
  subdomain: clickhouse-headless
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: clickhouse
                app.kubernetes.io/instance: clickhouse
                app.kubernetes.io/name: clickhouse
            topologyKey: kubernetes.io/hostname
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
```
