### ISSUE TITLE
Does clickhouse-backup support multiple disks?

### ISSUE THREAD

**Issue by sky9611** [Altinity/clickhouse-backup#728]
**Context**
 I have a clickhouse cluster held in Kubernetes using clickhouse-operator. Each pod has 4 attached PVC as disks. Besides the default storage path `var/lib/clickhouse`, the other three disks are mounted to path `/mnt/disk1/clickhouse/`, `/mnt/disk2/clickhouse/` and `/mnt/disk3/clickhouse/`. **I've already grant all permissions for user clickhouse to access these paths**

The clickhouse-backup is deployed in the same pod with each clickhouse pod as a sidecar container.

**Issue**
When I use clickhouse-backup to create backup, it appears that only files in the default storage path (`var/lib/clickhouse`) have been backed up. 

I created backup for partition `20230227` of table `circular_shard_primary.usage_event`.

Here is the created backup metadata file:

```json
[
  {
    "files": {
      "default": [
        "default_20230227_7105_7140_2_7204.tar",
        "default_20230227_7141_7180_2_7204.tar",
        "default_20230227_7181_7181_0_7204.tar",
        "default_20230227_7182_7182_0_7204.tar"
      ]
    },
    "table": "usage_event",
    "database": "circular_shard_primary",
    "parts": {
      "default": [
        {
          "name": "20230227_7105_7140_2_7204"
        },
        {
          "name": "20230227_7141_7180_2_7204"
        },
        {
          "name": "20230227_7181_7181_0_7204"
        },
        {
          "name": "20230227_7182_7182_0_7204"
        }
      ]
    },
    "query": "...",
    "size": {
      "default": 2566276367
    },
    "total_bytes": 4392430151162,
    "metadata_only": false
  }
]
```

And from table `system.parts`, we can get:

``` sql
-- select name, path from system.parts where database = 'circular_shard_primary' and table = 'usage_event' and partition = '20230227'

20230227_5312_6614_4_7204 /mnt/disk3/clickhouse/data/circular_shard_primary/usage_event/20230227_5312_6614_4_7204/
20230227_6615_6880_3_7204 /mnt/disk3/clickhouse/data/circular_shard_primary/usage_event/20230227_6615_6880_3_7204/
20230227_6881_7104_3_7204 /mnt/disk3/clickhouse/data/circular_shard_primary/usage_event/20230227_6881_7104_3_7204/
20230227_7105_7140_2_7204 /var/lib/clickhouse/data/circular_shard_primary/usage_event/20230227_7105_7140_2_7204/
20230227_7141_7180_2_7204 /var/lib/clickhouse/data/circular_shard_primary/usage_event/20230227_7141_7180_2_7204/
20230227_7181_7181_0_7204 /var/lib/clickhouse/data/circular_shard_primary/usage_event/20230227_7181_7181_0_7204/
20230227_7182_7182_0_7204 /var/lib/clickhouse/data/circular_shard_primary/usage_event/20230227_7182_7182_0_7204/

```
As you can see, only parts stored in default disk(20230227_7105_7140_2_7204, 20230227_7141_7180_2_7204, 20230227_7181_7181_0_7204, 20230227_7182_7182_0_7204) have been backed up, while others are ignored

**Question**
Does clickhouse-backup support to create backup with data stored in multiple disks? If so, how should I configure it

<details>
<summary>k8s manifest</summary>

``` yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  annotations: {}
spec:
  configuration:
    clusters:
    - layout:
        shardsCount: 36
    zookeeper:
      nodes:
      - host: zookeeper
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse
      serviceTemplate: svc-template
  templates:
    serviceTemplates:
    - name: svc-template
      spec:
        ports:
        - name: http
          port: 8123
        - name: tcp
          port: 9000
        type: LoadBalancer
    podTemplates:
    - name: clickhouse
      spec:
        containers:
        - image: clickhouse
          name: clickhouse-pod
          volumeMounts:
          - name: default
            mountPath: "/var/lib/clickhouse"
          - name: disk1
            mountPath: "/mnt/disk1/clickhouse/"
          - name: disk2
            mountPath: "/mnt/disk2/clickhouse/"
          - name: disk3
            mountPath: "/mnt/disk3/clickhouse/"
          command:
          - "/bin/bash"
          - "-c"
          - chown clickhouse /mnt/disk1/clickhouse/ && chown clickhouse /mnt/disk2/clickhouse/
            && chown clickhouse /mnt/disk3/clickhouse/ && /entrypoint.sh
        - name: clickhouse-backup
          image: clickhouse-backup
          imagePullPolicy: Always
          command:
          - bash
          - "-xc"
          - "/bin/clickhouse-backup server"
          env:
          - name: LOG_LEVEL
            value: debug
          - name: ALLOW_EMPTY_BACKUPS
            value: 'true'
          - name: API_LISTEN
            value: 0.0.0.0:7171
          - name: API_CREATE_INTEGRATION_TABLES
            value: 'true'
          - name: BACKUPS_TO_KEEP_REMOTE
            value: '3'
          - name: CLICKHOUSE_CHECK_REPLICAS_BEFORE_ATTACH
            value: 'false'
          ports:
          - name: backup-rest
            containerPort: 7171
        nodeSelector:
          beta.kubernetes.io/os: linux
    volumeClaimTemplates:
    - name: default
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Ti
    - name: disk1
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Ti
    - name: disk2
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Ti
    - name: disk3
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Ti
```

</details>
