### ISSUE TITLE
error 'backup20230825metadata.json' is not found on remote storage

### ISSUE THREAD

**Issue by zouwenjie00** [Altinity/clickhouse-backup#732]
when I Upload  the backup to S3 ,the S3 name is  like "backup20230825/metadata.json",when I download the backup file to run command:
./clickhouse-backup -c config.yml  download  backup20230828/metadata.json,
there is error,
message is error 'backup20230825metadata.json' is not found on remote storage
please help me

**Comment by Slach** [comment]
you need use backupname instead of backup_name/metadata.json
you can't download only one file

`clickhouse-backup -c config.yml download backup20230828`

**Comment by zouwenjie00** [comment]
> you need use backupname instead of backup_name/metadata.json you can't download only one file
> 
> `clickhouse-backup -c config.yml download backup20230828`

it is still error ,But when I run this command ,it also error,message is "error 'backup20230828' is not found on remote storage"

when I exec ./clickhouse-backup -c config.yml list ,the message is :
```
backup20230828/metadata/bigdata/VW_MTPART.json                                ???         27/08/2023 18:02:19   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX.json                  ???         27/08/2023 18:02:19   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json                 ???         27/08/2023 18:02:19   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json                 ???         27/08/2023 18:02:19   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/user_info_hive_hdfs.json                      ???         27/08/2023 18:02:19   remote      broken (can't stat metadata.json)
backup20230828/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_5_1   11.35MiB    27/08/2023 18:02:25   remote      , old-format
backup20230828/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_1_1_0   70.29MiB    27/08/2023 18:02:27   remote      , old-format
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX4.json                 ???         27/08/2023 18:02:28   remote      broken (can't stat metadata.json)
backup20230828/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_0_0_0   79.64MiB    27/08/2023 18:02:28   remote      , old-format
backup20230828/metadata/bigdata/ads_hr_core_list_od_m.json                    ???         27/08/2023 18:02:30   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/ads_hr_slr_ben_mul_m.json                     ???         27/08/2023 18:02:35   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/query_log_all.json                            ???         27/08/2023 18:02:38   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/vw_test_repeat_data.json                      ???         27/08/2023 18:02:42   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/ads_hr_core_list_od_m_f.json                  ???         27/08/2023 18:02:51   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/vw_user_info_hive_m.json                      ???         27/08/2023 18:02:56   remote      broken (can't stat metadata.json)
backup20230828/metadata.json  
```

**Comment by Slach** [comment]
could yuo share
`clickhouse-backup print-config`

without sensitive credentials?

**Comment by zouwenjie00** [comment]
> Collaborator

```yaml
general:
  remote_storage: s3
  backups_to_keep_local: 2
  backups_to_keep_remote: 0
  max_file_size: 1099511627776
  disable_progress_bar: false
  log_level: debug
  allow_empty_backups: false
clickhouse:
  username: default
  password: "123455"
  host: 10.120.1.33
  port: 19000
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  log_sql_queries: true
  skip_tables:
  - system.*
  - default.*
  - information_schema.*
  - finance_d_ksha.*
  - dm_goa_new.*
  - datamax.*
  - dev_apm.*

s3:
  access_key: "XXXXX"                   # S3_ACCESS_KEY，<AWS访问密钥> 
  secret_key: "XXXXX"                   # S3_SECRET_KEY 
  bucket: "datasafe"                       # S3_BUCKET，<存储桶BUCKET名称> 
  endpoint: "http://oss-cn-uat.com"                     # S3_ENDPOINT   
  force_path_style: false          # S3_FORCE_PATH_STYLE 
  path: ""                         # S3_PATH ， <备份路径> 
```

**Comment by Slach** [comment]
try to use
```
s3:
  force_path_style: true  
```

and share
`S3_DEBUG=1 clickhouse-backup list remote`

Moreover, try to install aws cli and share 
```
AWS_ACCESS_KEY_ID=XXX AWS_ACCESS_SECRET_KEY=YYY aws s3 ls --endpoint-url http://oss-cn-uat.com s3://datasafe/
```

**Comment by Slach** [comment]
`  backups_to_keep_local: 2`

have no sense and will allocate disk space

better `backups_to_keep_local: 1` and after successfully upload `delete local <backup_name>`

**Comment by zouwenjie00** [comment]
> try to use
> 
> ```
> s3:
>   force_path_style: true  
> ```
> 
> and share `S3_DEBUG=1 clickhouse-backup list remote`
> 
> Moreover, try to install aws cli and share
> 
> ```
> AWS_ACCESS_KEY_ID=XXX AWS_ACCESS_SECRET_KEY=YYY aws s3 ls --endpoint-url http://oss-cn-uat.com s3://datasafe/
> ```
I set the params as below：
s3:
  force_path_style: true 
but it is still error。error 'backup20230828' is not found on remote storage

when i use the aws cli，I can download the s3 file to the local:
download: s3://datasafe/backup20230828/metadata/bigdata/vw_test_repeat_data.json to ../../../data/metadata/bigdata/vw_test_repeat_data.json
download: s3://datasafe/backup20230828/metadata.json to ../../../data/metadata.json
download: s3://datasafe/backup20230828/metadata/bigdata/vw_user_info_hive_m.json to ../../../data/metadata/bigdata/vw_user_info_hive_m.json
download: s3://datasafe/backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json to ../../../data/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json
download: s3://datasafe/backup20230828/metadata/bigdata/query_log_all.json to ../../../data/metadata/bigdata/query_log_all.json
download: s3://datasafe/backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX4.json to ../../../data/metadata/bigdata/VW_MTPARTUSAGELINKDataX4.json
download: s3://datasafe/backup20230828/metadata/bigdata/ads_hr_slr_ben_mul_m.json to ../../../data/metadata/bigdata/ads_hr_slr_ben_mul_m.json
download: s3://datasafe/backup20230828/metadata/bigdata/ads_hr_core_list_od_m_f.json to ../../../data/metadata/bigdata/ads_hr_core_list_od_m_f.json
download: s3://datasafe/backup20230828/metadata/bigdata/VW_MTPART.json to ../../../data/metadata/bigdata/VW_MTPART.json
download: s3://datasafe/backup20230828/metadata/bigdata/user_info_hive_hdfs.json to ../../../data/metadata/bigdata/user_info_hive_hdfs.json
download: s3://datasafe/backup20230828/metadata/bigdata/ads_hr_core_list_od_m.json to ../../../data/metadata/bigdata/ads_hr_core_list_od_m.json
download: s3://datasafe/backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX.json to ../../../data/metadata/bigdata/VW_MTPARTUSAGELINKDataX.json
download: s3://datasafe/backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json to ../../../data/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json
download: s3://datasafe/backup20230828/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_2_5_1.tar to ../../../data/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_2_5_1.tar
download: s3://datasafe/backup20230828/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_1_1_0.tar to ../../../data/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_1_1_0.tar
download: s3://datasafe/backup20230828/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_0_0_0.tar to ../../../data/shadow/bigdata/ads_hr_core_list_od_m_f/disk_name_1_all_0_0_0.tar

**Comment by zouwenjie00** [comment]
> ` backups_to_keep_local: 2`
> 
> have no sense and will allocate disk space
> 
> better `backups_to_keep_local: 1` and after successfully upload `delete local <backup_name>`

i guess the cause is file path contains "/",clickhouse-backup tools dill it with ""

**Comment by Slach** [comment]
could you do exactly what i recommends and share output of commands?

**Comment by zouwenjie00** [comment]
> s3:
>   force_path_style: true

1. I update the config.yml to set  force_path_style: true  and backups_to_keep_local: 1 ；to exec commands" ./clickhouse-backup -c config.yml download backup20230828"
    the error messgae is "2023/08/28 19:37:31.999120 error 'backup20230828' is not found on remote storage"

exec commands "./clickhouse-backup -c config.yml list remote",there also have files list:
backup20230828/metadata/bigdata/VW_MTPART.json                                ???        28/08/2023 05:43:01   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX.json                  ???        28/08/2023 05:43:01   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json                 ???        28/08/2023 05:43:01   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json                 ???        28/08/2023 05:43:01   remote      broken (can't stat metadata.json)
backup20230828/metadata/bigdata/user_info_hive_hdfs.json                      ???        28/08/2023 05:43:01   remote      broken (can't stat metadata.json)


2.  I also install aws cli ,and exec the command "bin/aws s3 cp --endpoint-url http://oss-cn-uat.com s3://datasafe/backup20230828/ /data/ --recursive" ,it running sucess, and files can download,the message is :
download: s3://datasafe/backup20230828/metadata/bigdata/vw_test_repeat_data.json to ../../../data/metadata/bigdata/vw_test_repeat_data.json
download: s3://datasafe/backup20230828/metadata.json to ../../../data/metadata.json

3. so what can i do to use clickhouse-back restore database? 
4. i want to do for this : first use  aws cli download files to local path; second use clickhouse-back tool restore the database by local files ; and last to remove the local files.

**Comment by Slach** [comment]
looks like your s3 backend is not s3 compatible

I asked you to share full logs for the following two commands

first

```
S3_DEBUG=1 clickhouse-backup list remote
```

You run it. But share nothing useful, I asked about full command output.

Second
```
AWS_ACCESS_KEY_ID=XXX AWS_ACCESS_SECRET_KEY=YYY aws s3 ls --endpoint-url http://oss-cn-uat.com s3://datasafe/
```

**Comment by zouwenjie00** [comment]
thank you ,those messages is useful? 
first:
https://github.com/zouwenjie00/bootout/blob/master/backup-list.log


Second:
AWS_ACCESS_KEY_ID=xOaTXyJjbYhzWnJOh8fBocm AWS_SECRET_ACCESS_KEY=4q09TrM0dMukDYzPLklY08y0rNVUBcq bin/aws s3 ls --endpoint-url http://oss-cn-uat.com s3://datasafe/
```
2023-08-28 14:08:15   21349037 awscli-bundle.zip
2023-08-28 13:43:52       1716 metadata.json
2023-08-28 13:43:35        740 vw_user_info_hive_m.json
2023-08-28 13:43:33      62086 ads_hr_core_list_od_m_f.json
2023-08-28 13:43:24        374 vw_test_repeat_data.json
2023-08-28 13:43:20       2460 query_log_all.json
2023-08-28 13:43:17       8449 ads_hr_slr_ben_mul_m.json
2023-08-28 13:43:14      61635 ads_hr_core_list_od_m.json
2023-08-28 13:43:09        968 VW_MTPARTUSAGELINKDataX4.json
2023-08-28 13:43:06   83513344 disk_name_1_all_0_0_0.tar
2023-08-28 13:43:05   73700864 disk_name_1_all_1_1_0.tar
2023-08-28 13:43:02   11901952 disk_name_1_all_2_5_1.tar
2023-08-28 13:43:01        930 VW_MTPARTUSAGELINKDataX5.json
2023-08-28 13:43:01        753 user_info_hive_hdfs.json
2023-08-28 13:43:01        970 VW_MTPARTUSAGELINKDataX.json
2023-08-28 13:43:01       6024 VW_MTPART.json
2023-08-28 13:43:01        973 VW_MTPARTUSAGELINKDataX3.json
```

**Comment by Slach** [comment]
How did you upload your backup to `datasafe` bucket?

shared `aws s3 ls` result show uploaded backup to root of bucket without backup name

instead of `metadata.json` it should be `backup_name/metadata.json`

**Comment by zouwenjie00** [comment]
> How did you upload your backup to `datasafe` bucket?
> 
> shared `aws s3 ls` result show uploaded backup to root of bucket without backup name
> 
> instead of `metadata.json` it should be `backup_name/metadata.json`

How did you upload your backup to datasafe bucket?
I exec 
1.create : ./clickhouse-backup -c config.yml create backup20230828
2.upload to s3 bucket: ./clickhouse-backup -c config.yml upload backup20230828

**Comment by zouwenjie00** [comment]
> How did you upload your backup to `datasafe` bucket?
> 
> shared `aws s3 ls` result show uploaded backup to root of bucket without backup name
> 
> instead of `metadata.json` it should be `backup_name/metadata.json`

when download files to exec "./clickhouse-backup -c config.yml download backup20230828 "

the log is HEAD /datasafe/backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json/metadata.json HTTP/1.1
the request HTTP/1.1 404 Not Found

I do not know  the http request url "/datasafe/backup20230828/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json/metadata.json"  why add "metadata.json"

**Comment by Slach** [comment]
could you clean your `datasafe` bucket from current data
and share results of following command?
`S3_DEBUG=1 clickhouse-backup -c config.yml create_remote backup20230829`

**Comment by zouwenjie00** [comment]
> could you clean your `datasafe` bucket from current data and share results of following command? `S3_DEBUG=1 clickhouse-backup -c config.yml create_remote backup20230829`


 S3_DEBUG=1  ./build/linux/amd64/clickhouse-backup create_remote backup20230829 -c config.yml
the log message is :
https://github.com/zouwenjie00/bootout/blob/master/create_remote.log

**Comment by zouwenjie00** [comment]
> could you clean your `datasafe` bucket from current data and share results of following command? `S3_DEBUG=1 clickhouse-backup -c config.yml create_remote backup20230829`

and i exec download : the response message add metadata.json in last of path:
/datasafe/backup20230829/metadata/bigdata/VW_MTPARTUSAGELINKDataX4.json/metadata.json



S3 Response message is :
2023/08/29 17:21:07.412560  info [s3:DEBUG] request failed with unretryable error https response error StatusCode: 404, RequestID: , HostID: , NotFound:
2023/08/29 17:21:07.412908  info [s3:DEBUG] Request
HEAD /datasafe/backup20230829/backup20230829/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json/metadata.json HTTP/1.1^M
Host: 10.16.64.202:8086^M
User-Agent: aws-sdk-go-v2/1.18.1 os/linux lang/go/1.21.0 md/GOOS/linux md/GOARCH/amd64 api/s3/1.34.0^M
Accept-Encoding: identity^M
Amz-Sdk-Invocation-Id: 67d4fef7-17df-4746-a87a-fc6e217bbf1a^M
Amz-Sdk-Request: attempt=1; max=3^M
Authorization: AWS4-HMAC-SHA256 Credential=xOaTXyJjbYhzWnJOh8fGBocm/20230829/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=c4bd9736d5785085616c26039951144644cd76be1b682a4221676b705135309e^M
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855^M
X-Amz-Date: 20230829T092107Z^M
^M

2023/08/29 17:21:07.425526  info [s3:DEBUG] Response
HTTP/1.1 404 Not Found^M
Content-Length: 279^M
Content-Type: application/xml; charset=utf-8^M
Date: Tue, 29 Aug 2023 09:21:07 GMT^M
X-Request-Id: oss-628810ca-0c6e-446a-ba7c-5121391fa407^M

**Comment by Slach** [comment]
lets clean `datasafe` bucket again

and change config.yml
```yaml
s3:
  force_path_style: true
  path: backups
```

after it run
```
clickhouse-backup -c config.yml create_remote test_backup
```

and share result for
```
clickhouse-backup -c config.yml list remote
```

**Comment by zouwenjie00** [comment]
> test_backup

changed config.yml
```
s3:
  force_path_style: true          # S3_FORCE_PATH_STYLE 
  path: "backup20230829"                         # S3_PATH 
  debug: true          
```
after it run
`clickhouse-backup -c config.yml create_remote test_backup`

the s3 files name :
backup20230829/test_backup/metadata.json
backup20230829/test_backup/metadata/bigdata/vw_user_info_hive_m.json
backup20230829/test_backup/metadata/bigdata/vw_test_repeat_data.json

> and share result for
> `clickhouse-backup -c config.yml list remote`

the run messages is：
https://github.com/zouwenjie00/bootout/blob/master/list_remote.log

**Comment by sourabhaggrawal** [comment]
Hi, 
I am also facing the same problem, I am able to create backup and upload to S3 and can see the data in S3 buckets from aws console, but when try to restore using clickhouse-backup it says backup does not exist on remote  I am using latest version 2.4.0 of clickhouse-backup.

Below is the config
```yaml
general:
    remote_storage: s3
    max_file_size: 0
    disable_progress_bar: true
    backups_to_keep_local: 0
    backups_to_keep_remote: 0
    log_level: info
    allow_empty_backups: false
    download_concurrency: 1
    upload_concurrency: 1
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    retries_on_failure: 3
    retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    sharded_operation_mode: ""
    retriesduration: 30s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: default
    password: ""
    host: chi-medium-cluster-1-0-0-0.chi-medium-cluster-1-0-0.default.svc.cluster.local
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    skip_table_engines: []
    timeout: 5m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /etc/clickhouse-server/
    restart_command: exec:systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    debug: false
s3:
    access_key: ********
    secret_key: **********
    bucket: *******
    endpoint: https://*****.s3.amazonaws.com
    region: us-west-2
    acl: private
    assume_role_arn: ""
    force_path_style: true
    path: ""
    object_disk_path: ""
    disable_ssl: false
    compression_level: 1
    compression_format: tar
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: false
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 2
    part_size: 0
    max_parts_count: 5000
    allow_multipart_download: false
    object_labels: {}
    debug: true
```

Below is the output of "create"

```
./build/linux/amd64/clickhouse-backup list remote
2023/08/29 09:30:10.751254  info clickhouse connection prepared: tcp://chi-medium-cluster-1-0-0-0.chi-medium-cluster-1-0-0.default.svc.cluster.local:9000 run ping logger=clickhouse
2023/08/29 09:30:10.777842  info clickhouse connection open: tcp://chi-medium-cluster-1-0-0-0.chi-medium-cluster-1-0-0.default.svc.cluster.local:9000 logger=clickhouse
2023/08/29 09:30:10.781569  info SELECT count() AS is_macros_exists FROM system.tables WHERE database='system' AND name='macros'  SETTINGS empty_result_for_aggregation_by_empty_set=0 logger=clickhouse
2023/08/29 09:30:10.876305  info SELECT macro, substitution FROM system.macros logger=clickhouse
2023/08/29 09:30:10.910361  info [s3:DEBUG] Request
GET /clickhouse-backup-stage?versioning= HTTP/1.1
Host: clickhouse-backup-stage.s3.amazonaws.com


2023/08/29 09:30:12.210772  info [s3:DEBUG] Response
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Tue, 29 Aug 2023 09:30:13 GMT
Server: AmazonS3


71
<?xml version="1.0" encoding="UTF-8"?>
<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
0


2023/08/29 09:30:12.217865  info [s3:DEBUG] Request
GET /clickhouse-backup-stage?delimiter=%2F&list-type=2&max-keys=1000&prefix= HTTP/1.1
Host: clickhouse-backup-stage.s3.amazonaws.com
User-Agent: aws-sdk-go-v2/1.18.1 os/linux lang/go/1.21.0 md/GOOS/linux md/GOARCH/amd64 api/s3/1.34.0



2023/08/29 09:30:12.518387  info [s3:DEBUG] Response
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 29 Aug 2023 09:30:13 GMT
Server: AmazonS3


126
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>clickhouse-backup-stage</Key><RequestId>949MJN53K6S7M0KJ</RequestId><HostId>sS95Oo3c26Cfzmb5sLgCRG9WOBzDZeCFAgSOn5DBhgC8pKZosvG7Kw8XCEwOsuRHncNkw=</HostId></Error>
0


2023/08/29 09:30:12.521230  info [s3:DEBUG] request failed with unretryable error https response error StatusCode: 404, RequestID: 949MJN53K6S7M0KJ, HostID: sS95Oo3c26Cfzmb5sLgCRG9WOBzDZeCFAgSOn5DBhgC8pKZosvG7Kw8XCEwOsuRHncNkw=, api error NoSuchKey: The specified key does not exist.
2023/08/29 09:30:12.523733  warn BackupList bd.Walk return error: operation error S3: ListObjectsV2, https response error StatusCode: 404, RequestID: 949MJN53K6S7M0KJ, HostID: sS95Oo3c26Cfzmb5sLgCRG9WOBzDZeCFAgSOn5DBhgC8pKZosvG7Kw8XCEwOsuRHncNkw=, api error NoSuchKey: The specified key does not exist. logger=s3
2023/08/29 09:30:12.531153  info clickhouse connection closed logger=clickhouse
```

**Comment by sourabhaggrawal** [comment]
Same configuration was used to create/upload backup to s3.

**Comment by Slach** [comment]
@zouwenjie00 

from shared logs

`GET /datasafe?delimiter=%2F&list-type=2&max-keys=1000&prefix=backup20230829%2F`

return 

```xml
<ListBucketResult>
    <Name>datasafe</Name>
    <Prefix>backup20230829/</Prefix>
    <KeyCount>12</KeyCount>
    <MaxKeys>1000</MaxKeys>
    <ContinuationToken>0</ContinuationToken>
    <NextContinuationToken>0</NextContinuationToken>
    <IsTruncated>false</IsTruncated>
    <Contents>
        <ETag>&#34;5c3ff60326ef2cc89f52662f0821bae3&#34;</ETag>
        <Key>backup20230829/test_backup/metadata.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>1654</Size>
    </Contents>
    <Contents>
        <ETag>&#34;c59d4a295a57b4d5115f49cafc1948e3&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/vw_user_info_hive_m.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>740</Size>
    </Contents>
    <Contents>
        <ETag>&#34;df631be51ab3759f628f850a8f1e1cb9&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/vw_test_repeat_data.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>374</Size>
    </Contents>
    <Contents>
        <ETag>&#34;835f8e6af22d0a8483b4154e033bf3c5&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/query_log_all.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>2460</Size>
    </Contents>
    <Contents>
        <ETag>&#34;0d42b32b4c3cfe08d8722dddfbfffc57&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/ads_hr_slr_ben_mul_m.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>8449</Size>
    </Contents>
    <Contents>
        <ETag>&#34;6bc33fde57026c4d46555e4460f0b9eb&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/VW_MTPARTUSAGELINKDataX.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>970</Size>
    </Contents>
    <Contents>
        <ETag>&#34;14b10a6fb90e110df6073059f5ea563c&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/VW_MTPARTUSAGELINKDataX4.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>968</Size>
    </Contents>
    <Contents>
        <ETag>&#34;62f87590bff1e3b700a3ec5d5ce8ce18&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/ads_hr_core_list_od_m.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>61635</Size>
    </Contents>
    <Contents>
        <ETag>&#34;ac2167540780bbb95154d85bc83a4ff6&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/VW_MTPARTUSAGELINKDataX3.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>973</Size>
    </Contents>
    <Contents>
        <ETag>&#34;e26f43ed8651a5153d66038b720c6f98&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/user_info_hive_hdfs.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>753</Size>
    </Contents>
    <Contents>
        <ETag>&#34;d8779548e15d6171d1a2a8d9bcb667e2&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/VW_MTPART.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>6024</Size>
    </Contents>
    <Contents>
        <ETag>&#34;6050ff88ea7d872c31a3612f4b557c9b&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>930</Size>
    </Contents>
</ListBucketResult> 
```

looks like your S3 "compatible" provider is not respect request parameters `delimiter=%2F&list-type=2`
instead of
```xml
    <Contents>
        <ETag>&#34;6050ff88ea7d872c31a3612f4b557c9b&#34;</ETag>
        <Key>backup20230829/test_backup/metadata/bigdata/VW_MTPARTUSAGELINKDataX5.json</Key>
        <LastModified>2023-08-29T17:28:35+08:00</LastModified>
        <Owner>
            <ID>1EB391CEA6F644779DB5471464CAE0C5</ID>
            <DisplayName>1EB391CEA6F644779DB5471464CAE0C5</DisplayName>
        </Owner>
        <Size>930</Size>
    </Contents>

```

The expected result here shall be something like that:
```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>datasafe</Name>
    <Prefix>backup20230829/</Prefix>
    <KeyCount>1</KeyCount>
    <MaxKeys>1000</MaxKeys>
    <Delimiter>/</Delimiter>
    <IsTruncated>false</IsTruncated>
    <CommonPrefixes>
        <Prefix>test_backup/</Prefix>
    </CommonPrefixes>
</ListBucketResult>
```

Which exactly provider do you use? Could you ask your provider to check this comment?
`oss-cn-uat.com` is unknown domain

**Comment by Slach** [comment]
@sourabhaggrawal you have different problem
you don't need `force_path_style` and need to set up `endpoint` because you are using AWS S3 directly, instead of S3-compatible provider for @zouwenjie00 use-case

change config.yml
```yaml
 s3:
    force_path_style: false
    access_key: ********
    secret_key: **********
    bucket: *******
    # remove endpint from config 
    # endpoint: https://*****.s3.amazonaws.com
    region: us-west-2
    
    # you are use kubernetes `clickhouse-operator`, so better will use
    path: backups/{cluster}/{shard} 

```
