### ISSUE TITLE
Add support for custom path to clickhouse folders

### ISSUE THREAD

**Issue by TheRedPandaDev** [Altinity/clickhouse-backup#741]
My clickhouse folders are on a different path than "/var/lib/clickhouse". I tried specifying this path in my config.yaml with disk_mapping: { default: "<my_path>" }, it helped with creating backups, but I can't restore from them due to error "error can't copy data to datached '<my_table>': error during filepath.Walk for part '202308_0_7_2': failed to create hard link '<my_path>/backup/2023-09-07T07-08-29/shadow/process/element_local/default/202308_0_7_2/checksums.txt' -> '/var/lib/clickhouse/store/e56/e56ea89c-4e6b-41f8-9018-a0265225a3a1/detached/202308_0_7_2/checksums.txt': link <my_path>/backup/2023-09-07T07-08-29/shadow/process/element_local/default/202308_0_7_2/checksums.txt /var/lib/clickhouse/store/e56/e56ea89c-4e6b-41f8-9018-a0265225a3a1/detached/202308_0_7_2/checksums.txt: invalid cross-device link".
Is something wrong with my disk_mapping configuration or is there not support for custom path?

**Comment by Slach** [comment]
could you share from your destination server

`SELECT * FROM system.disks`
and
`SELECT * FROM system.storage_policies`

**Comment by TheRedPandaDev** [comment]
@Slach
system.disks:
backups,/opt/
default,/var/lib/clickhouse/
storage_policies:
default,default

**Comment by TheRedPandaDev** [comment]
clickhouse-server is running in Docker and the '/var/lib/clickhouse' is mounted to my custom path. Is there a way to make it work?

**Comment by Slach** [comment]
ok. got it
you are run clickhouse-server inside docker + volume to /data/ on host

i think better solution will run `clickhouse-server` + `clickhouse-backup`
in docker-compose 
with the same volumes

something like
```yaml
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      /<my_path>:/var/lib/clickhouse
      /<my_path_opt>:/opt
  clickhouse-backup:
    image: altinity/clickhouse-backup:latest
    volumes_from:
      - clickhouse 
```
