### ISSUE TITLE
debug disk_name_4 disk have no parts operation=HardlinkBackupPartsToStorage

### ISSUE THREAD

**Issue by zouwenjie00** [Altinity/clickhouse-backup#743]
Hi：
I want to backup database in clickhouse cluster A ,and restore it on other clickhouse cluster B, But the clickhouse cluster B  table have no data. 
when run the command is "./build/linux/amd64/clickhouse-backup restore_remote ck-bak-20230907 -c config-metric-platform-46.yml -s -d --rm"
there have many this message in different table:
2023/09/08 02:54:30.724549  info done                      backup=ck-bak-20230907 operation=restore table=metric_platform.ods_rdm_tester_efficiency
2023/09/08 02:54:30.724653 debug disk_name_2 disk have no parts operation=HardlinkBackupPartsToStorage
2023/09/08 02:54:30.724693 debug disk_name_4 disk have no parts operation=HardlinkBackupPartsToStorage
2023/09/08 02:54:30.724722 debug disk_name_1 disk have no parts operation=HardlinkBackupPartsToStorage
2023/09/08 02:54:30.724752 debug disk_name_3 disk have no parts operation=HardlinkBackupPartsToStorage

**Comment by Slach** [comment]
Could you clarify? Is tables restored finally?

Could you share: 
`SELECT * FROM system.disks FORMAT Vertical` 
from source and destination clickhouse-server?

**Comment by zouwenjie00** [comment]
> 

the metadata had restored，but the data not restored；

Cluster A disk is：
![image](https://github.com/Altinity/clickhouse-backup/assets/27050487/bb9eff43-ee24-45e4-bf04-b6af471d35f6)

Cluster B disk is：

![image](https://github.com/Altinity/clickhouse-backup/assets/27050487/15e59f33-be4c-48cb-9ecf-92ef75e7b62c)
![image](https://github.com/Altinity/clickhouse-backup/assets/27050487/3ef36976-9f80-4255-b491-e37fc9d9b201)

**Comment by Slach** [comment]
Use `clickhouse-client` in the future and please don't share information as pictures

So, you have 2 disk in source server and 5 disk in destination server?

Could you share:
`SELECT * FROM system.storage_policies` from both servers?

Could you please clarify and answer to all my qustions?
how did you run `clickhouse-backup`?
Is your source `clickhouse-server` run as standalone or inside `docker` container?
Did you run `clickhouse-backup create` outside docker on host?
Is your destination `clickhouse-server` run as standalone on a separate machine?
How did you move data between the source and destination server?

Could you share a result of the following command from the destination server?
`ls -la /data/ssd01/ck1/data/clickhouse/backup/ck-bak-20230907/shadow/*/*/`

**Comment by zouwenjie00** [comment]
> Use `clickhouse-client` in the future and please don't share information as pictures
> 
> So, you have 2 disk in source server and 5 disk in destination server?
> 
> Could you share: `SELECT * FROM system.storage_policies` from both servers?
> 
> Could you please clarify and answer to all my qustions? how did you run `clickhouse-backup`? Is your source `clickhouse-server` run as standalone or inside `docker` container? Did you run `clickhouse-backup create` outside docker on host? Is your destination `clickhouse-server` run as standalone on a separate machine? How did you move data between the source and destination server?
> 
> Could you share a result of the following command from the destination server? `ls -la /data/ssd01/ck1/data/clickhouse/backup/ck-bak-20230907/shadow/*/*/`

1. Yes, I have 2 disk in source server and 5 disk in destination server

2. Could you share:
SELECT * FROM system.storage_policies from both servers?
Cluster A:
```
policy_name            volume_name                disks
default                     default                           default
policy_name_1         volume_name_0            policy_name_1
```

Cluster B:
```
policy_name            volume_name                disks
default                     default                           default
policy_name_1         volume_name_0            ['disk_name_1','disk_name_2','disk_name_3','disk_name_4']
```

3.I run clickhouse-backup in the clusterA Server
first i create and  upload to s3:
./build/linux/amd64/clickhouse-backup create_remote ck-bak-20230907 -c config-metric-platform.yml
last i restore the command on cluster A
./build/linux/amd64/clickhouse-backup restore_remote ck-bak-20230907 -c config-metric-platform-46.yml
the config of  config-metric-platform.yml is :

```yaml
general:
  remote_storage: s3
  #remote_storage: none
  backups_to_keep_local: 1
  backups_to_keep_remote: 0
  max_file_size: 1099511627776
  disable_progress_bar: true
  log_level: debug
  allow_empty_backups: false
  download_concurrency: 1
  upload_concurrency: 1
  use_resumable_state: true
  restore_schema_on_cluster: ""
  upload_by_part: true
  download_by_part: true
  restore_database_mapping: {}
clickhouse:
  username: default
  password: "XXX"
  host: 10.18.106.46
  port: 19000
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  log_sql_queries: true
  #data_path: "/data/clickhouse-backup"
  #disk_mapping: {"default": "/data/clickhouse-backup"}
  skip_tables:
  - system.*
  - default.*
  - information_schema.*
  - finance_d_ksha.*
  - dm_goa_new.*
  - INFORMATION_SCHEMA.*

s3:
  access_key: "xxxxxx"                   # S3_ACCESS_KEY，<AWS访问密钥> 
  secret_key: "xxxxxx"                   # S3_SECRET_KEY 
  bucket: "datasafe"                       # S3_BUCKET，<存储桶BUCKET名称>                  #  
  endpoint: "http://oss-cn-uat.com"
  force_path_style: true          # S3_FORCE_PATH_STYLE 
  path: "backup"                         # S3_PATH ， <备份路径> 
  debug: true                     # S3_DEBUG
  disable_ssl: false               # S3_DISABLE_SSL 
  part_size: 536870912
  compression_level: 1             # S3_COMPRESSION_LEVEL 
  compression_format: tar          # S3_COMPRESSION_FORMAT 
```

config-metric-platform-46.yml is : 
```yaml
general:
  remote_storage: s3
  #remote_storage: none
  backups_to_keep_local: 1
  backups_to_keep_remote: 0
  max_file_size: 1099511627776
  disable_progress_bar: true
  log_level: debug
  allow_empty_backups: false
  download_concurrency: 1
  upload_concurrency: 1
  use_resumable_state: true
  restore_schema_on_cluster: ""
  upload_by_part: true
  download_by_part: true
  restore_database_mapping: {}
clickhouse:
  username: default
  password: "XXXXXXX"
  host: 10.18.159.229
  port: 8010
  timeout: 5m
  freeze_by_part: false
  secure: false
  skip_verify: false
  sync_replicated_tables: true
  log_sql_queries: true
 
  skip_tables:
  - system.*
  - default.*
  - information_schema.*
  - finance_d_ksha.*
  - dm_goa_new.*
  - INFORMATION_SCHEMA.*
s3:
  access_key: "xxxxxx"                   # S3_ACCESS_KEY，<AWS访问密钥> 
  secret_key: "xxxxxx"                   # S3_SECRET_KEY 
  bucket: "datasafe"                       # S3_BUCKET，<存储桶BUCKET名称>                  # S3_ENDPOINT   
  endpoint: "http://oss-cn-uat.com"
  force_path_style: true          # S3_FORCE_PATH_STYLE 
  path: "backup"                         # S3_PATH ， <备份路径> 
  debug: true                     # S3_DEBUG
  disable_ssl: false               # S3_DISABLE_SSL 
  part_size: 536870912
  compression_level: 1             # S3_COMPRESSION_LEVEL 
  compression_format: tar          # S3_COMPRESSION_FORMAT 
```

> 4.Is your source `clickhouse-server` run as standalone or inside docker container?

the source clickhouse-server and destination clickhouse-server  run as standalone 

> 5. the source `clickhouse-server` and destination `clickhouse-server`  run as standalone  , two shards  two replicas on physical machine 

> 6.How did you move data between the source and destination server?

I want to backup to s3 ,and restored from s3,i dont konw it is can be come true ?  so i ask you for help me.
