### ISSUE TITLE
Encrypted Password

### ISSUE THREAD

**Issue by dpetiz** [Altinity/clickhouse-backup#745]
Clickhouse supports the user creation with sha256.
In my environments i changed to sha256 so i replaced the clear text passwords.

The backup script should be able to parse sha256 passwords but it seems to work only with clear text.
Feature asked: SHA256 password support
Existing code:
```
clickhouse:
  username: default                # CLICKHOUSE_USERNAME
  password: ""                     # CLICKHOUSE_PASSWORD
```
Feature Asked:
```
clickhouse:
  username: default                # CLICKHOUSE_USERNAME
  password: ""                     # CLICKHOUSE_PASSWORD
  password_aes "" #CLICKHOUSE_PASSWORD_IN_AES256 <- TO BE ADDED
```
