### ISSUE TITLE
clickhouse-backup stops resolving cluster and shard macros in s3 endpoint url during the restore job

### ISSUE THREAD

**Issue by chief-rocka** [Altinity/clickhouse-backup#750]
I have clickhouse installed on kubernetes. I am using clickhouse-backup to backup the default database to s3 following the example on github. https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

It starts off resolving the macros fine `GET /clickhouse/backup/eventstore/0/` but then it stops resolving the macros `GET /clickhouse/backup/%7Bcluster%7D/%7Bshard%7D/tli/hjlwmcqtpgyqptixsyallxpxagopv?x-id=GetObject HTTP/1.1` This happens right after all the `DROP TABLE IF EXISTS` statements.

Request
```
2023/09/15 17:55:34.881522  info [s3:DEBUG] Request
GET /clickhouse/backup/%7Bcluster%7D/%7Bshard%7D/tli/hjlwmcqtpgyqptixsyallxpxagopv?x-id=GetObject HTTP/1.1
Host: *****.svc.cluster.local:9000
User-Agent: aws-sdk-go-v2/1.18.1 os/linux lang/go/1.21.0 md/GOOS/linux md/GOARCH/amd64 api/s3/1.34.0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: e871d186-1ffe-4426-916b-df31df115862
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=*****/20230915/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=*****
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230915T175534Z
```

Response
```
2023/09/15 17:55:34.886755  info [s3:DEBUG] Response
HTTP/1.1 404 Not Found
Content-Length: 415
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 15 Sep 2023 17:55:34 GMT
No-Gzip-Compression: true
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1785241B66C4AD2A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```

Error
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>backup/{cluster}/{shard}/tli/hjlwmcqtpgyqptixsyallxpxagopv</Key><BucketName>clickhouse</BucketName><Resource>/clickh  
ouse/backup/{cluster}/{shard}/tli/hjlwmcqtpgyqptixsyallxpxagopv</Resource><RequestId>1785241B66C4AD2A</RequestId><HostId>f79f5349-3db3-4897-b3fd-12bb7b3352cc</HostId></Error>
2023/09/15 17:55:34.886836  info [s3:DEBUG] request failed with unretryable error https response error StatusCode: 404, RequestID: 1785241B66C4AD2A, HostID: f79f5349-3db3-4897-b3fd-12bb7b3352cc, NoSuchKey:
2023/09/15 17:55:34.886881  info clickhouse connection closed logger=clickhouse
2023/09/15 17:55:34.886900 error metrics.ExecuteWithMetrics(restore_remote) return error: operation error S3: GetObject, https response error StatusCode: 404, RequestID: 1785241B66C4AD2A, HostID: f79f5349-3db3-4897-b3fd-12bb7b3352cc, NoSuchKey: logger=metrics
2023/09/15 17:55:34.886925 debug api.status.stop -> status.commands[7] == {ActionRowStatus:{Command:restore_remote --schema --rm chi-eventstore-eventstore-0-0-full-2023-09-15-17-52-27 Status:error Start: 2023-09-15 17:55:07 Finish:2023-09-15 17:55:34 Error:operation error S3: GetObject, https response error StatusCode: 404, RequestID: 1785241B66C4AD2A, HostID: f79f5349-3db3-4897-b3fd-12bb7b3352cc, NoSuchKey: } Ctx:<nil> Cancel:<nil>} logger=status
2023/09/15 17:55:34.886947 error API /backup/actions error: operation error S3: GetObject, https response error StatusCode: 404, RequestID: 1785241B66C4AD2A, HostID: f79f5349-3db3-4897-b3fd-12bb7b3352cc, NoSuchKey:  logger=server
```
Versions
- clickhouse-server:23.6.2.18
- clickhouse-backup:2.4.0

Config for s3 disk
```xml
config.d/backup_storage_config.xml: |
  <?xml version="1.0"?>
  <clickhouse>
    <storage_configuration>
      <disks>
        <backup>
          <type>s3</type>
          <endpoint>https://*****.svc.cluster.local:9000/clickhouse/backup/{cluster}/{shard}/</endpoint>
          <access_key_id>*****</access_key_id>
          <secret_access_key>*****</secret_access_key>
          <prefer_not_to_merge>true</prefer_not_to_merge>
          <skip_access_check>true</skip_access_check>
          <send_metadata>false</send_metadata>
          <cache_enabled>false</cache_enabled>
        </backup>
      </disks>
    </storage_configuration>
    <backups>
      <allowed_disk>backup</allowed_disk>
      <allowed_path>/backup/</allowed_path>
      <allow_concurrent_backups>false</allow_concurrent_backups>
      <allow_concurrent_restores>false</allow_concurrent_restores>
    </backups>
  </clickhouse>
```

clickhouse config

```yaml
general:
    remote_storage: s3
    max_file_size: 0
    disable_progress_bar: true
    backups_to_keep_local: -1
    backups_to_keep_remote: 3
    log_level: debug
    allow_empty_backups: true
    download_concurrency: 8
    upload_concurrency: 3
    use_resumable_state: true
    restore_schema_on_cluster: '{cluster}'
    upload_by_part: true
    download_by_part: false
    restore_database_mapping: {}
    retries_on_failure: 3
    retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    sharded_operation_mode: ""
    retriesduration: 30s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: *****
    password: *****
    host: localhost
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    skip_table_engines: []
    timeout: 4h
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: true
    embedded_backup_disk: backup
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: true
    sync_replicated_tables: true
    log_sql_queries: true
    config_dir: /etc/clickhouse-server/
    restart_command: exec:systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: /etc/ssl/certs/ca-certificates.crt
    debug: false
s3:
    access_key: *****
    secret_key: *****
    bucket: clickhouse
    endpoint: https://*****.svc.cluster.local:9000
    region: us-east-1
    acl: private
    assume_role_arn: ""
    force_path_style: true
    path: backup/{cluster}/{shard}
    object_disk_path: object_disk/{cluster}/{shard}
    disable_ssl: true
    compression_level: 1
    compression_format: none
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: true
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 9
    part_size: 0
    max_parts_count: 10000
    allow_multipart_download: false
    object_labels: {}
    debug: true
gcs:
    credentials_file: ""
    credentials_json: ""
    credentials_json_encoded: ""
    bucket: ""
    path: ""
    object_disk_path: ""
    compression_level: 1
    compression_format: tar
    debug: false
    endpoint: ""
    storage_class: STANDARD
    object_labels: {}
    custom_storage_class_map: {}
    client_pool_size: 500
cos:
    url: ""
    timeout: 2m
    secret_id: ""
    secret_key: ""
    path: ""
    compression_format: tar
    compression_level: 1
    debug: false
api:
    listen: 0.0.0.0:7171
    enable_metrics: true
    enable_pprof: false
    username: ""
    password: ""
    secure: false
    certificate_file: ""
    private_key_file: ""
    ca_cert_file: ""
    ca_key_file: ""
    create_integration_tables: true
    integration_tables_host: localhost
    allow_parallel: true
    complete_resumable_after_restart: true
ftp:
    address: ""
    timeout: 2m
    username: ""
    password: ""
    tls: false
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 9
    debug: false
sftp:
    address: ""
    port: 22
    username: ""
    password: ""
    key: ""
    path: ""
    object_disk_path: ""
    compression_format: tar
    compression_level: 1
    concurrency: 9
    debug: false
azblob:
    endpoint_schema: https
    endpoint_suffix: core.windows.net
    account_name: ""
    account_key: ""
    sas: ""
    use_managed_identity: false
    container: ""
    path: ""
    object_disk_path: ""
    compression_level: 1
    compression_format: tar
    sse_key: ""
    buffer_size: 0
    buffer_count: 3
    max_parts_count: 5000
    timeout: 15m
custom:
    upload_command: ""
    download_command: ""
    list_command: ""
    delete_command: ""
    command_timeout: 4h
    commandtimeoutduration: 4h0m0s  
```
