### ISSUE TITLE
 error open /var/lib/clickhouse/flags/force_drop_table: no such file or directory

### ISSUE THREAD

**Issue by zouwenjie00** [Altinity/clickhouse-backup#751]
Hi：
   I use clickhouse-backup in k8s cluster,when i exec the restore  command in pod ：
 `clickhouse-backup restore_remote backup20230918-2 -d -s --rm `
but there had show error message is ： `error open /var/lib/clickhouse/flags/force_drop_table: no such file or directory`

1. entry pod：
```
kubectl exec -it chi-demo-pod-cluster-clickhouse-0-0-0 --container clickhouse-backup -n clickhouse -- bash
```

2.backup to s3:
```
clickhouse-backup create_remote backup20230918-2
```

3.s3 have two file :
```
backup/shard-0/backup20230918-2/metadata.json
backup/shard-0/backup20230918-2/metadata/test/backup.json
```

4.restore:
```
 clickhouse-backup restore_remote backup20230918-2 -d -s --rm 
```

the CRD config file is ：

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "demo-pod-cluster"
  namespace: clickhouse
  labels:
    datamars.kubernetes.io/engine: Clickhouse
spec:
  defaults:
    templates:
      serviceTemplate: service-template
      podTemplate: pod-template
      #dataVolumeClaimTemplate: volume-claim
  configuration:
    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1
      timezone: Asia/Shanghai
      #max_partition_size_to_drop: 60000000000
      #max_table_size_to_drop: 60000000000
      #clickhouse-path: /var/lib/clickhouse/flags/force_drop_table
    profiles:
      readonly/readonly: "1"
      normal_ddl/allow_ddl: "1"
      normal_ddl/readonly: "0"
    users:
      #ck_test/default: secret
      ck_test/networks/ip: "::/0"
      ck_test/password: 123456
      ck_test/profile: default
      ck_test/access_management: 1
      testpwduser2/k8s_secret_password: clickhouse/demo-pod-cluster-clickhouse-auto-secret/secret
      testpwduser2/networks/ip: "::/0"
      testpwduser2/profile: default
      testpwduser2/access_management: 1
      testpwduser33/networks/ip: "::/0"
      testpwduser33/profile: default
      testpwduser33/access_management: 1
      testpwduser33/k8s_secret_password: clickhouse/ck-fe55918999186bbcb55ad/OPERATOR_PASSWORD
    zookeeper:
      nodes:
        - host: zookeeper-cluster-demo-0.zookeeper-cluster-demo-headless.zookeeper.svc.cluster.local
          port: 2181
        - host: zookeeper-cluster-demo-1.zookeeper-cluster-demo-headless.zookeeper.svc.cluster.local
          port: 2181
        - host: zookeeper-cluster-demo-2.zookeeper-cluster-demo-headless.zookeeper.svc.cluster.local
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
    clusters:
      - name: "clickhouse"
        secret:
          auto: "True"
        layout:
          shardsCount: 1
          replicasCount: 1
        secret:
          auto: "True"
    files:
      /var/lib/clickhouse/flags/force_drop_table: |
        <yandex>
          <max_partition_size_to_drop>0</max_partition_size_to_drop>
          <max_table_size_to_drop>0</max_table_size_to_drop>
        </yandex>
      ch-backup.yaml: |
        general:
          remote_storage: "none"
          disable_progress_bar: false
          backup_to_keep_local: 1
          backups_to_keep_remote: 0
        clickhouse:
          username: default
          password: ""
          host: localhost
          data_path: /var/lib/clickhouse
          disk_mapping:
            default: /var/lib/clickhouse
          skip_tables:
            - system.*
          timeout: 5m
        api:
          listen: "0.0.0.0:7171"
          enable_metrics: true
  templates:
    serviceTemplates:
      - name: service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
          clusterIP: None

    podTemplates:
      - name: pod-template
        metadata:
          annotations:
            operator.datamars.org/volumeType: LocalStorage
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: worker
          schedulerName: datamars-scheduler
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
          containers:
            - name: clickhouse
              imagePullPolicy: Always
              #image: image.xxx.com/datamars/clickhouse-server:yd.21.3.19.1
              image: image.xxx.com/datamars/clickhouse:22.2.2.1
              volumeMounts:
                # 挂载数据文件路径
                - name: data
                  mountPath: /var/lib/clickhouse
                # 挂载日志文件路径
                - name: log
                  mountPath: /var/log/clickhouse-server
              resources:
                # 配置cpu和内存大小
                limits:
                  memory: "2Gi"
                  cpu: "2"
                requests:
                  memory: "2Gi"
                  cpu: "2"
            - name: clickhouse-backup
              image: image.xxx.com/datamars/clickhouse-backup:2.4.1
              imagePullPolicy: Always
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              env:
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "3"
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_ACL
                  value: "private"
                - name: S3_ENDPOINT
                  value: http://oss-cn-uat.xxx.com
                - name: S3_BUCKET
                  value: datasafe
                - name: S3_PATH
                  value: backup/shard-{shard}
                - name: S3_ACCESS_KEY
                  value: xxx
                - name: S3_SECRET_KEY
                  value: xxx
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                - name: S3_DISABLE_SSL
                  value: "true"
                - name: S3_DEBUG
                  value: "true"
                - name: PASSWORD
                  value: "123456"
              ports:
                - name: backup-rest
                  containerPort: 7171
    volumeClaimTemplates:
      - name: data
        metadata:
          annotations:
            operator.datamars.org/diskType: local_hdd
        #reclaimPolicy: Retain
        spec:
          storageClassName: "datamars-default-lvm"
          accessModes:
            - ReadWriteOnce
          resources:
          # pv的存储大小
            requests:
              storage: 2Gi
      - name: log
        metadata:
          annotations:
            operator.datamars.org/diskType: local_hdd
        #reclaimPolicy: Retain
        spec:
          storageClassName: "datamars-log-default-lvm"
          accessModes:
            - ReadWriteOnce
          resources:
          # pv的存储大小
            requests:
              storage: 2Gi
```

**Comment by Slach** [comment]
```
  files:
      /var/lib/clickhouse/flags/force_drop_table: |
        <yandex>
          <max_partition_size_to_drop>0</max_partition_size_to_drop>
          <max_table_size_to_drop>0</max_table_size_to_drop>
        </yandex>
```

this part has no sense and will do nothing

1) `flags` folder doesn't contains XML
this is just empty files which means flags will change some behaviors of `clickhouse-server`

2) files with absolute path will not mount file from the root by security reason


properly, will use something like that:
```yaml
    files:
      config.d/force_drop_table.xml: |
        <yandex>
          <max_partition_size_to_drop>0</max_partition_size_to_drop>
          <max_table_size_to_drop>0</max_table_size_to_drop>
        </yandex>
```

and you need direct access to `data` volume from `clickhouse` container inside `clickhouse-backup` container

so just add
```yaml
            - name: clickhouse-backup
              image: image.xxx.com/datamars/clickhouse-backup:2.4.1
              volumeMounts:
                - name: data
                  mountPath: /var/lib/clickhouse
```


sorry for late reply
