### ISSUE TITLE
AWS EKS IRSA doesn't work

### ISSUE THREAD

**Issue by mglotov** [Altinity/clickhouse-backup#798]
`clickhouse-backup` can't connect to s3 because the default order of getting AWS creds is changed. 

We use [AWS EKS IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to provide necessary permissions for apps. This is a recommended and secured way of working with AWS services from an EKS cluster. 

Our clickhouse installation looks like this:
```
...    
    podTemplates:
      - name: clickhouse-22.8-lts
        # type PodSpec struct {} from k8s.io/core/v1
        spec:
          serviceAccount: clickhouse
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.8
              volumeMounts:
                - name: clickhouse-pv
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "1536Mi"
                  cpu: "500m"
                limits:
                  memory: "1536Mi"
                  cpu: "1"
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:master
              imagePullPolicy: Always
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              env:
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: UPLOAD_CONCURRENCY
                  value: "1"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "14"
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_DEBUG
                  value: "true"
                - name: S3_REGION
                  value: ${local.region}
                - name: S3_BUCKET
                  value: "${local.name_staging}-clickhouse-backups"
                - name: S3_PATH
                  value: backup/shard-{shard}
                - name: S3_ACL
                  value: ""
                - name: CLICKHOUSE_SKIP_TABLES
                  value: "system.*,INFORMATION_SCHEMA.*,default.*" # All tables except these will be backed up 
              ports:
                - name: backup-rest
                  containerPort: 7171
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: clickhouse-pv
```
The `clickhouse` serviceAccount has the required annotation. 
When the `clickhouse-backup` container starts it complains that it cannot assume AWS Role:
```
2023/12/12 09:13:33.346085 debug /tmp/.clickhouse-backup-metadata.cache.S3 load 0 elements logger=s3
2023/12/12 09:13:33.354932  warn BackupList bd.Walk return error: operation error S3: ListObjectsV2, get identity: get credentials: failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, get identity: get credentials: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: d075eb45-aa80-4eb4-8711-0da580729577, api error AccessDenied: User: arn:aws:sts::ACCOUNT_ID:assumed-role/ROLE_NAME/1702372412996829909 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME logger=s3
```

As you can see, it tries to assume itself. It happens because of this code https://github.com/Altinity/clickhouse-backup/blob/d79255fb8b5ad7149e50eb33f835cced27f671f5/pkg/storage/s3.go#L119

When IRSA is used, the `AWS_ROLE_ARN` is automatically set for a pod. According the code above, `clickhouse-backup` sees this variable and tries to use it (assume role), but role has only the next permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "clickhouse-backup-s3-access-to-files",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::BUCKET_NAME/*"
        },
        {
            "Sid": "clickhouse-backup-s3-access-to-bucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketVersioning"
            ],
            "Resource": "arn:aws:s3:::BUCKET_NAME"
        }
    ]
}
```
It will work as expected if code looks like something like this:
```
	if s.Config.AssumeRoleARN != ""  {
		stsClient := sts.NewFromConfig(awsConfig)
		awsConfig.Credentials = stscreds.NewAssumeRoleProvider(stsClient, s.Config.AssumeRoleARN)
	}
```
