### ISSUE TITLE
clickhouse-backups prometheus alert fires on nodes not targetted

### ISSUE THREAD

**Issue by tman5** [Altinity/clickhouse-backup#844]
In a replicated setup and the backup is only looking at the first member of the relica, this alert will fire for the other 2 nodes:

```
[(clickhouse_backup_last_backup_end{container_name="clickhouse-backup"} > 0 and time() - clickhouse_backup_last_backup_end{container_name="clickhouse-backup"} > 129600) or (clickhouse_backup_last_create_finish{container_name="clickhouse-backup"} > 0 and time() - clickhouse_backup_last_create_finish{container_name="clickhouse-backup"} > 129600) or (clickhouse_backup_last_upload_finish{container_name="clickhouse-backup"} > 0 and time() - clickhouse_backup_last_upload_finish{container_name="clickhouse-backup"} > 129600)](https://prometheus.dev.clarkinc.biz/graph?g0.expr=(clickhouse_backup_last_backup_end%7Bcontainer_name%3D%22clickhouse-backup%22%7D%20%3E%200%20and%20time()%20-%20clickhouse_backup_last_backup_end%7Bcontainer_name%3D%22clickhouse-backup%22%7D%20%3E%20129600)%20or%20(clickhouse_backup_last_create_finish%7Bcontainer_name%3D%22clickhouse-backup%22%7D%20%3E%200%20and%20time()%20-%20clickhouse_backup_last_create_finish%7Bcontainer_name%3D%22clickhouse-backup%22%7D%20%3E%20129600)%20or%20(clickhouse_backup_last_upload_finish%7Bcontainer_name%3D%22clickhouse-backup%22%7D%20%3E%200%20and%20time()%20-%20clickhouse_backup_last_upload_finish%7Bcontainer_name%3D%22clickhouse-backup%22%7D%20%3E%20129600)&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0.g0.range_input=1h.)
```

We'll get the following alerts on the 2 replicas not targetted for the backup job, but not for the first replica
```
`time() - clickhouse_backup_last_backup_end{pod_name="chi-clickhouse-replicated-0-1-0",namespace="dev"}` = `time() - clickhouse_backup_last_create_finish{pod_name="chi-clickhouse-replicated-0-1-0",namespace="dev"}` = 3d 10h 1m 19s `time() - clickhouse_backup_last_backup_finish{pod_name="chi-clickhouse-replicated-0-1-0",namespace="dev"}` = Check clickhouse-backup logs ```kubectl logs -n dev pods/chi-clickhouse-replicated-0-1-0 -c clickhouse-backup --since=48h```

`time() - clickhouse_backup_last_backup_end{pod_name="chi-clickhouse-replicated-0-2-0",namespace="dev"}` = `time() - clickhouse_backup_last_create_finish{pod_name="chi-clickhouse-replicated-0-2-0",namespace="dev"}` = 3d 10h 1m 19s `time() - clickhouse_backup_last_backup_finish{pod_name="chi-clickhouse-replicated-0-2-0",namespace="dev"}` = Check clickhouse-backup logs ```kubectl logs -n dev pods/chi-clickhouse-replicated-0-2-0 -c clickhouse-backup --since=48h```
```

Here is the backup config:

```yaml
                - name: CLICKHOUSE_SERVICES
                  value: chi-clickhouse-replicated-0-0
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: BACKUP_USER
                  value: backup
                - name: BACKUP_PASSWORD
                  value: "password"
                - name: MAKE_INCREMENT_BACKUP
                  value: "1"
                - name: FULL_BACKUP_WEEKDAY
                  value: "1"
```
