### ISSUE TITLE
GCS upload error

### ISSUE THREAD

**Issue by igorlidzhiev** [Altinity/clickhouse-backup#85]
Error while uploading backup to GCS
"dialing: invalid character '/' looking for beginning of value"

**Comment by AlexAkulov** [comment]
Hello!
Please, show your config file or values of envs with GCS prefix.

**Comment by igorlidzhiev** [comment]
> Hello!
> Please, show your config file or values of envs with GCS prefix.

Hello!
My config.yml
```
general:
  remote_storage: gcs
  disable_progress_bar: false
  backups_to_keep_local: 2
  backups_to_keep_remote: 4
clickhouse:
  username: user
  password: "password"
  host: clickhouse.fqdn
  port: 9000
  data_path: "/var/lib/clickhouse"
  skip_tables:
  - system.*
s3:
  access_key: ""
  secret_key: ""
  bucket: ""
  endpoint: ""
  region: us-east-1
  acl: private
  force_path_style: false
  path: ""
  disable_ssl: false
  part_size: 104857600
  compression_level: 1
  compression_format: gzip
  sse: ""
  disable_cert_verification: false
gcs:
  credentials_file: ""
  credentials_json: "/etc/clickhouse-backup/gcs.json"
  bucket: "gcs-backup"
  path: "clickhouse"
  compression_level: 1
  compression_format: gzip
```
