### ISSUE TITLE
When deployed with clickhouse operator, is it possible to run clickhouse backup on only one replica?

### ISSUE THREAD

**Issue by aaron276h** [Altinity/clickhouse-backup#863]
We want to run clickhouse-backup as a sidecar in Clickhouse, which we deploy using the [clickhouse operator](https://github.com/Altinity/clickhouse-operator). Since we only need to backup one replica for each shard, to avoid using unnecessary resources, is it possible to configure the operator to run the clickhouse backup on only one replica per shard?

**Comment by Slach** [comment]
by default, clickhouse-backup requires memory only when upload/download data usually memory fooprint is only 30-40mb without these operations

issue is not related to clickhouse-backup itself

you can specify a different `podTemplate` for each replica in shard

something like that
```
spec:
  templates:
  - name: pod-with-backup
    spec:
      containers:
      - name: clickhouse-backup
        image: altinity/clickhouse-backup:latest
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest  
  - name: pod-clickouse-only
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest  
  configuration:
    layout:
      shardsCount: 2 
      replicas:
      - templates:
          podTemplate: pod-with-backup
      - templates:
          podTemplate: pod-clickhouse-only
```

Moreover, it will more complex command sequence to restore data in this cluster in this case
need to add environment variable `RESTORE_SCHEMA_ON_CLUSTER="{cluster}"` in clickhouse-backup container spec
