### ISSUE TITLE
Version 2.5.0 cannot run

### ISSUE THREAD

**Issue by tman5** [Altinity/clickhouse-backup#889]
When trying to run any command for the latest 2.5.0 version, this error occurs:

```
7f5adad71b6f:/# clickhouse-backup server
bash: /bin/clickhouse-backup: Operation not permitted
7f5adad71b6f:/# clickhouse-backup help
bash: /bin/clickhouse-backup: Operation not permitted
7f5adad71b6f:/# clickhouse-backup version
bash: /bin/clickhouse-backup: Operation not permitted
7f5adad71b6f:/# clickhouse-backup --version
bash: /bin/clickhouse-backup: Operation not permitted

```

**Comment by Slach** [comment]
thanks for reporting, quick workaround
add 
CAP_SYS_NICE into your kubernetes manifests

`docker run --cap-add=SYS_NICE --rm altinity/clickhouse-backup:2.5.0 /bin/clickhouse-backup --help`

or 
```yaml
spec:
 templates:
   podTemplates:
   - name: with-backup
     spec:
       containers:
       - name: clickhouse-backup 
         securityContext:
           capabilities
             add:
             - SYS_NICE
```

```
