### ISSUE TITLE
shadow folder is missing in s3

### ISSUE THREAD

**Issue by myaswanth03** [Altinity/clickhouse-backup#897]
I set clickhouse back and stored those files in s3.
in the server shadow folder and few folders are available, those are copied to s3 automatically. But the shadow folder is not able to upload in s3 but remain folder metadata are uploaded automatically.
I set up crontab, it's working fine.

**Comment by Slach** [comment]
Is `clickhouse-backup` run on the same server where run `clickhouse-server`?
`clickhouse-backup` require direct access to sme file system with `clickhouse-server`

**Comment by Slach** [comment]
https://github.com/Altinity/clickhouse-backup/blob/master/ReadMe.md?plain=1#L12-L13

**Comment by myaswanth03** [comment]
running in the same server
shadow was created in the server, not copied to s3, but the remaining folders/files are copying normally

**Comment by myaswanth03** [comment]
2024/04/22 11:22:07.454246 debug finish xxxxxxxxx list_local with concurrency=1 len(table.Parts[...])=5 uploadedFiles=map[], uploadedBytes=0 logger=uploadTableData
2024/04/22 11:22:07.484801  info done                      backup=shard01-2024-04-22-11-22-hourly-incr duration=31ms operation=upload size=1.99KiB table=xxxxxxxx_price_list_local
2024/04/22 11:22:07.485124 debug start xxxxxxx with concurrency=1 len(table.Parts[...])=3 logger=uploadTableData
2024/04/22 11:22:07.485189 debug finish xxxxxxxwith concurrency=1 len(table.Parts[...])=3 uploadedFiles=map[], uploadedBytes=0 logger=uploadTableData 



uploadedBytes=0

**Comment by Slach** [comment]
> running in the same server

is it standalone server? or clickhouse-server is running in container?

**Comment by myaswanth03** [comment]
> is it standalone server? or clickhouse-server is running in container?

Not in container

**Comment by Slach** [comment]
ok. let's figure out
could you share

`clickhouse-client -q "SELECT * FROM system.disks"` ?

**Comment by myaswanth03** [comment]
> clickhouse-client -q "SELECT * FROM system.disks"

default /data/  95907753984     105554829312    0    local

**Comment by Slach** [comment]
could

**Comment by Slach** [comment]
could you share 
`clickhouse-backup print-config`

without sensitive credentials?

**Comment by myaswanth03** [comment]
```yaml
general:
  remote_storage: s3
  disable_progress_bar: false
  backups_to_keep_local: 3
  backups_to_keep_remote: 25
clickhouse:
  host: localhost
  port: 9000
  config_dir: /etc/clickhouse-server
  debug: false
  disk_mapping: {}
  freeze_by_part: false
  log_sql_queries: true
  password: ''
  secure: false
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  skip_verify: false
  sync_replicated_tables: true
  timeout: 5m
  username: default
s3:
    access_key: "xxxx"
    secret_key: "xxx"
    bucket: "xxxx"
    endpoint: ""
    region: xxxx
    acl: private
    assume_role_arn: ""
    force_path_style: false
    path: ""
    object_disk_path: ""
    disable_ssl: false
    compression_level: 1
    compression_format: tar
    sse: ""
    sse_kms_key_id: ""
    sse_customer_algorithm: ""
    sse_customer_key: ""
    sse_customer_key_md5: ""
    sse_kms_encryption_context: ""
    disable_cert_verification: false
    use_custom_storage_class: false
    storage_class: STANDARD
    custom_storage_class_map: {}
    concurrency: 5
    part_size: 0
    max_parts_count: 256
    allow_multipart_download: false
    object_labels: {}
    request_payer: ""
    debug: false
```
