### ISSUE TITLE
driver: bad connection on Ping

### ISSUE THREAD

**Issue by DrissiReda** [Altinity/clickhouse-backup#94]
I tried doing a simple
```
clickhouse-backup tables
```
And I get this error:

```
2020/06/09 12:31:48 can't connect to clickouse with: driver: bad connection
```

After some debugging I've seen it happens on `clickhouse.go 95`

My clickhouse database version is 20.3.8.53. I'm running the database in a docker and mounting /var/lib/clickhouse to my host.

With this config:

```yaml
general:
  remote_storage: s3
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
clickhouse:
  username: default
  password: ""
  host: localhost
  port: 8123
  data_path: "/var/lib/clickhouse"
  skip_tables:
  - system.*
  timeout: 30s
  freeze_by_part: true
s3:
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "chbkp"
  endpoint: "localhost:9000"
  region: us-east-1
  acl: private
  force_path_style: false
  path: ""
  disable_ssl: false
  part_size: 104857600
  compression_level: 1
  compression_format: gzip
  sse: ""
  disable_cert_verification: false

```

Does anyone have any suggestions?
