### ISSUE TITLE
custom TLS self-signed cert for S3 return error even when S3_DISABLE_CERT_VALIDATION=true

### ISSUE THREAD

**Issue by sanjeev3d** [Altinity/clickhouse-backup#960]
An error occurred while attempting to upload a backup to S3 [MINIO]. The error message indicates that the maximum number of attempts was exceeded and there was a failure to verify the TLS certificate.

Error Message
```
SELECT status, error FROM system.backup_actions WHERE command='upload chi-cliff-cliffcluster-replica0-shard0.ns-rm-yb-clicktt.svc.cluster.local-full-2024-07-25-07-50-12'

error: one of upload table go-routine return error: 
one of uploadTableData go-routine return error: can't upload: operation error S3: PutObject, exceeded maximum number of attempts, 3, https response error 
StatusCode: 0, RequestID: , HostID: , 
request send failed, 
Put "https://[xxxxxxxxxx]:30000/yb-backup/backup/shard-shard0/chi-cliff-cliffcluster-replica0-shard0.ns-rm-yb-clicktt.svc.cluster.local-full-2024-07-25-07-50-12/shadow/test_db/mydata/default_4_0_0_0.tar?x-id=PutObject": 
tls: failed to verify certificate: x509: certificate signed by unknown authority
```

The configmap for clickhouse-backup container is as follows:

```

data:
  ALLOW_EMPTY_BACKUPS: "true"
  API_CREATE_INTEGRATION_TABLES: "true"
  API_LISTEN: 0.0.0.0:7171
  BACKUPS_TO_KEEP_REMOTE: "3"
  LOG_LEVEL: debug
  REMOTE_STORAGE: s3
  S3_ACCESS_KEY: xxxxx
  S3_ACL: private
  S3_BUCKET: yb-backup
  S3_DEBUG: "true"
  S3_DISABLE_SSL: "true"
  S3_ENDPOINT: xxxxxxxx
  S3_FORCE_PATH_STYLE: "true"
  S3_PATH: backup/shard-{shard}
  S3_DISABLE_CERT_VALIDATION: "true"
  S3_SECRET_KEY: xxxxx
```
