### ISSUE TITLE
 Error during restore_remote operation: "can't create table test_db

### ISSUE THREAD

**Issue by sanjeev3d** [Altinity/clickhouse-backup#962]
I'm doing restoration POC in one of env by droping database using command **DROP DATABASE test_db ON CLUSTER 'cliffcluster'**
but getting error

 An error occurred during the restore_remote operation on the ClickHouse instance. The error message indicates that the table
test_db
.
mydata_distributed
could not be created due to an existing directory. Below are the details of the error:

Error Details:

```
error restore_remote --schema --rm chi-cliff-cliffcluster-replica0-shard0.click.svc.cluster.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard0.click.svc.cluster.local
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
SELECT start,finish,status,error FROM system.backup_actions WHERE command='restore_remote --schema --rm chi-cliff-cliffcluster-replica0-shard0.click.svc.clusterlocal-full-2024-07-26-11-06-43'
2024-07-26 11:11:24	2024-07-26 11:11:25	error	can't create table `test_db`.`mydata_distributed`: code: 57, message: Directory for table data store/b95/b954e04a-128e-49f2-b061-71f76c0d9d7e/ already exists after 2 times, please check your schema dependencies
```

**Comment by Slach** [comment]
use `DROP DATABASE test_db ON CLUSTER 'cliffcluster' SYNC` instead of `DROP DATABASE test_db ON CLUSTER 'cliffcluster'`

second command don't delete data to allow UNDROP in 480 seconds
look https://clickhouse.com/docs/en/sql-reference/statements/undrop for details

when you use --rm then will apply DROP TABLE IF NOT EXISTS ... SYNC (but you drop table, it was not necessary)

**Comment by sanjeev3d** [comment]
Thanks @Slach It working But I have one doubt

I deployed cluster in 3-shards and 3-replica and svc are like this

```
chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica1-shard0.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica1-shard1.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica1-shard2.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica2-shard0.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica2-shard1.click.svc.uhn7klt22.local
chi-cliff-cliffcluster-replica2-shard2.click.svc.uhn7klt22.local
```


My backup config

`CLICKHOUSE_SERVICES: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local`

where restoration config is


```
          - name: CLICKHOUSE_SCHEMA_RESTORE_SERVICES
            value: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local
         
          - name: CLICKHOUSE_DATA_RESTORE_SERVICES
            value: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local
```

plz guide me correct way to take backup and restore same


By this backup is restoring of only first replica-0 of each shards.  do i need take backup of each shards and replica..?

**Comment by Slach** [comment]
your restore config is wrong

you shall restore schema on all 9 replicas
```yaml
  - name: CLICKHOUSE_SCHEMA_RESTORE_SERVICES
    value: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica1-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica1-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica1-shard2.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica2-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica2-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica2-shard2.click.svc.uhn7klt22.local 
```            

but restore data only in first replica in each shard
```yaml
    - name: CLICKHOUSE_DATA_RESTORE_SERVICES
      value: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local
```

**Comment by Slach** [comment]
read https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster

**Comment by sanjeev3d** [comment]
> your restore config is wrong
> 
> you shall restore data on all 9 replicas
> 
> ```yaml
>   - name: CLICKHOUSE_SCHEMA_RESTORE_SERVICES
>     value: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica1-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica1-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica1-shard2.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica2-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica2-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica2-shard2.click.svc.uhn7klt22.local 
> ```
> 
> but restore data only in first replica in each shard
> 
> ```yaml
>     - name: CLICKHOUSE_DATA_RESTORE_SERVICES
>       value: chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local,chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local
> ```

This way I have already test using your backup restore github page but getting this error, It restore on only first three

 kubectl logs -f clickhouse-backup-restore-ngn6s -n click
 
```
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
INSERT INTO system.backup_actions(command) VALUES('restore_remote --schema --rm chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43')
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
still in progress chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
schema chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard0.click.svc.uhn7klt22.local RESTORED
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
INSERT INTO system.backup_actions(command) VALUES('restore_remote --schema --rm chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43')
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
still in progress chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
schema chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klt22.local RESTORED
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
INSERT INTO system.backup_actions(command) VALUES('restore_remote --schema --rm chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43')
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
still in progress chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
schema chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local-full-2024-07-26-11-06-43 on chi-cliff-cliffcluster-replica0-shard2.click.svc.uhn7klt22.local RESTORED
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
Remote backup not found for chi-cliff-cliffcluster-replica1-shard0.click.svc.uhn7klt22.local
```

**Comment by Slach** [comment]
check restore script
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md?plain=1#L428

your 
`chi-cliff-cliffcluster-replica1-shard0`
different name conversion like -0-0

remove `.click.svc.uhn7klt22.local` from host names in kind: Job environment variables


did you change `serviceTemplates` in your `kind: ClickHouseInstallation` manifests?

**Comment by sanjeev3d** [comment]
Without complete svc name I'm getting DNS error

 kubectl logs -f clickhouse-backup-restore-9qrtv -n click
```
<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
Cannot resolve host (chi-cliff-cliffcluster-replica0-shard0), error 0: Host not found.
Code: 198. DB::NetException: Not found address of host: chi-cliff-cliffcluster-replica0-shard0. (DNS_ERROR)
```

Naming convention different because of replica and shards I have defined in this way, sharing complete ClickHouseInstallation

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "cliff"
spec:
  defaults:
    templates:
            podTemplate: pod-template-with-volumes-shard
            serviceTemplate: chi-service-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.click
          port: 2181
        - host: zookeeper-1.zookeepers.click
          port: 2181
        - host: zookeeper-2.zookeepers.click
          port: 2181
    settings:
      remote_servers/all-replicated/secret: cliff
      remote_servers/all-sharded/secret: cliff
      remote_servers/cliffcluster/secret: cliff
      remote_servers/all-replicated/secret: distributed
      remote_servers/all-sharded/secret: distributed
      remote_servers/cliffcluster/secret: distributed
      remote_servers/all-replicated/secret: default
      remote_servers/all-sharded/secret: default
      remote_servers/cliffcluster/secret: default
      disable_internal_dns_cache: 1
    users:
      # test user has 'password' specified, while admin user has 'password_sha256_hex' specified
      default/networks/ip:
              - "0.0.0.0/0"
              - "::/0"
      admin/password: xxxxxx
      admin/access_management: 1
      admin/networks/ip:
              - "0.0.0.0/0"
              - "::/0"
    clusters:
      - name: "cliffcluster"
        layout:
          shards:
            - name: shard0
              replicasCount: 3
              templates:
                 podTemplate: pod-template-with-volumes-shard
              replicas:
                - name: replica0-shard0
                - name: replica1-shard0
                - name: replica2-shard0
            - name: shard1
              replicasCount: 3
              templates:
                 podTemplate: pod-template-with-volumes-shard
              replicas:
                - name: replica0-shard1
                - name: replica1-shard1
                - name: replica2-shard1
            - name: shard2
              replicasCount: 3
              templates:
                 podTemplate: pod-template-with-volumes-shard
              replicas:
                - name: replica0-shard2
                - name: replica1-shard2
                - name: replica2-shard2
  templates:
    podTemplates:
      - name: pod-template-with-volumes-shard
          containers:
            - name: clickhouse
              image: clickhouse-server:24.4.2-alpine
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse
            - name: clickhouse-backup
              image: clickhouse-backup:master
              imagePullPolicy: Always
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse
              command:
                 - bash
                 - -xc
                 - "/bin/clickhouse-backup server"
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
              envFrom:
              - configMapRef:
                  name: clickhouse-backup-config
              ports:
                 - name: backup-rest
                   containerPort: 7171

    volumeClaimTemplates:
      - name: clickhouse-storage-template
        spec:
          # no storageClassName - means use default storageClassName
          storageClassName: robin-encrypt
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
    serviceTemplates:
      - name: chi-service-template
        generateName: "clickhouse-{chi}"
        spec:
          type: NodePort
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
            - name: interserver
              port: 9009
              targetPort: 9009
```
