### ISSUE TITLE
Restoring backup - Data only on node restored to

### ISSUE THREAD

**Issue by tman5** [Altinity/clickhouse-backup#973]
After restoring a backup to a cluster, the data only appears to be on the first node in the cluster. The other nodes don't have any disk space usage from the data. Here is the remote_server config:

```
remote_servers:
  cluster:
    shard:
      internal_replication: true
      replica:
        host: 201
        port: 9000
      replica:
        host: 202
        port: 9000
      replica:
        host: 203
        port: 9000
```

On ALL the nodes I ran the following:
```
clickhouse-backup restore_remote --rm --schema backup_name
```

On the first node (201) I ran the following:
```
clickhouse-backup restore_remote --rm  backup_name
```
