### ISSUE TITLE
S3_OBJECT_DISK_PATH - option to disable in backup config

### ISSUE THREAD

**Issue by jovanradin** [Altinity/clickhouse-backup#978]
After upgrade to latest version of clickhouse my backup failed few times and in logs i saw that i need to enable s3 object backup Before upgrade it was disabled and backup worked fine (without S3 disk, it is already on bucket and i don't need it).
my current config is:
```yaml
          - name: clickhouse-backup
              image: altinity/clickhouse-backup:2.5.20
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              env:
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: API_ENABLE_METRICS
                  value: "true"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_LOCAL
                  value: "2"
                # keep last 1 full week of backups
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "3"
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_REGION
                  value: eu-central-1
                - name: S3_BUCKET
                  value: xxx-ch02-backup
                - name: S3_PATH
                  value: "backup/{shard}"
                - name: S3_OBJECT_DISK_PATH
                  value: "object_disk/{shard}"
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                # 100mb part size
                - name: S3_PART_SIZE
                  value: "104857600"
                # Set compression type and level
                - name: CLICKHOUSE_BACKUP_COMPRESSION
                  value: "zstd"
                - name: CLICKHOUSE_BACKUP_COMPRESSION_LEVEL
                  value: "19"
```

Storage configuration:

```
merge_tree/allow_remote_fs_zero_copy_replication: false   
merge_tree/max_suspicious_broken_parts_bytes: 1073741824000
storage_configuration/disks/s3/type: "s3"      
storage_configuration/disks/s3/support_batch_delete: true 
storage_configuration/disks/s3/use_environment_credentials: true
storage_configuration/disks/s3/endpoint: "[https://xxx-ch02.s3.amazonaws.com/data/{shard}/](https://xxx-ch02.s3.amazonaws.com/data/%7Bshard%7D/)"
storage_configuration/disks/s3/region: "eu-central-1"     
storage_configuration/disks/s3/metadata_path: "/var/lib/clickhouse/disks/s3/"    
storage_configuration/disks/s3/min_bytes_for_seek: "1000"      
storage_configuration/disks/s3_cached/type: "cache"     
storage_configuration/disks/s3_cached/disk: "s3"     
storage_configuration/disks/s3_cached/path: "/var/lib/clickhouse/cache/s3/"  
storage_configuration/disks/s3_cached/max_size: "20Gi"     
storage_configuration/policies/s3_tiered/volumes/local/disk: "default"     
storage_configuration/policies/s3_tiered/volumes/remote/disk: "s3_cached"     
storage_configuration/policies/s3_tiered/move_factor: "0.25"     
storage_configuration/policies/s3_main/volumes/remote/disk: "s3_cached"
```

Can you add option to disable S3_OBJECT_DISK_PATH, current backup is 76tb for 3 days and it is superexpensive and it worked before without it  :)
Thanks.
