### ISSUE TITLE
watch command not working for create_remote backup

### ISSUE THREAD

**Issue by thatsk** [Altinity/clickhouse-backup#985]
i am running clickhouse-backup command process with --watch option 
```
[Unit]
Description=ClickHouse Backup Service
After=network.target

[Service]
ExecStart=/usr/bin/clickhouse-backup server --watch 
Restart=on-failure
Environment=PATH=/usr/local/bin:/usr/bin:/bin
Environment=CLICKHOUSE_BACKUP_CONFIG=/etc/clickhouse-backup/config.yml
StandardOutput=append:/var/log/clickhouse-backup.log
StandardError=append:/var/log/clickhouse-backup-error.log

[Install]
WantedBy=multi-user.target
```
also added config.yml
```
general:
    remote_storage: gcs
    max_file_size: 0
    backups_to_keep_local: 2
    backups_to_keep_remote: 5
    log_level: info
    allow_empty_backups: false
    download_concurrency: 20
    upload_concurrency: 20
    upload_max_bytes_per_second: 0
    download_max_bytes_per_second: 0
    object_disk_server_side_copy_concurrency: 32
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    restore_table_mapping: {}
    retries_on_failure: 3
    retries_pause: 30s
    watch_backup_name_template: clickhouse_backup_dev-{type}-{time:20060102150405}
    sharded_operation_mode: ""
    cpu_nice_priority: 15
    io_nice_priority: idle
    rbac_backup_always: true
    rbac_conflict_resolution: recreate
    retriesduration: 30s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
```
its not backing up to gcs what I am doing wrong ?
