### ISSUE TITLE
Whether Huawei OBS is supported?

### ISSUE THREAD

**Issue by liubo-it** [Altinity/clickhouse-backup#986]
Whether data can be backed up to HuaWei obs？ @Slach

**Comment by Slach** [comment]
directly not

looks like OBS is S3 compatible storage

try
```yaml
general:
  remote_storage: s3
s3:
   ...  
```

and report logs here if some issues happens
